### ISSUE TITLE
Constants for reply markups, content_type and chat_type 

### ISSUE THREAD

**Issue by jenkokov** [nickoala/telepot#10]
Hi! Thank you for a great lib! Did you think about add constants to the library? 
Like telepot.content_type.TEXT or tepepot.ReplyKeyboardMarkup. I read about telepot.namedtuple but I'm talking about code completion on editors and easiest supporting of code if API will be changed. What do you think about it? If you want, I can help with it.

**Comment by nickoala** [comment]
telepot.content_type.TEXT? No. Too cosmetic to my taste - adding some rather un-creative code for marginal benefits.

telepot.ReplyKeyboardMarkup? Maybe. Especially with the recent addition of a bunch of `InlineQueryResultXXX` objects, I think having their corresponding namedtuples in the library can ease the process of *creating* such objects.

I am working on including inline query right now. Hopefully an update will be coming out soon.

Thanks for the offer. I think I can handle the job myself.

**Comment by jenkokov** [comment]
Good, now I understand your point and waiting for updates. Thank you for the reply. I think the issue can be closed now.
