### ISSUE TITLE
Just a report

### ISSUE THREAD

**Issue by javierin** [nickoala/telepot#100]
Hi

I've seen that some changes have been made regarding new_chat_participant in the code, but i've found this message when a new user joined a supergroup and wanted to let you know just in case:

```
/usr/local/lib/python2.7/dist-packages/telepot/namedtuple.py:48: UserWarning: Unexpected fields: new_chat_participant
Bot API seems to have added new fields to the returned data. This version of namedtuple is not able to capture them.

Please upgrade telepot by:
  sudo pip install telepot --upgrade

If you still see this message after upgrade, that means I am still working to bring the code up-to-date. Please try upgrade again a few days later. In the meantime, you can access the new fields the old-fashioned way, through the raw dictionary.
  warnings.warn(s, UserWarning)
^CTraceback (most recent call last):
  File "bot.py", line 30, in <module>
    time.sleep(10)
KeyboardInterrupt
user@host:~/bot# sudo pip install telepot --upgrade
Requirement already up-to-date: telepot in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: urllib3>=1.15.1 in /usr/local/lib/python2.7/dist-packages (from telepot)

```

Cheers!

**Comment by zumoshi** [comment]
hello,
thanks for you report, @nickoala is working on an update ( #99 ). this issue will most likely be fixed in that update.

**Comment by nickoala** [comment]
The message looks like this:
```python
{'chat': {'id': -11111111, 'title': 'Moby', 'type': 'group'},
 'date': 1467664036,
 'from': {'first_name': 'Nick', 'id': 22222222, 'last_name': 'Lee'},
 'message_id': 12019,
 'new_chat_member': {'first_name': 'Chef',
                     'id': 99999999,
                     'username': 'KitchenBot'},
 'new_chat_participant': {'first_name': 'Chef',
                          'id': 99999999,
                          'username': 'KitchenBot'}}
```
The field `new_chat_member` is the current standard. However, to keep backward compatibility, Telegram keeps the old field `new_chat_participant` in the message. They are identical, as you can see.

Telepot's namedtuples follow the current standard, so it has the field `new_chat_member`. As you try to convert a message dictionary into a namedtuple (`telepot.namedtuple.Message(**msg)`), if there is any unexpected field, the above warning will be issued.

So, there is really nothing wrong. I hope you can tolerate the warning.
