### ISSUE TITLE
Thanks)

### ISSUE THREAD

**Issue by yellowmegaman** [nickoala/telepot#101]
Awesome thing this telepot is =)

One question though - i have priv channel with bot connected to it.
I can send messages to the channel.
But i can't make bot work ( response to command) in it.

Any advice?

**Comment by zumoshi** [comment]
Hello,
please take a look at issue #84 .

**Comment by yellowmegaman** [comment]
Thanks for reply!)

Actually i have no issues with sending message to private channel (i've already found out it's id)
bot.sendMessage('-XXXXXXXXXX', str('testmychannel'))

The question is, how to make bot listen to commands inside that channel

**Comment by zumoshi** [comment]
my bad i misread your issue.
i don't think that can be done. i just tried but even with privacy option disabled bot does not get notified of channel messages even though its added as an admin.

the only way i can think of is that you can make an inline bot than send the command you want to your bot as an inline query, you can than send your bots answer to channel by selecting it from inline query results.

or you can send the command to bot in a private chat and have bot respond in the channel.

**Comment by yellowmegaman** [comment]
Thank you again, i'll try. Sad thing that's not default telegram api functionality.
