### ISSUE TITLE
How can I translate my main class variables

### ISSUE THREAD

**Issue by bum-bum** [nickoala/telepot#104]
how can I do localization.
for example if user type /kr, then bot shows korean

**Comment by zumoshi** [comment]
hello,
telepot does not provide any special tools for localization, you need to convert all your string literals to use some localization libraries format (e.g. [gettext](https://docs.python.org/3/library/gettext.html)) than store each user's preference in a database or similar and use that when sending messages to the user.
than on commands like `/kr` you simply change the user's preference. unfortunately, I don't have a simple code example to provide atm but if you didn't manage to get it working ask here and i or @nickoala will try to add an example including localization to the examples directory.
