### ISSUE TITLE
Unauthorized Error

### ISSUE THREAD

**Issue by bhanu011** [nickoala/telepot#105]
I am trying to create new bot but after doing basics while testing my account i.e bot.getMe() I am facing this Unauthorized Error: (u'Unauthorized', 401, {u'eooro_code': 401, u'ok': False, u'description': u'Unauthorized'}). What is it saying, is it saying token is not correct? thanks!

**Comment by zumoshi** [comment]
Hello,
yes error 401 means that the token is not correct.
please check to see if you pasted it correctly, maybe a space is before or after the token or maybe its not complete (part of it is left off).
also note that using the `/revoke` command in [@botfather](http://telegram.me/botfather) disables the token. you can take your token from [@botfather](http://telegram.me/botfather) again using the `/token` command.

if you took a new token and checked it but it was still not working please provide relevant parts of your code so we can try to diagnose it.
you can also try using one of the examples provided [here](https://github.com/nickoala/telepot/tree/master/examples).

**Comment by bhanu011** [comment]
thank you for the reply, with same token id i am able to request by pasting this in web browser
https://api.telegram.org/bot123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11/getMe token id is different from the one displayed here.

But by using bot.getMe() i am not able to request/test my account. I am not sure if need to do take care of https while calling bot.getMe()

**Comment by nickoala** [comment]
I am able to do this on Python 3.5 (with a **real token**, of course):
```
>>> import telepot
>>> bot = telepot.Bot('1212121:AAAAAAAAAAAAAAAAAAAAAAAAAAAA')
>>> bot.getMe()
{'id': 1212121, 'username': 'KitchenBot', 'first_name': 'Kitchen'}
```
Can you try that, too?
