### ISSUE TITLE
Trigger a "sending" notification while a photo is being sent

### ISSUE THREAD

**Issue by wodim** [nickoala/telepot#106]
I am sending photos using `sendPhoto()`, but while they are being sent, the user does not receive this notification:

![2016-06-20_12-00-55](https://cloud.githubusercontent.com/assets/1001553/16190300/d475d8b2-36de-11e6-8520-320ee6c9f09a.png)

Any way to trigger it?

**Comment by zumoshi** [comment]
Hello,
yes , the method you are looking for is `sendChatAction`. from the [Reference](https://github.com/nickoala/telepot/blob/master/REFERENCE.md) : 

> sendChatAction(chat_id, action)
> 
> Tell the user that something is happening on the bot's side. The status is set for 5 seconds or less (when a message arrives from your bot, Telegram clients clear its typing status).
> 
> See: https://core.telegram.org/bots/api#sendchataction

this method can display all types of `sending X` messages, for sending photo specifically you can use the following code:

```python
# Uploading a file may take a while. Let user know you are doing something.
bot.sendChatAction(chat_id, 'upload_photo')
```

**Comment by wodim** [comment]
Thank you very much my dear.
