### ISSUE TITLE
Using both inline button and keyboard markups

### ISSUE THREAD

**Issue by kobybm1** [nickoala/telepot#110]
Hi and thank you for this great project!

Is it possible to use in the same message both "InlineKeyboardMarkup" and switch keyboard markup on the same message?
Right now when I'm sending messages I'm replacing the user keyboard with:
**_keyboard = {'keyboard': [['aa'],['aaa','aa']], 'resize_keyboard': True }
bot.sendMessage(user, message, reply_markup=keyboard)_**

And when I'm sending a button to the user it's like this:
    **_markup = InlineKeyboardMarkup(inline_keyboard=[
         [dict(text='BlaBlaBla, url='http://blablabla.com')]
     ])
    bot.sendMessage(user, mesage,reply_markup=markup )_**

How (If possible) I can send a button and also replace the user keyboard on the same message? (Currently I'm sending a dummy message with keyboard and then sending the button)

Thanks!

**Comment by zumoshi** [comment]
hello,
you don't have to use the `NamedTuples`, you simply provide an object representing the json to be sent to `reply_markup`. I did some tests (specifying both `keyboard` and `inlinekeyboard`) and it doesn't seem to be possible. but I don't think this is a telepot limitation, rather one from the bot API.

as you can see [here](https://core.telegram.org/bots/api#sendmessage) the manual uses the word `or` between them.
> 	InlineKeyboardMarkup **or** ReplyKeyboardMarkup **or** ReplyKeyboardHide **or** ForceReply

I may be wrong though. try asking [@BotSupport](http://telegram.me/botsupport).

**Comment by nickoala** [comment]
I agree with @zumoshi that there seems no way to include a custom keyboard **and** an inline keyboard in the same message. You should contact Telegram if you really want this feature.
