### ISSUE TITLE
Probably webhooks

### ISSUE THREAD

**Issue by lucas59356** [nickoala/telepot#111]
TelegramError: (u'Conflict: terminated by other long poll or webhook', 409, {u'error_code': 409, u'ok': 
False, u'description': u'Conflict: terminated by other long poll or webhook'})
![2016-06-24_20-32-39](https://cloud.githubusercontent.com/assets/15693688/16353039/d84d9b72-3a4a-11e6-9395-5fa596e55642.jpg)

**Comment by zumoshi** [comment]
hello,
maybe there are multiple instances of your bot running ?
or perhaps you gave your token to another bot-maker API and they set up a webhook. you can simply get a new token for the same bot using `/revoke` command at botfather, that will prevent any other instances from conflicting and also disables any webhooks. than use the new token in your bot.

**Comment by lucas59356** [comment]
Thank for the suggestion, I think too this is the problem. I test the same code at my pc,  an heroku vm and a koding vm

**Comment by lucas59356** [comment]
Problem solved, thank you for your time :)
