### ISSUE TITLE
Audio files filename is not retrieved

### ISSUE THREAD

**Issue by Searinox** [nickoala/telepot#112]
When an audio file is sent to the bot, such as an mp3, its name is shown in the conversation as the file is captioned with its name. The bot's message only contains a mime_type and while getFile() can find the correct extension, the file name itself is lost despite it clearly appearing in the conversation.

**Comment by zumoshi** [comment]
hello,
[telegram api](https://core.telegram.org/bots/api#audio) does not send the filename with an audio message currently, there is nothing telepot can do to fix that. however, you will get the title, performer and other id3 tags the mp3 file may have.

if you absolutely need the filename, try contacting [@BotSupport](http://telegram.me/botsupport).
