### ISSUE TITLE
getupdates() returns empty

### ISSUE THREAD

**Issue by amirghasemian** [nickoala/telepot#113]
hello
getupdates returns empty while I sent messages to the bot.
bot = telepot.Bot('222222222:VVVVVVVVVVVVVVVVVVVVVVV')
print(bot.getMe())
response = bot.getUpdates()
pprint(response)

**Comment by zumoshi** [comment]
hello,
i just tested it and there is no problem.
![image](https://cloud.githubusercontent.com/assets/4184939/16529524/aba0743a-3fd8-11e6-9e41-62c3f1f349b2.png)
_first before sending messages and then after sending messages, as expected first one is empty but second one has messages_

which telepot/python version are you using ?
also try using `/revoke` to get a new token from botfather , maybe another bot you set up before is consuming messages for this token.

**Comment by nickoala** [comment]
@amirghasemian, you probably **should get a new token** anyway. You accidentally exposed your bot's token in the original question. Anybody who gets hold of the token can pretend to be your bot. Token is a secret you should never reveal.

**Comment by nickoala** [comment]
@amirghasemian, I just erased your token and replaced it with a dummy. Be careful always.
