### ISSUE TITLE
Action when Timeout

### ISSUE THREAD

**Issue by stranger26** [nickoala/telepot#114]
Hey,

Is there anyway to execute an action when the bot closes that instance on timeout?

I'm using the following code for timeout:
`bot = telepot.DelegatorBot(TOKEN, [(per_from_id(), create_open(UserTracker, timeout=30))])
bot.message_loop(run_forever=True)`

Thanks! :)

**Comment by zumoshi** [comment]
hello,
yes , create a method called `on_close` in the `UserTracker` class. it will be called when the instance is closed (the reason , e.g. whether the timeout hit or an exception occurred is passed to that method as a parameter).
you can read more about `create_open` in the [telepot Reference](https://github.com/nickoala/telepot/blob/master/REFERENCE.md#telepot-delegate-create-open).

**Comment by stranger26** [comment]
Oh okay, so if I didn't understand wrong, j.open() and j.close() are empty functions for us to replace with? Thank you very much for clarifying tho.

**Comment by nickoala** [comment]
@stranger26, `j.close()` is not an empty function. It raises a `StopListening` exception to terminate the thread.
