### ISSUE TITLE
getting TOKEN from the command-line is not possible

### ISSUE THREAD

**Issue by pouyan021** [nickoala/telepot#116]
Hi

I've downloaded one of your skeletons(traditional,simple) but when i try to compile the code it says 

`TOKEN = sys.argv[1] 
IndexError: list index out of range
`

so what do you say? how should it be fixed?

thank you!

**Comment by zumoshi** [comment]
Hello,
how do you run it?
try putting your token after the filename when running the script:
```
$ python ./file.py TOKEN_HERE
```

**Comment by pouyan021** [comment]
Thanks a lot, I used pycharm to run it,i didn't try your way,is there anyway you know to fix this through the IDE as well? 


Get Outlook for Android






On Fri, Jul 1, 2016 at 9:16 PM +0430, "zumoshi" <notifications@github.com> wrote:












Hello,

how do you run it?

try putting your token after the filename when running the script:

$ python ./file.py TOKEN_HERE

**Comment by zumoshi** [comment]
you can either hard code the token in the code, (e.g. `TOKEN = 'YOUR TOKEN HERE'`), take it from a configuration file, or if you don't want to change the code put your token in pycharm's script parameters section of run configuration :

![image](https://cloud.githubusercontent.com/assets/4184939/16530560/f2cfc0e0-3fdd-11e6-8582-a1ba0d6b04ef.png)
![image](https://cloud.githubusercontent.com/assets/4184939/16530602/1dd8b0f8-3fde-11e6-8c48-4adf50272993.png)

this will simply append anything you put there after the filename when executing the script.

**Comment by pouyan021** [comment]
Hi


That was a lot of help for me,thanks a lot


Get Outlook for Android






On Fri, Jul 1, 2016 at 10:51 PM +0430, "zumoshi" <notifications@github.com> wrote:












you can either hard code the token in the code, (e.g. TOKEN = 'YOUR TOKEN HERE'), take it from a configuration file, or if you don't want to change the code put your token in pycharm's script parameters section of run configuration :









this will simply append anything you put there after the filename when executing the script.
