### ISSUE TITLE
Timeout of ChatHandler can't be None

### ISSUE THREAD

**Issue by CzBiX** [nickoala/telepot#120]

**Comment by nickoala** [comment]
Correct. It cannot be `None`. You must specify a time after which the handler will terminate. That time period serves as a kind of inactivity timeout - if a user has been silent for some seconds, he is treated as having left the chat, so the handler terminates.

**Comment by CzBiX** [comment]
I thought it could be `None` for forever.
Just see you recommend that timeout is not `None` in #2 , thanks for you explain it.
