### ISSUE TITLE
Nginx + Flask

### ISSUE THREAD

**Issue by lobomick** [nickoala/telepot#121]
I have Nginx over flask to redirect requests at port 8443 to flask on port 5000.
3 weeks ago it worked properly simply setting the defaults value on flask (host=127.0.0.1, port=5000) , but has stopped working. Now only it works if you put  flask directly on webhook at port 8443 defining host to 0.0.0.0 .
I've been debugging and in both cases the message arrives to the queue (pass_update) but the difference between one form and another seems that one consume the msg stored in the queue and the other no, simply put it in.
What am i doing wrong?

here is my bot run code (it's like an example...)

```

from queue import Queue
from flask import Flask, request
from mybot import Bot
from mybot.settings import WEBHOOK_PORT, WEBHOOK_CERT, WEBHOOK_CERT_KEY

app = Flask(__name__)
update_queue = Queue()   # channel between `app` and `bot`
bot = Bot(update_queue)
context = (WEBHOOK_CERT, WEBHOOK_CERT_KEY)
bot.message_loop()

@app.route('/mybot', methods=['POST'])
def pass_update():
    update_queue.put(request.data)  # pass update to bot
    return 'OK'

if __name__ == '__main__':
    app.run(
        # host='0.0.0.0',
        # port=WEBHOOK_PORT,
        ssl_context=context,
        debug=True)

```

**Comment by lobomick** [comment]
I think I `m going to develop my own solution using celery and passing telepot .

**Comment by nickoala** [comment]
In case you haven't totally left, shouldn't you supply the message queue to `message_loop()`?

```python
bot = telepot.Bot(TOKEN)

bot.message_loop(source=update_queue)
```

I am assuming you have overridden the appropriate methods in `bot`, so there is no need to supply a handler function or routing table to `message_loop()`.
