### ISSUE TITLE
ssl error

### ISSUE THREAD

**Issue by efazati** [nickoala/telepot#122]
my app receive some things like this. how fix it?

`SSLError: hostname 'api.telegram.org' doesn't match either of 'incapsula.com', '*.adpost.com', '*.aws.toyota.com', '*...`

**Comment by nickoala** [comment]
It seems your network is restricting access to some domains.

Open a browser, enter URL (after replacing token): `https://api.telegram.org/bot<token>/getMe`

What do you see?

**Comment by efazati** [comment]
{"ok":true,"result":{"id":...,"first_name":"...","username":"..._bot"}}

every things work fine but when many requests come to python we catch these error

**Comment by nickoala** [comment]
Ok, it seems like your network is not blocking access to `api.telegram.org`. You said the `SSLError` only occurs when the program is handling many requests, if I understand correctly.

...... I really have no clue ....... what do you think?
