### ISSUE TITLE
Except error

### ISSUE THREAD

**Issue by suibaf** [nickoala/telepot#127]
Hi,
I wrote a little bot with telepot. I need to manage the errors especially BotWasBlockedError. Since I'm not expert of python I have some problem. With the following code, python  answer me with error "except BotWasBlockedError as e" syntax error. Can you help me please?
BR
Fabio

`while 1:

    dataora = str(datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')[:-7]) # leggiamo la data e ora attuale

    class BotWasBlockedError(telepot.exception.TelegramError):
        DESCRIPTION_PATTERNS = ['bot.*kicked']

    try:
        if valori_letti[0] == 1: # Dall'ultima lettura risulta che il gruppo è in marcia               
            if stato_gruppo == "Gruppo elettrogeno fermo": #se nel ciclo precedente il gruppo era fermo ed ora invece è in marcia
                bot.sendMessage(7970492, "Il Gruppo elettrogeno è appena andato in marcia " + dataora)
                bot.sendMessage(144183687, "Il Gruppo elettrogeno è appena andato in marcia " + dataora)          
            stato_gruppo = "Gruppo elettrogeno in moto" #Aggiorniamo lo stato del gruppo
        else:
            if stato_gruppo == "Gruppo elettrogeno in moto": #se nel ciclo precedente il gruppo era in MARCIA ed ora invece è fermo
                bot.sendMessage(7970492, "Il Gruppo elettrogeno si è appena fermato "+ dataora)
                bot.sendMessage(144183687, "Il Gruppo elettrogeno si è appena fermato " + dataora) 
            stato_gruppo = "Gruppo elettrogeno fermo" #Aggiorniamo lo stato del gruppo         
    except BotWasBlockedError as e
        print e`

**Comment by zumoshi** [comment]
hello,
you seem to be missing a colon (:) at the end of that line. you can read more on python's error handling at https://docs.python.org/3/tutorial/errors.html .

**Comment by suibaf** [comment]
Hi Zumushi,
thank you for your answer. Yes you are right semicolon (:) it's necessary. But no working. If a BotWasblockedError is rised, the propram is closed.

**Comment by zumoshi** [comment]
you don't have to create a `BotWasBlockedError` class yourself. telepot already has one.
also i don't quite understand what you are trying to achieve with your code, does it continuously send the same message until the user blocks the bot ?

try the following code:
```python
import sys
import telepot

TOKEN = sys.argv[1]  # get token from command-line

bot = telepot.Bot(TOKEN)
try:
    bot.sendMessage(7970492,"test")
    print("message sent")
except telepot.exception.BotWasBlockedError:
    print("user blocked the bot")
```

it tries to send a message to the user id specified, and prints the result (message was sent or bot was blocked).

**Comment by suibaf** [comment]
Thank you Zumoshi,
`does it continuously send the same message until the user blocks the bot ?`
No of course I send you a piece of code. OK now it work fine.
Can I know the name of the user that blocked the bot?
BR

**Comment by zumoshi** [comment]
telepot does not include name of the user in the exception. however, the exception is raised after calling the `sendMessage` method, so you already have the user id. you need to store the user's name when they first message the bot and retrieve the name from there using the user's id when you need it.

**Comment by suibaf** [comment]
If I understand, using user id I can know the name of the user. Thank you very much

**Comment by zumoshi** [comment]
there is no method to specifically tell you the user's name from his id. but when you get a message from the user, his name and id will be sent to your bot. you can then store these in a database and look up user's information based on his id.
