### ISSUE TITLE
Restart bot with new token

### ISSUE THREAD

**Issue by beta48** [nickoala/telepot#128]
Hi,

I am using `bot.message_loop(handle)` acc. to the tutorial to listen for new messages. I would like to allow users to import a new telegram token from a config file, close the running message_loop thread and restart bot with the new token. Is there something like 'bot.stop_loop'?

**Comment by nickoala** [comment]
Telepot is not designed for changing token dynamically. Once a bot is created with a token, it is never meant to be changed. What you want to do, I guess you can only achieve with a "controller" program outside of telepot - for example, a shell script which updates the config file, stops the bot program, and re-starts it.

**Comment by zumoshi** [comment]
it could be useful though. it should not be very hard to implant if the thread is in daemon mode. you just have to store a reference to it and stop it, then make sure the handler class can be garbage collected.

unless there is a specific problem that i am not aware of.

**Comment by beta48** [comment]
I am currently stopping and restarting the complete script. That works fine. I was just wondering if there is a more elegant solution.
