### ISSUE TITLE
Inline query not executing always

### ISSUE THREAD

**Issue by krso92** [nickoala/telepot#131]
The thing is:
I mention my bot like '@mybot' and 'inline_query' is executing.
Depending of the text that goes after bot name, bot ether return random number or return one of items between ' or ' substring.

Here is code related to this situation:

```python
OR = ' or '
def on_message(self, msg):
     if flavor == 'inline_query':
            query_id, from_id, query_string = telepot.glance(msg, flavor='inline_query')
            choices = query_string.lower().split(OR)
            print 'INLINE!!!!!'
            if choices and len(choices) > 1:
                response = [(InlineQueryResultArticle(
                    id='dice_or',
                    title='Quick decide!',
                    input_message_content=InputTextMessageContent(
                        message_text=choices[random.randint(0, len(choices))]
                    )
                )
                )]
            else:
                # random dice
                print 'dice inline'
                response = [InlineQueryResultArticle(
                    id='dice_rnd',
                    title='Dice!',
                    input_message_content=InputTextMessageContent(
                        message_text=str(self.random_dice())
                    )
                )]
            self.bot.answerInlineQuery(query_id, response)
```

function `self.random_dice()` returns number between 1 and 6.

I noticed that I am always getting same random number, and that I get one of real choices that I type. EXAMPLE: '@mybot sub or string or substring' always returns one of mentioned substring between or-s.

What is happening is that when call inline query for bot the first time - the code is executed and random number is returned (I see `print 'INLINE!!!!!'` is printed in console), every other time it returns me that same number and it do not execute this code. (I do not see `print 'INLINE!!!!!'` is printed in console). I restart my bot and call inline query again and code does not get run and give me same number.

After some time (minutes <= 5) I noticed loop: On inline query call code is run once and get new number, every next time returns same number without executing code.

I think it have something to do with that i use variable `choices` in working part which uses input to generate output, and other part (else) is independent of input. But returns random.

Who is caching this? Telegram or telepot? Can you help me bypass this?

Thanks
Love telepot!

**Comment by zumoshi** [comment]
Hello,
telegram caches all inline query responses for up to 5 minutes by default. this is because most of the bots search in some website and content is unlikely to change however caching could save lots of bandwidth on multiple users requesting the same queries.

but this behavior is overwritable, from https://core.telegram.org/bots/api#answerinlinequery : 
> cache_time = The maximum amount of time in seconds that the result of the inline query may be cached on the server. Defaults to 300.

telepot's API also implants this parameter for `answerInlineQuery` method. see [here](http://telepot.readthedocs.io/en/latest/reference.html#telepot.Bot.answerInlineQuery).

you may also increase the cache duration for bots with deterministic results, e.g. calculators. 2+2 is always going to be 4...

**Comment by krso92** [comment]
Many thanks! This makes things clear, I was totally confused.
Cheers!

**Comment by krso92** [comment]
I am actually not sure how to set cache_time for my bot can you please help me?
My bot extends class telepot.helper.UserHandler

**Comment by zumoshi** [comment]
cache time is not set per-bot. it's set for each inline query response separately, just add the parameter `cache_time` to your call to `answerInlineQuery`.

example (from your code in first post):
```python
self.bot.answerInlineQuery(query_id, response, cache_time=0)
```

**Comment by krso92** [comment]
I totally overlooked that line... I get it, it works, thanks again :)
