### ISSUE TITLE
Can't edit inline button?

### ISSUE THREAD

**Issue by CrispyBacon1999** [nickoala/telepot#132]
I'm trying to edit an inline keyboard button, but telepot won't return a proper inline message id to pass into the editMessageReplyMarkup() function.

My code is located at https://ide.c9.io/crispybacon1999/admin-bot in the admin.py file. I'm not sure if it's a problem with telepot, or if I'm just completely misunderstanding the documentation, but some help would be great either way!

**Comment by zumoshi** [comment]
Hello, 
see issue #73 .
`inline_message_id` is only used to edit messages sent via inline query response and the bot does not have access to their chat id and message id.
