### ISSUE TITLE
How make telepot faster in python 2

### ISSUE THREAD

**Issue by efazati** [nickoala/telepot#134]
I have application with python 2 over 100 req per sec. every hour my app freeze a and need restart supervisor to work faster
I have about 4 sec  to 25 sec delay for every msg

how can make it faster?

I change sleep but nothing good happen!

```
# Keep the program running.
while 1:
    time.sleep(0.1)
```

**Comment by nickoala** [comment]
Honestly, not being able to test telepot in such a heavy load, I cannot offer any useful suggestions.

Are you using a single `handle()` function to handle messages? If so, you are processing messages *sequentially*. Any blocking in the `handle()` function would delay handling of the next message. The delay will get longer and longer as messages accumulate.

If you are using the delegation mechanism, that means 100 threads may get spawned in a second. Is your machine powerful enough for that?

**Comment by efazati** [comment]
I use single handle

```
bot.message_loop({'chat': on_chat_message,
                  'callback_query': on_callback_query}, 0.05)
print 'Listening ...'

# Keep the program running.
while 1:
    time.sleep(0.1)
```
how can have delegation mechanism?

**Comment by efazati** [comment]
I used this and everythings goes perfect

http://telepot.readthedocs.io/en/latest/#maintain-threads-of-conversation

**Comment by nickoala** [comment]
Cool. That's easy to fix.

**Comment by efazati** [comment]
I have problem again :( 
after timeout, InlineKeyboardMarkup expired. how this happend?
after click, nothing comes to server

**Comment by similato** [comment]
Hi could explain what you should do

**Comment by efazati** [comment]
my code:


```
bot = telepot.DelegatorBot(TOKEN, [
    (per_chat_id(), create_open(MessageCounter, timeout=10)),
])

bot.message_loop(run_forever='Listening ...')

```

I was create link like this
```
message_with_inline_keyboard = self.sender.sendMessage(InlineKeyboardMarkup(inline_keyboard=[[dict(text='profile', callback_data='/profile_%s' % user['_id'])]]))

```

everything works fine till this printed in my terminal

> ERROR:root:on_close() called due to WaitTooLong: 

seems link expired. `on_callback_query` receive nothing

**Comment by similato** [comment]
I did not catch

**Comment by efazati** [comment]
after timeout, profile link not worked
I was created with InlineKeyboardMarkup

**Comment by efazati** [comment]
![image](https://cloud.githubusercontent.com/assets/1132647/17942347/32f811e8-6a4c-11e6-9c17-6f96412d7a88.png)

this happend and nothing sended to my server

**Comment by efazati** [comment]
I think per_chat_id() not return on_callback_query.

**Comment by efazati** [comment]
with this status everythings worked
but i think thats weird 

```
bot = telepot.DelegatorBot(TOKEN, [
    (per_message(), create_open(MessageCounter, timeout=0.1)),
])
```

**Comment by efazati** [comment]
after update crashed after 3 hours :/

@nickoala what you think about this?

**Comment by nickoala** [comment]
Well, just telling me "Crashed" does not really help me solve your problem.

The thing you said about inline keyboard not responding after timeout, it's a known problem in 8.3. I have fixed it in today's newest release, 9.0. But I have not time to update the docs. The only place you can see how it works is in the [examples](https://github.com/nickoala/telepot/tree/master/examples/callback).

You also mentioned that `timeout=0.1` seemed to fix the problem. That is extremely improbable. `timeout` is not meant to be used that way.

I suggest you try the following *after* updating to 9.0. Note that I changed `MessageCounter` to extend from `ChatHandler` (instead of `UserHandler` in your code):

```python
from telepot.delegate import (
    pave_event_space, per_chat_id, per_callback_query_chat_id, create_open)

class MessageCounter(telepot.helper.ChatHandler):
   ......

bot = telepot.DelegatorBot(TOKEN, [
    pave_event_space()(
        [per_chat_id(), per_callback_query_chat_id()],
        create_open, MessageCounter, timeout=10, include_callback_query=True),
])
```

1. `per_callback_query_chat_id()` allows the inline keyboard's callback query to resurrect the same delegate, even *after* it times out.

2. `include_callback_query=True` tells `MessageCounter` to capture inline query belonging to the same chat, during its lifetime.

Good luck.

**Comment by efazati** [comment]
Thanks, everything work fine

**Comment by nickoala** [comment]
I have made it even more convenient today (with version 9.1). Just do this:

```python
from telepot.delegate import (
    per_chat_id, create_open, pave_event_space, include_callback_query_chat_id)

bot = telepot.DelegatorBot(TOKEN, [
    include_callback_query_chat_id(
        pave_event_space())(
            per_chat_id(), create_open, MessageCounter, timeout=10),
])
```

It's equivalent to what I suggested before, but the extra mundane stuff is encapsulated by `include_callback_query_chat_id`, so you don't have to worry about them.
