### ISSUE TITLE
Diceyclock - check if text is sent

### ISSUE THREAD

**Issue by drewreece** [nickoala/telepot#138]
Since diceyclock is the example for new users you may want to add a check for text to avoid throwing errors when other content types are sent. 

I realise that point is covered in later examples but new users may not get that far.

**Comment by nickoala** [comment]
Thanks for the suggestion. But the reason I did not add the check is I don't want to make the code more complicated than it needs to be. I want to keep it minimal for absolute beginners. If they somehow decide to send it photos, then they are not using the bot as intended, and they should bare the responsibility to find out why the program is broken, and hopefully learn some more in the process.

**Comment by drewreece** [comment]
Fair enough, I just figured Telegram made it easy to send locations, images, sounds etc.
