### ISSUE TITLE
How to mute Telepot logs?

### ISSUE THREAD

**Issue by oc2pcoj** [nickoala/telepot#139]
```
2016-08-28 09:39:23,294 on_close() called due to WaitTooLong:
2016-08-28 09:39:23,329 "POST /bot216467218:AAEWaqe7hrXSEnMefNjZpwY9YxEvgCEMVkY/getUpdates HTTP/1.1" 200 23
2016-08-28 09:39:23,432 Starting new HTTPS connection (1): api.telegram.org
```
It is very excess logging. Can I stop it or redirect to another log file?

**Comment by nickoala** [comment]
You can override `on_close()`, can't you?

Because a delegate will close on *any* exceptions or errors, I think it is prudent to print them out and not swallow them, in case of an error you do not expect. If you don't like to see some of them, just override `on_close()` to not print them. Be careful that, if you cast too wide a net, you may mute a genuine error, a delegate dead without any trace.

**Comment by nickoala** [comment]
Sorry, I made a somewhat rushed comment. To make the situation clear, here's the relevant segment of telepot code:

```python
try:
    # message loop ....

# These exceptions are "normal" exits.
except (exception.IdleTerminate, exception.StopListening) as e:
    j.on_close(e)

# Any other exceptions are accidents. **Print it out.**
# This is to prevent swallowing exceptions in the case that on_close()
# gets overridden but fails to account for unexpected exceptions.
except Exception as e:
    traceback.print_exc()
    j.on_close(e)
```

Those comments are straight from the repository - I have made an explicit decision to print out the stacktrace of any "abnormal" exits, no matter how you override `on_close()`.

So, sorry, you cannot eliminate the stacktrace by overriding `on_close()`. The only solution, if you hate seeing so much logging, would be to either redirect the logging to another file (an O/S or process manager function), or to modify the source code yourself.

**Comment by oc2pcoj** [comment]
> The only solution, if you hate seeing so much logging, would be to either redirect the logging to another file (an O/S or process manager function), or to modify the source code yourself.

Is it possible to redirect logging to another file only for Telepot? 

`import logging
log_name = 'log_sends_notifications'
logging.basicConfig(filename=log_name,level=logging.DEBUG, format='%(asctime)s %(message)s')`

It works for my code and for Telepot too.

**Comment by nickoala** [comment]
Cool, if that works for you. Obviously, I overlooked that config functionality of the logging module.

**Comment by jcvo90** [comment]
hi apology, could you give an example of code? 
I do not know where to insert those lines
"import logging log_name = 'log_sends_notifications' logging.basicConfig(filename=log_name,level=logging.DEBUG, format='%(asctime)s %(message)s')"
, thanks

**Comment by das7pad** [comment]
@jcvo90 Logging may be configured at the very beginning. Assume you start your bot via `python entrypoint.py` then these lines go into `entrypoint.py`. Here is an [example](https://gist.github.com/das7pad/a1d6607e3614fca7d1e61e525f30fca6#file-telepot_aio-py).

**Comment by jcvo90** [comment]
@das7pad thank you very much, I will implement your solution now
