### ISSUE TITLE
Inline Query

### ISSUE THREAD

**Issue by eren-kemer** [nickoala/telepot#14]
Hey there, 
first of all, great work you did there, thanks for the API!
I've been trying to send messages to the bot using inline query, with your API but had to find out it doesn't seem to be supported. Here's what i get when receiving an inline query with notifyOnMessage:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 379, in handle
    callback(update['message'])
KeyError: 'message'
```

This is what i'm trying right now:

```
import time
import pprint
import telepot
from pprint import pprint
bot = telepot.Bot('MY_KEY')

def handle(msg):
       messageObject = msg
       pprint(messageObject)  # to test if it sends me any kind of object.
       if messageObject['chat']['type'] == 'group':    # making sure it is a group
               chat_id = messageObject['chat']['id']    # putting needed info in vars for easier usage
               name = messageObject['chat']['username']
               message = messageObject['text']
               print(chat_id)    # just some prints to check what the program is receiving
               print(name)
               print(message)

               bot.sendMessage(chat_id, 'Hello @' + name + ', ' + message)    # send a msg to the Chat



bot.notifyOnMessage(handle)
print 'Listening ...'
# Keep the program running.
while 1:
    time.sleep(10)


```
It actually works when sending the complete message, but i wanna work with inline queries.^^
I'm pretty new to python so please bear with me if i'm just being stupid or something.
Is there any way i can deal with this issue?

**Comment by nickoala** [comment]
Right, telepot does not support inline query yet. I am working on it, and hopefully an update will be coming out soon. Can't promise when, but I will try to get it out as soon as I can.

**Comment by nickoala** [comment]
Hello, for everyone who are following, a new version of telepot has just come out. It now supports **inline query**. But I need some more time to complete the documentations. See changelog for a list of modifications.
