### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by floidn** [nickoala/telepot#142]
Hi,
I made a very basic bot on my Ubuntu system, it is not really written in an elegant way but it works and does the things I want it to do. Unfortunately the bot have to run on a Windows machine and I get an error message I cannot get rid of. 

> Traceback (most recent call last):
>   File "C:\Users\Pietro\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telepot\__init__.py", line 738, in collector
>     callback(item)
>   File "C:\Users\Pietro\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telepot\__init__.py", line 961, in handle
>     d = make_delegate((self, msg, id))
>   File "C:\Users\Pietro\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telepot\delegate.py", line 244, in f
>     j = cls(seed_tuple, *args, **kwargs)
>   File "E:\XWingPairbot.py", line 40, in __init__
>     super(PersonalAssistant, self).__init__(seed_tuple, timeout)
>   File "C:\Users\Pietro\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telepot\helper.py", line 894, in __init__
>     super(ChatHandler, self).__init__(bot, seed, **kwargs)
>   File "C:\Users\Pietro\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telepot\helper.py", line 660, in __init__
>     super(ChatContext, self).__init__(bot, context_id, *args, **kwargs)
>   File "C:\Users\Pietro\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telepot\helper.py", line 638, in __init__
>     super(ListenerContext, self).__init__(*args, **kwargs)
>   File "C:\Users\Pietro\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telepot\helper.py", line 852, in __init__
>     super(DefaultRouterMixin, self).__init__(*args, **kwargs)
> TypeError: __init__() missing 1 required positional argument: 'event_space` 

Any hint of what's going on?

**Comment by nickoala** [comment]
Documentations are not up-to-date. Basically, there are some parameters which are not mentioned in the docs, but are necessary in the latest version. Can you show me the relevant section of your code:

```python
bot = telepot.DelegatorBot([
    # WHAT DO YOU PUT HERE?????
])
```
I will tell you the necessary change.

**Comment by floidn** [comment]
I started from an example

> bot = telepot.DelegatorBot(TTOKEN, [(per_chat_id(), create_open(PersonalAssistant, timeout=60)),])
> bot.message_loop(run_forever='Listening ...')

**Comment by nickoala** [comment]
In the newest version, you should do this:

```python
from telepot.delegate import per_chat_id, create_open, pave_event_space

bot = telepot.DelegatorBot(TOKEN, [
    pave_event_space()(
        per_chat_id(), create_open, PersonalAssistant, timeout=60),
])
```

**Comment by floidn** [comment]
Thank you very much for your help nickoala but I still got an error

> Traceback (most recent call last):
>   File "C:\Users\Pietro\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telepot\__init__.py", line 738, in collector
>     callback(item)
>   File "C:\Users\Pietro\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telepot\__init__.py", line 961, in handle
>     d = make_delegate((self, msg, id))
>   File "C:\Users\Pietro\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telepot\delegate.py", line 244, in f
>     j = cls(seed_tuple, *args, **kwargs)
> TypeError: __init__() got an unexpected keyword argument 'event_space'

**Comment by nickoala** [comment]
What is your handler class definition?

```python
class YourHandler(telepot.helper.ChatHandler):
    def __init__(self, ?????):
        super(YourHandler, self).__init__(.....)
```

**Comment by floidn** [comment]
this one?

> class PersonalAssistant(telepot.helper.ChatHandler):
>     def __init__(self, seed_tuple, timeout):
>         super(PersonalAssistant, self).__init__(seed_tuple, timeout)

**Comment by nickoala** [comment]
Try changing it to:

```python
class PersonalAssistant(telepot.helper.ChatHandler):
    def __init__(self, *args, **kwargs):
        super(PersonalAssistant, self).__init__(*args, **kwargs)
```

**Comment by floidn** [comment]
Nope, still the same error. Is there a working example with the last version of telebot? If yes I can try to rewrite my bot starting from that!

**Comment by nickoala** [comment]
Well, I just updated the **[tutorial](http://telepot.readthedocs.io/en/latest/)**. Those examples should work.

**Comment by nickoala** [comment]
And please make sure you are using 9.1

**Comment by floidn** [comment]
Works like a charm. Thank you!
