### ISSUE TITLE
Multi-language bot

### ISSUE THREAD

**Issue by ersiko** [nickoala/telepot#144]
Hi Nick! 

I'm trying to make my bot a multi-language one.
So far, if I add the gettext install to `__init__`, it works, but all messages come in the same language:
```
import os
import locale
(...)
localedir = os.path.join(os.path.abspath(os.path.dirname(__file__)), 'lang')
esp = gettext.translation('int.py', localedir, languages=['es'])
eng = gettext.translation('int.py', localedir, languages=['en'])
(...)
class MyBot(telepot.helper.ChatHandler):
    def __init__(self, *args, **kwargs):
        super(MyBot, self).__init__(*args, **kwargs)
        eng.install()
(...)
bot = telepot.DelegatorBot(BOT_TOKEN, [
    include_callback_query_chat_id(
        pave_event_space())(
            per_chat_id(), create_open, MyBot, timeout=15
    ),
])

```

I'd like to choose a language based on the user preferences. To make it simple (for now), if the user id is 1111111, then spanish, else english.

Of course, when `__init__` is called I don't have the message, so I can't know the user id to make the language decision. But if I call "install()" in "on_message" function, I'll be calling "install()" way more than I need. Optimally I'd like to call "install()" once per Delegator session.

Is there a place where I can call gettext install() only once per session?

Sorry if I wasn't completely clear... If I wasn't, I'll try to elaborate.

Thanks in advance for your attention, and of course thank you very much for this very useful framework!

**Comment by nickoala** [comment]
Actually, you DO get the initial message in `__init__()`. The first argument is what I call a *seed tuple*, which is just `(bot, initial_msg, seed)`. You can get a hold of it by declaring it explicitly:

```python
class MyBot(telepot.helper.ChatHandler):
    def __init__(self, seed_tuple, *args, **kwargs):
        super(MyBot, self).__init__(seed_tuple, *args, **kwargs)
        bot, initial_msg, seed = seed_tuple
```

However, even if you know the user id and set the language in `__init__()`, you are still installing the language over and over. Here is why. After 15 seconds of user inactivity (`timeout=15`), the `MyBot` instance will expire. Next time that user makes contact again, a new `MyBot` instance will be created. So, you are installing language for him again.

What you need is to remember who already have language installed and who has not. And that storage has to be persistent across many lifetime of `MyBot`. In the simplest case, it can be just a dict. Otherwise, it can be in a database. Point is, you have to program that yourself. Telepot does not do that for you.

**Comment by ersiko** [comment]
Thanks! Reading the documentation I saw the message should be available, in the tuple, but it wasn't used in any example used it, and I didn't know I had to declare it explicitly. That explains it, thanks a lot.

About your suggestion, I can store user lang preferences in a dict or database, but those preferences must be applied for every DelegatorBot spawned, right?
If I understood correctly, each MyBot created by DelegatorBot would be closed after the timeout, and all the resources would be "cleaned", losing the language "install", and there's no way to persist that. 
Because the next time the same user talks to the bot, a new MyBot would be created, with no language preferences, and I'll still need to query the database (or dict, or whatever it is) for the languange preference, and then perform the proper language install(). I see no way around that (buy I may be wrong).  Does this make sense? Is that why you're saying telepot can't do it in other way?

It's not optimal, but the worst case scenario is an install() call for every user every 15 seconds. And if I set a "default" language, most of the users won't need the install() part. I hope I can live with that!

**Comment by ersiko** [comment]
Ok, "install()" was not the way to go, as it affects the whole thread. But I can set the gettext call as a new attribute to "MyBot" object, and it works!

```
import gettext
import os
import locale
(...)
localedir = os.path.join(os.path.abspath(os.path.dirname(__file__)), 'lang')
esp = gettext.translation('int.py', localedir, languages=['es'])
eng = gettext.translation('int.py', localedir, languages=['en'])
(...)
class MyBot(telepot.helper.ChatHandler):
    def __init__(self, seed_tuple, *args, **kwargs):
        super(MyBot, self).__init__(seed_tuple,*args, **kwargs)
        bot, msg, seed = seed_tuple
        #print(msg['from']['id'])
        if msg['from']['id'] == 11111111:
            self.text = eng.gettext
        else:
            self.text = esp.gettext
(...)
    def on_chat_message(self, msg):
            if msg['text'] == '/test':
                self.sender.sendMessage(self.text('hello world'))
```
And that would print two different messages for users on each language. I'm thinking maybe I could even modify sender.sendMessage to support this... but if it works this way, I'll keep going and maybe work on that later :)

I'll leave this issue open for a day in case you want to add some comments to it, then close it. Thanks a lot for your help and for telepot :)

**Comment by ersiko** [comment]
Just to follow python common usage, and to make strings available to "pybabel extract", I changed the name from "self.text" to "self._". It's not the best way yet, but apparently it works :+1:
