### ISSUE TITLE
editMessageText

### ISSUE THREAD

**Issue by Alenichel** [nickoala/telepot#145]
Hi
I have some problem with telepot.Bot.editMessageText.

the output is:
> telepot.exception.TelegramError: ("Bad Request: Message can't be edited", 400, {'ok': False, 'error_code': 400, 'description': "Bad Request: Message can't be edited"})

I can't find any clue about the source of the problem despite I'm following the Telepot reference: I'm passing to the function the _msg_identifier_ argument (gained with telepot.message_identifier() ) and the new text message. I haven't neither added the Reply_Markup.

Am I doing wrong ?

**Comment by nickoala** [comment]
```python
>>> import telepot
>>> bot = telepot.Bot('TOKEN')
>>> sent = bot.sendMessage(99999999, 'Hello')
>>> edited = bot.editMessageText(telepot.message_identifier(sent), 'How are you?')
```
These work fine for me, both in Python 2.7 and 3.5.

If you need further help, you should try to distill your situation down to the simplest case. That is, you should try to reproduce your problem in as little code as possible. That will help me help you.
