### ISSUE TITLE
Can't send local image as response to inline query

### ISSUE THREAD

**Issue by Noammac** [nickoala/telepot#146]
I have a `.jpg` file in the same directory as the bot script that I want to send as a response to a certain inline query, this is my code:
```python
        articles = [InlineQueryResultArticle(
                        id='abc',
                        title='ABC',
                        input_message_content=InputTextMessageContent(
                            message_text='Hello'
                        )
                   ),
                    InlineQueryResultPhoto(
                        id='def',
                        title='def',
                        photo_url="toast.jpg",
                        thumb_url="someonlineimageiused",
                    )]
```
But when I try to inoke an inline query it gives me the following error: 
```
telepot.exception.TelegramError: ('Bad Request: CONTENT_URL_INVALID', 400, {'error_code': 400, 'description': 'Bad Request: CONTENT_URL_INVALID', 'ok': False})
```

I got as well `INVALID_THUMB_URL` when I tried to use `toast.jpg` as the thumbnail.
Is there any solution or do I need to upload the picture?

**Comment by nickoala** [comment]
`InlineQueryResultPhoto` only accept URLs. 

`InlineQueryResultCachedPhoto` accpets a `photo_file_id`, which refers to a photo stored on the Telegram servers, which was presumably sent at an earlier time.

I don't see any way you can "embed" an image file within the inline query result. I can understand it though. Imagine someone embeds 50 image files in one result. That means, along with that result, 50 image files will be uploaded. I can understand why Telegram doesn't want that to happen.

**Comment by Noammac** [comment]
Another question I have is if there's a way to send a `BytesIO` object as an image (`bot.sendMessage` method)

**Comment by nickoala** [comment]
I assume you mean `bot.sendPhoto()`.

If you pass in a non-string, it will call the object's `read()` method to obtain the bytes. So, I think a `BytesIO` will work, although I have not tried it. I have only tried a file object.

Additionally, you should also pass in the filename, because the filename cannot be guessed from a `BytesIO`:

```python
bot.sendPhoto(chat_id, open('x.jpg'))  # this should work
bot.sendPhoto(chat_id, ('x.jpg', open('x.jpg')))  # this should work too
bot.sendPhoto(chat_id, ('x.jpg', bytesio))  # this should also work, but I have never tried it
```

**Comment by Noammac** [comment]
I tried it with `bot.sendPhoto(chat_id, 'toast.jpg', bytearr)`, but I got the following error:
```TypeError: a bytes-like object is required, not '_io.BytesIO'```
