### ISSUE TITLE
v9.1 BadHTTPResponse on everything (even simple examples)

### ISSUE THREAD

**Issue by SaschaMann** [nickoala/telepot#147]
The recent update to v9.1 appears to have broken something. I'm not sure what the exact issue is but even
```python
bot = telepot.Bot('token')
bot.getMe()
```
throws a BadHTTPResponse exception:
```
Traceback (most recent call last):
  File "[...]\env\[...]\lib\site-packages\telepot\api.py", line 110, in _parse
    data = json.loads(text)
  File "[...]\env\[...]\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "[...]\env\[...]\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "[...]\env\[...]\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[...]\env\[...]\lib\site-packages\telepot\__init__.py", line 402, in getMe
    return self._api_request('getMe')
  File "[...]\env\[...]\lib\site-packages\telepot\__init__.py", line 398, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "[...]\env\[...]\lib\site-packages\telepot\api.py", line 131, in request
    return _parse(r)
  File "[...]\env\[...]\lib\site-packages\telepot\api.py", line 112, in _parse
    raise exception.BadHTTPResponse(response.status, text, response)
telepot.exception.BadHTTPResponse: <exception str() failed>
```

Using pip to go back to v9.0 "fixed" that problem, it works using that version.
I got similar error messages with a previously working full bot, so it's not just getMe().

**Comment by nickoala** [comment]
:no_mouth: 

Well, I really have no clue ......

The *only* differences between 9.0 and 9.1 are:

- one function got renamed
- one function was added

Both are in module `telepot.delegate`, which don't get used by such a simple call as `getMe()`.

So .... I really have no answer :no_mouth:

**Comment by gaste11o** [comment]
I have such exception too.

**Comment by SaschaMann** [comment]
I created a new virtualenv with just telepot 9.1 and requirements installed, same issue.

I looked at the changes between 9.0 and 9.1 and really can't find anything that could cause it.

**Comment by nickoala** [comment]
To both @gaste11o and @SaschaMann, are you sure this problem did *not* creep up in 9.0?

There were big changes between 9.0 and previous version. It would be more believable if such a problem creep up in 9.0.

For me, both 9.0 and 9.1 work fine. So, I still have no clue :no_mouth:

**Comment by SaschaMann** [comment]
Yes, when I reverted back to 9.0 it worked fine. 9.0 was also the first version of telepot I even used.

I tried it again with 9.1 using the testenv created earlier and now it worked. Without me changing anything whatsoever, didn't even touch it inbetween. Perhaps this was some issue on Telegram's side, sending wrong data?

I really have no clue but it seems to have fixed itself. 😕 
Really strange problem.

@gaste11o does it work for you again, too?

**Comment by gaste11o** [comment]
Last few hours I don't seen this error

**Comment by SaschaMann** [comment]
Guess this can be closed then. Weird stuff.

**Comment by nickoala** [comment]
I did have the experience that Telegram servers went down for a few hours, the result of which, of course, was what you saw. Just forgot to mention this possibility. Now that everything works, we can spend time on more meaningful stuff.
