### ISSUE TITLE
What happens with Heroku and multiple instances?

### ISSUE THREAD

**Issue by garciaw** [nickoala/telepot#148]
Hi, I read that when you run code in Heroku, it can go to any number of machines and have multiple instances of the code on different machines serving different users. What happens with webhooks then? I'm just a hobby developer, so I don't really know much about webhooks and connections... But wouldn't there be errors like when I try to run 2 local instances of telepot? Or if it doesn't raises errors, how could that affect speed of receiving / sending messages?

PS: my code has

    bot.setWebhook() # unset if was set previously
    bot.setWebhook(URL + SECRET)

And I think that should take care of things, but if feels like there would still be a "tug of war" where each instance is trying to get its webhook back every second

**Comment by nickoala** [comment]
Do you mean: what if you run two programs at the same time, *with the same token*, both trying to set webhook?

**Comment by garciaw** [comment]
Yes, I already made the mistake of forgetting I had a terminal window running the bot (in long-polling mode) and running the same code on another window, but I didn't know what could happen if I was using webhooks... My original question was referring to the answer to [this stackoverflow question](http://stackoverflow.com/questions/20737606/are-heroku-instances-persistent-or-can-i-use-dict-array-as-a-cache), where you deploy your code only once, but it can end up in a number of different machines, so they obviously would have the same token.

But upon more reading and better understanding the linked answer, I guess the simplest solution is just to have the bot running on single Dyno. I thought Heroku users with a free plan could still have their code running on multiple instances, thus creating a "double webhook" conflict.

**Comment by nickoala** [comment]
I have not used Heroku, so cannot give any informed advice there.

From the perspective of telepot and Telegram Bot API, I can only say that there should not be two programs with the same token doing `getUpdates` or `setWebhook` at the same time.

**Comment by garciaw** [comment]
Thanks for clarifying, you can close this issue.
My doubt was mostly due to my misunderstanding of how Heroku and webhooks work. If you set it up so that just one Dyno (one Heroku machine) is running the bot, it should be fine.

**Comment by arthurtyukayev** [comment]
I run my bots from Heroku. As long as your bind the required $PORT you're able to launch your bot as a worker in the Procfile. However, if you would like to scale the bot you should run your bot with webhooks.
