### ISSUE TITLE
Can't send msg, There is no error

### ISSUE THREAD

**Issue by efazati** [nickoala/telepot#149]
I have users list msg, and every user has name.
sometimes there is characters and telepot can't send msg. also there is no errors

i was replace strings and every things worked
but there is new chars and i can't catch the problem
is there any way to solve this?
```
def remove_bad_char(name):
    name = name.replace('�', '')
    name = name.replace('/', '')
    name = name.replace('@', '')
    name = name.replace('?', '')
    name = name.replace(':', '')
    name = name.replace('\n', '')
    name = name.replace('\\', '')
    name = name.replace('ـ', '')
    name = name.replace('-', '')
    name = name.replace('.', '')
    name = name.replace('', '')
    return name
```

**Comment by efazati** [comment]
updated this function and everythigns worked. is there any list of chars?

```

def remove_bad_char(name):
    name = name.replace('ई', '')
    name = name.replace('ह', '')
    name = name.replace('═', '')
    name = name.replace('°', '')
    name = name.replace('⇣', '')
    name = name.replace('↶', '')
    name = name.replace('/', '')
    name = name.replace('@', '')
    name = name.replace('?', '')
    name = name.replace(':', '')
    name = name.replace('\n', '')
    name = name.replace('\\', '')
    name = name.replace('ـ', '')
    name = name.replace('-', '')
    name = name.replace('.', '')
    name = name.replace('', '')
    return name

```

**Comment by nickoala** [comment]
First, I don't understand your question.

Second, are you using Python 3?

**Comment by efazati** [comment]
no i user python 2.7

when msg has character like 'ई', msg can't deliver ... without any error

**Comment by nickoala** [comment]
I am wondering, if you are using Python 2.7, should you put a `u` in front of unicode strings, e.g. `u'ई'`, to make sure it's unicode? Not sure it can fix your issue. Just wondering.

**Comment by efazati** [comment]
received text is utf-8 .... no need no u

**Comment by zumoshi** [comment]
![image](https://cloud.githubusercontent.com/assets/4184939/18249755/726350f2-7395-11e6-8d60-cbfc581ab7b2.png)
i didn't have any problem sending these characters in python 3 using this code:
```python
import telepot
bot = telepot.Bot("xxx")
bot.sendMessage(xxx,"ईह═°⇣↶/@?:\n\\ـ-.")
```

i suspect your problem is with utf-8 handling, not these specific characters.
if you want to limit the names to ascii chars you can use the following code:
```python
import re
def remove_nonalphanumeric(name):
    return re.sub('[\W_]+', '', name)
```

but i suggest that you upgrade to python 3, it has a much better utf-8 handling.

**Comment by efazati** [comment]
no this can't help, many ascii chars worked but some chars not work!
maybe upgarde to python 3 is better way
