### ISSUE TITLE
TelegramError: (u'[Error]: Conflict: terminated by other long poll or webhook', 409)

### ISSUE THREAD

**Issue by gustavotpd** [nickoala/telepot#15]
I've created a shell script that starts on login on raspberry pi, this script listen for a telegram bot command /photo. I noticed that script stops and command has not response. Occours this error TelegramError: (u'[Error]: Conflict: terminated by other long poll or webhook', 409). Does anyone have experienced this issue? Thanks in advance.

**Comment by nickoala** [comment]
It is because you have set a webhook, or have another thread/script calling `getUpdates()` at the same time. Telegram does not allow updates to be obtained in multiple "ways".

First, make sure you don't have another program calling `getUpdates()` or `notifyOnMessage()` on the same bot.

Second, enter Python interpreter, unset webhook:

```
import telepot
bot = telepot.Bot('TOKEN')
bot.setWebhook()  # unset webhook by supplying no parameter
```

If they don't solve your problem, re-check and repeat until you solve the problem.

**Comment by gustavotpd** [comment]
Thanks for the quickly response, I'll check this. Thanks.

**Comment by gustavotpd** [comment]
Check with ps aux | grep name_of_my_script and no other instance running. 
My script is simple, listen to /photo and take a photo with picamera, running diceyclock.py I got the same error. Thanks.

My script: 

def handle(msg):
    chat_id = msg['chat']['id']
    command = msg['text']

    print 'Recebi o  comando: %s' % command

    if command == '/photo':
        path=os.getenv("HOME")
        with picamera.PiCamera() as picam:
                picam.rotation=90
                picam.framerate = 24
                picam.annotate_background = picamera.Color('black')
                picam.annotate_text = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
                picam.capture(path+'/pic.jpg',resize=(640,480))
                time.sleep(2)
                picam.close()
                bot.sendMessage(chat_id, 'Enviando imagem, pode demorar alguns segundos. Por favor aguarde...')
                f  = open(path+'/pic.jpg', 'rb')
                bot.sendPhoto (chat_id, f)
    elif command == '/time':
        bot.sendMessage(chat_id, str(datetime.datetime.now()))

bot = telepot.Bot('167680517:AAHPJ9sKIPAugIOhTDw3-d8Zw-ALujnEPTo')
bot.notifyOnMessage(handle)
bot.setWebhook()
print 'Sou o photoBotListener...'

while 1:
    time.sleep(50)

**Comment by nickoala** [comment]
Two things:

1. Put `setWebhook()` *before* `notifyOnMessage(handle)`. It may not make any difference, but more logically correct that way. You should unset webhook *before* trying to `getUpdates()` (which `notifyOnMessage()` calls under the hood).

2. Try `ps aux | grep python` to check if any other bot scripts are running. If there are, make sure they are not using the same bot token as the script you are describing above.

**Comment by nvcken** [comment]
with the same bot token how can we scale telegram bot process ?

**Comment by cuongnv-ibl** [comment]
@nickoala pls help
