### ISSUE TITLE
Error in detection of inline query type?

### ISSUE THREAD

**Issue by eyalzek** [nickoala/telepot#150]
I wrote a bot that takes an inline query and returns gif options. I construct my responses as such:

```
InlineQueryResultGif(
    type = "gif",
    id = data["id"],
    gif_url = data["url"],
    gif_width = data["width"],
    gif_height = data["height"],
    thumb_url = data["thumb_url"]
)
```

But on some queries I'm getting the following error:

`TelegramError: (u'Bad Request: Can\'t find field "gif_file_id"', 400, {u'error_code': 400, u'ok': False, u'description': u'Bad Request: Can\'t find field "gif_file_id"'})
`

As far as I understand `gif_file_id` is part of `InlineQueryResultCachedGif` and not `InlineQueryResultGif`. I've review my result and they seem ok, I don't know which one specifically causes the problem.

This is using the latest telepot version and python 2.7.6. I tried using python 3.5 to see what it says, but with it I'm getting: `ValueError: Invalid answer format`.

**Comment by nickoala** [comment]
My guess is this. If you look at the Bot API spec of [InlineQueryResultGif](https://core.telegram.org/bots/api#inlinequeryresultgif) and [InlineQueryResultCachedGif](https://core.telegram.org/bots/api#inlinequeryresultcachedgif). They both have the type `gif`. The only way for Telegram to distinguish the two is by the presence of the field `gif_file_id` or `gif_url`. 

Is it possible that some of your `data["url"]` may be `None` or 0 or empty string or something like that? When Telegram does not see a `gif_url`, it may look for `gif_file_id`, which causes the error you saw.

**Comment by eyalzek** [comment]
Yep, you're right. I was returning objects with value `None` for "gif_url". Thanks :) Closing.
