### ISSUE TITLE
reply_markup is not working

### ISSUE THREAD

**Issue by Serafim-End** [nickoala/telepot#152]
Hi, 
I have a simple implementation which based on your library.
Earlier sendMessage with parameter reply_markup works fine,
but about five days ago it has broken.

callback_data in markup is not working for me in variants where I use it. 
`    mark_up = InlineKeyboardMarkup(inline_keyboard=[
        [dict(text=settings.MORE,
              callback_data='/nearest{}'.format(
                  number_of_cinemas + settings.CINEMA_TO_SHOW
              ))]
    ])`

Have you idea how to fix it?

**Comment by nickoala** [comment]
So, why did it work before?

**Comment by Serafim-End** [comment]
please explain.
