### ISSUE TITLE
Telepot for Building Automation

### ISSUE THREAD

**Issue by suibaf** [nickoala/telepot#153]
Hi,
I'm writing an app for building automation with raspberry PI and I need to manage some situation.
1) If the raspberry pi is off of course the bot is off. When I start UP the raspberry the bot answer to all command that is arrived when it is off. I want to avoid this behavior. Is there a solution?
2) Raspberry PI is connect to internet with a wifi key (with a router or Smartphone hotspot). If it lose the connection (router off for example) then the bot is not able to reconnect. Raspberry is online but the bot no response.
Excuse for my poor english, and keep in mind that I'm newbie od python.
BR

**Comment by zumoshi** [comment]
Hello,
for the first problem try putting this code at the beginning of your code:
```python
# bot initialization , you probably already have this
import telepot
bot = telepot.Bot('token')

# getting updates that was sent to bot when it was off
updates = bot.getUpdates(limit=100,timeout=0)
if len(updates)>0:
    # telling telegeram that we have proccesed them
    bot.getUpdates(offset=updates[-1]['update_id']+1,timeout=0)

# message loop or whatever here
```
this will ignore up to 100 messages that were sent when the bot was offline

as for your second question, I'm not sure what you are asking, if the internet is gone of course the bot can't work. but if you mean after the internet is back bot fails to reconnect, that should not be the case. how did you set up the bot? `bot.message_loop(handler)` should keep retrying indefinitely. (#53)

**Comment by suibaf** [comment]
Hi Zumoshi,
 thank you very much.
Yes I use bot.message_loop(handler). I will test yet!! 
I'll let you know
BR

**Comment by suibaf** [comment]
Zumoshi,
for example: if internet is gone and I start the bot there is an exception and the file py is closed. Same think if, while the bot is running, the internet go out. I need to avoid this behavior.
Thank you.

**Comment by zumoshi** [comment]
i just tested and the `bot.message_loop` won't stop (app won't get closed) when there is no internet.

alternatively, you can also try running your bot via [supervisord](http://supervisord.org/) or similar app runners that automatically restart your bot in case it crashed. this way you can let it crash when there is no internet and it will restart until the net is back on. 

here is a good tutorial on using supervisord: https://www.digitalocean.com/community/tutorials/how-to-install-and-manage-supervisor-on-ubuntu-and-debian-vps

**Comment by suibaf** [comment]
Strange!! Why my app is closed? If I start bot while there is NOT internet, it try two or three time and then close.

**Comment by suibaf** [comment]
In this post, I read that if no internet telepot try in infinite loop to reconnect. And I agree. But in my case it is closed.

**Comment by suibaf** [comment]
Here the message of the error and then it close:

  File "bot.py", line 164, in <module>
    bot.sendMessage(item, a + ' ' + dataora, reply_markup=show_keyboard)
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 240, in sendMessage
    return self._api_request('sendMessage', _rectify(p))
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 229, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telepot/api.py", line 130, in request
    r = fn(*args, **kwargs)  # `fn` must be thread-safe
  File "/usr/lib/python2.7/dist-packages/urllib3/request.py", line 135, in request_encode_body
    **urlopen_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 153, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 559, in urlopen
    _pool=self, _stacktrace=stacktrace)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/retry.py", line 223, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 304, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 724, in _validate_conn
    conn.connect()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 203, in connect
    conn = self._new_conn()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 133, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/connection.py", line 64, in create_connection
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
urllib3.exceptions.ProtocolError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))

**Comment by suibaf** [comment]
Please,
have you advice for me?

**Comment by zumoshi** [comment]
where is line 164 in bot.py ?

if it's inside the `handler` that is given to `message_loop` it should not crash the app (handler is run inside a try block), if it's outside in your code, you can put it inside a try block, so the app won't crash if it failed.

however, that might not be the best option if you expect it to succeed before next lines are executed.

my suggestion is that you use supervisord or similar apps and let them handle restarting your bot until the net is back on, instead of preventing it from crashing. (since the bot can't really do anything without the internet anyway)

**Comment by suibaf** [comment]
Zumoshi,
after some hour of test I understand somethink.
While the bot is running I unplug the cable of net the app crash on the new raspian 4.4.13-V7+#894.
On the old version of raspian 4.1.19 - V7 + #858 this problem there is NOT.
What can I do further your solution with supervisor?
BR
