### ISSUE TITLE
Location objects

### ISSUE THREAD

**Issue by silverWeaver** [nickoala/telepot#154]
Does it support location objects as described in Telegram API?
I mainly want the bot to send location and viewed as a map by the end user.

**Comment by zumoshi** [comment]
hello,
yes, telepot supports all telegram api methods including sendLocation.
from the [reference](http://telepot.readthedocs.io/en/latest/reference.html#basic-bot).

> sendLocation(chat_id, latitude, longitude, disable_notification=None, reply_to_message_id=None, reply_markup=None)
See: https://core.telegram.org/bots/api#sendlocation

sample usage can be found [here](https://github.com/nickoala/telepot/blob/master/test/test27_send.py#L258)

**Comment by silverWeaver** [comment]
Excellent! Thanks a lot!

**Comment by silverWeaver** [comment]
OK I tried the sendLocation method and works as expected. 
However the bot can't handle location objects as input from the user. Is this correct? It seems like it ignores them. They don't even arrive in the code. Maybe it's a telegram issue?

**Comment by zumoshi** [comment]
there is no problem with receiving locations in telegram or telepot. I just tested with the following code:
```python
import telepot
bot = telepot.Bot('token')

def handle(msg):
    print(msg)

bot.message_loop(handle, run_forever=True)

```
and it printed the following when I sent the bot a location : (username/userid has been changed)
```json
{  
   "from":{  
      "username":"...",
      "id":999,
      "first_name":"xxx",
      "last_name":"xxx"
   },
   "chat":{  
      "type":"private",
      "username":"...",
      "id":999,
      "first_name":"xxx",
      "last_name":"xxx"
   },
   "location":{  
      "latitude":27.782915,
      "longitude":30.635874
   },
   "message_id":2,
   "date":1473680983
}
```

perhaps you have an if or something similar in your code that prevents getting this message ? also note that the `text` key is missing , so if you have:
```python
if msg['text'] == '/start':
```
in your code it will crash, you must first check the message type.

**Comment by silverWeaver** [comment]
You were right!
Thanks for the help!
