### ISSUE TITLE
Reconnect timeout

### ISSUE THREAD

**Issue by dmitriyap** [nickoala/telepot#156]
I'm using telepot to run a bot on Raspberry Pi that controls and reports heating in my house.
Issue is that internet connection is not reliable there and sometimes it goes offline (and downtime could be hours). Telepot seems to handle these cases pretty well, but the moment internet goes off it starts infinitely retrying to connect, causing high CPU load. Which is not good as far as other tasks are also running in the background and there are no real reason to do these attempts without timeout in my case.
Is there is a way to configure retry attempts to have 1..5 seconds delay between attempts?
Would be great to have this delay to be an option for **bot.message_loop()**

**Comment by nickoala** [comment]
Use the `relax` parameter:
```python
bot.message_loop(relax=1.5)  # seconds
```
Beware of the consequence though. This would introduce a 1.5-second delay between *every* `getUpdate` call, even if internet connection is intact and `getUpdate` is successful. If you don't mind such a small delay, that would do it. Telepot currently does not have separate `relax` parameters for each case (when internet is ON or OFF).

**Comment by dmitriyap** [comment]
Thanks,

I read about relax param, but my concerns was exactly what you explained: it would take unread_messages * 1.5 seconds to process queue of unread updates after it goes life.

Btw, what would be the right way to skip all unread messages apart of say last 5?

**Comment by nickoala** [comment]
Actually, I don't think each new message will necessarily be separated by 1.5 seconds. `getUpdates` can return many messages in one call. Only calls to `getUpdates` are separated by 1.5 seconds.

"Skip all unread messages apart of last 5"? I don't quite know what you mean ...

**Comment by dmitriyap** [comment]
I got it.

My last question was about a situation when my bot comes online and there are 100 unread messages, but I only want to process last 5 and skip all the rest.

**Comment by nickoala** [comment]
When your bot comes online and there are 100 messages waiting, I suspect `getUpdates` will give you all 100 messages at once. If that's the case, `relax` for 1.5 seconds would not be a problem, for those 100 messages at least.
