### ISSUE TITLE
Migration to 9.1

### ISSUE THREAD

**Issue by oc2pcoj** [nickoala/telepot#158]
Well. Everything worked fine until updating to 9.1.
How can I mix per user handler and inline queries in single class?

This is my old logic:

```
class UserTracker(telepot.helper.UserHandler)
...
    def on_message(self, msg):
        flavor = telepot.flavor(msg)
        print flavor
        if flavor == 'inline_query':
        elif flavor == 'chat':
        elif flavor == 'callback_query':
...
db_connection = psycopg2.connect(DB_NAME)
bot = telepot.DelegatorBot(TOKEN, [
    (per_from_id(), create_open(UserTracker, db_connection, timeout=20)),
])
```

I updated my code for new changes:

```
class UserTracker(telepot.helper.ChatHandler, telepot.helper.AnswererMixin):
    def __init__(self, *args, **kwargs):
        super(UserTracker, self).__init__(*args, **kwargs)
```

``` python
bot = telepot.DelegatorBot(TOKEN, [
    pave_event_space()(
        per_chat_id(), create_open, UserTracker, timeout=50
    ),
])
```

But inline doesn't work.
I have got flavor with '_idle' value and bot crashes

```
raise exception.EventNotFound(event)
EventNotFound: Event(timestamp=1473624346.643259, data={'_idle': {'seconds': 50, 'source': {'id': 110821612, 'space': 1}}})
```

**Comment by nickoala** [comment]
Two questions:

1. Which *inline* do you mean, inline query or inline keyboard?

2. How often does `EventNotFount` happen?

**Comment by oc2pcoj** [comment]
1. Inline query. 
```telepot.flavor(msg) == 'inline_query'```
2. `EventNotFount` happens after inline queries from groups. For example:
I send message to bot and it handle it. After this I send inline query from another chat to bot. I haven't got `inline_query` from telepot.flavor(msg). After this I send message from simple chat and telepot crashes with `EventNotFount`

**Comment by nickoala** [comment]
Your intention calls for `per_from_id()` and `UserHandler`. In other words:

```python
class UserTracker(telepot.helper.UserHandler, telepot.helper.AnswererMixin):
   blah blah blah
```

```python
bot = telepot.DelegatorBot(TOKEN, [
    pave_event_space()(
        per_from_id(), create_open, UserTracker, timeout=50
    ),
])
```

For more details, please refer to my answer in #155

As for `EventNotFound`, I think it's related to #140. I suspect it's a bug in telepot, but have not time to check it out.

**Comment by oc2pcoj** [comment]
Should I use different implementation for handling inline and chat queries? 

```
bot = telepot.aio.DelegatorBot(TOKEN, [
    pave_event_space()(
        per_inline_from_id(), create_open, telepot.helper.InlineUserHandlerSubclass, timeout=10),

    pave_event_space()(
        per_from_id(), create_open, telepot.helper.UserHandlerSubclass, timeout=10),
])
```

**Comment by oc2pcoj** [comment]
Well. I fix my code for inline queries. It works! But I don't understand roots of `EventNotFound ` problem. It is very often exception.

**Comment by oc2pcoj** [comment]
@nickoala can I change text of sent messages with InlineKeyboardButton? I can't find solution for this.

**Comment by nickoala** [comment]
What do you mean by "change text of sent messages with InlineKeyboardButton"?

**Comment by oc2pcoj** [comment]
I try this in callback query:
```
query_id, from_id, query_data = telepot.glance(msg, flavor='callback_query')
message = msg['message']
msg_id = message['message_id']
bot.editMessageText((message['chat']['id'], msg_id), 'Test message')
```
But it causes error:
```
TelegramError: (u'Bad Request: Wrong inline message identifier specified', 400, {u'error_code': 400, u'ok': False, u'description': u'Bad Request: Wrong inline message identifier specified'})
```

**Comment by nickoala** [comment]
I tried the same thing, and it worked for me. The message identifier `(chat_id, message_id)` is correct.

A quicker way to obtain the message identifier is this:
```python
msg_idf = telepot.message_identifier(msg['message'])
bot.editMessageText(msg_idf, 'NEW MESSAGE HERE')
```
This should be equivalent to what you did, so I still have no idea why it didn't work for you. It worked for me both ways.
