### ISSUE TITLE
Problem sending internet GIFs

### ISSUE THREAD

**Issue by Noammac** [nickoala/telepot#159]
I tried to get a random GIF in a certain category using the [`giphypop`](https://github.com/shaunduncan/giphypop) wrapper, but when I send it using the `bot.sendPhoto()` method it just sends the first frame. Here's my code:
```python
random_img = giphypop.random_gif("boop cat", api_key=GIF_TOKEN, strict=True)
requests.get(random_img.media_url)
bytearr = io.BytesIO(response.content)
bot.sendPhoto(usid, ("boop.gif", bytearr), caption="Powered by Giphy")```

**Comment by nickoala** [comment]
Well, I don't know what `giphypop` does, but here's my take:

1. You download a `media_url`. I assume those are bytes of a GIF image.
2. You send the bytes using `sendPhoto`

Why do you expect it to send *more than* one image?

**Comment by Noammac** [comment]
I'm expecting it to send an animated gif like the one I actually got from
`media_url`, instead it just sends the forest frame and that's it.

**Comment by nickoala** [comment]
`sendPhoto` returns a bunch of `file_id`s. You can [download the image file by picking one of them](http://stackoverflow.com/questions/34170546/getfile-method-in-telegram-bot-api/34184899). It appears `sendPhoto` treats animated GIF as JPG, thus your first frame.

Use `sendDocument` to send animated GIF. You will get what you want.

**Comment by Noammac** [comment]
It worked, thanks.
