### ISSUE TITLE
Return venue on inline query

### ISSUE THREAD

**Issue by RomanPeters** [nickoala/telepot#163]
So it looks like I'm doing something wrong.

I'm trying to return an inline query. While articles are no problem, I couldn't quite figure out how to return a venue using an inline query.

I tried:

```
message = {'latitude': 52.00000000000000, 
                     'longitude': 5.00000000000000, 
                     'title': 'Place', 
                     'address': 'Streetstreet 123'}


inline_result = [InlineQueryResultVenue(
     id='venue, 
     title=message.get('title'),
     input_message_content=InputVenueMessageContent(
             latitude=message.get('latitude'),
             longitude=message.get('longitude'),
             title=message.get('title'),
             address=message.get('text')))]
return inline_result
```

But this raises an error:

`telepot.exception.TelegramError: ('Bad Request: Can\'t find field "latitude"', 400, {'ok': False, 'description': 'Bad Request: Can\'t find field "latitude"', 'error_code': 400})`

What am I doing wrong that makes the API unable to properly pass the latitude?

**Comment by nickoala** [comment]
Looking at the structure of [InlineQueryResultVenue](https://core.telegram.org/bots/api#inlinequeryresultvenue), it should be something like:

```python
InlineQueryResultVenue(
    id='venue1', 
    title=message.get('title'),
    latitude=message.get('latitude'),
    longitude=message.get('longitude'),
    address=message.get('address')
)
```

**Comment by RomanPeters** [comment]
That did it!
Thank you very much.
