### ISSUE TITLE
Unicode and the telegram token

### ISSUE THREAD

**Issue by nodex0** [nickoala/telepot#164]
I am not sure if this is exactly an issue but I wanted to point it out, since I saw related problems in old issues and took me some time.

When builiding a new telepot bot, if you imported the token from, lets say, JSON, the bot will be instanced normally, but every call will cause it to break. So, if the token is unicode, the bot will break in every request to the telegram API because it gets concatenated to strings. Using python 2.7.

**Comment by nickoala** [comment]
Using Python 2.7, this works for me:
```python
>>> import telepot
>>> bot = telepot.Bot(u'12345678:TOKEN')
>>> bot.sendMessage(999999999, 'hello')
```
I explicitly made the token unicode, and `sendMessage` works fine.

**Comment by nodex0** [comment]
This is what I did:
```python
>>> import telepot
>>> bot = telepot.Bot(u'12345678:TOKEN')
>>> bot.sendMessage(10809372, "¡hello!")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xad in position 83: ordinal not
in range(128)
>>> bot.sendMessage(10809372, u"¡hello!")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 83: ordinal not
in range(128)
```
If the message has non-ascii characters it doesn't work, and even if the sendMessage string is set to unicode, still not working.
However if the token string is a normal byte string, it does work, with unicode and byte strings (however normal bytes strings have to be properly encoded or so).

**Comment by converge** [comment]
Im trying to sendMessage()

`
msg = 'é'
msg = unicode(msg, 'utf-8')
telegramBot.sendMessage('@testBot', msg)
`
but always get this error:
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 49: invalid continuation byte

am I doing something wrong ?

**Comment by nickoala** [comment]
Well, these all work for me, both on Python 2.7 and 3.5, on Raspbian Jessie:
```python
bot.sendMessage(111111111, u'香港')
bot.sendMessage(111111111, u'¡hello!')
bot.sendMessage(111111111, u'é')
```
I really have no idea why those decode errors occur :thinking:

**Comment by converge** [comment]
I fixed it forcing the default encode in this way:

`# encoding setup
reload(sys)
sys.setdefaultencoding('utf-8')`

**Comment by I-MrFixIt-I** [comment]
I had the same problem,
I solved it by saving the script itself as an utf-8 file and not as standard as ascii

**Comment by jhorrell** [comment]
I had the same problem (Python 2.7). Bot instantiates OK and telepot methods like sendMessage() and getMe() work fine, but sendPhoto() runs into the encoding errors when the bot token is read from json e.g. "Error when sending the photo is: UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 445: ordinal not in range(128)".

The solution was to use the str() method on the token when instantiating the bot e.g. bot = telepot.Bot(str(token)). Thereafter, the sendPhoto() method works with file-like objects as obtained by open().

**Comment by nickoala** [comment]
This may not be relevant. I am writing this in case someone find it useful.

If you use `sendPhoto()` or similar methods to send files and you obtain the file-like object using `open()`, **remember to give the `rb` flag**, e.g. `open(path, 'rb')`. Forgetting the `b` may result in some kind of encoding error, similar to the ones discussed in this thread.
