### ISSUE TITLE
Argument to on_callback_query() is not a Message

### ISSUE THREAD

**Issue by pymaldebaran** [nickoala/telepot#167]
While debugging a problem I had with the way I handled the callback query in my bot I discovered that the actual argument passed to the `on_callback_quey(self, msg)` named msg was in fact... not a Telegram Message 😱.

Two clues led me to this conclusion. First when trying to convert to a namedtuple `Message` I get a warning:
```python
>>> Message(msg)
/usr/lib/python3.5/site-packages/telepot/namedtuple.py:48: UserWarning: Unexpected fields: data, id, inline_message_id, chat_instance
Bot API seems to have added new fields to the returned data. This version of namedtuple is not able to capture them.

Please upgrade telepot by:
  sudo pip install telepot --upgrade

If you still see this message after upgrade, that means I am still working to bring the code up-to-date. Please try upgrade again a few days later. In the meantime, you can access the new fields the old-fashioned way, through the raw dictionary.
  warnings.warn(s, UserWarning)
```

Ok at first I did not paid too much attention to the error since Telegram has been updated yesterday with some new types related to games.

Second clue: for debugging purpose I always log a pprint of each message my bot receive. This one was no exception:
```python
>>> pprint(msg)
{'chat_instance': '-6597979017591450366',
 'data': '1 0',
 'from': {'first_name': 'James',
          'id': 1007,
          'last_name': 'Bond',
          'username': 'jamesbond007'},
 'id': '123456789012345',
 'inline_message_id': 'BAAAAJorAAAz4B6OldTqM5uGeY8'}
```
(ok, to protect Great Britain finest agent privacy I edited some values)

Searching through the Telegram API doc it seems the actual object received is a [CallbackQuery](https://core.telegram.org/bots/api#callbackquery) dict.

If this is actually true, the `msg` name of the param is really misleading... it appears in the [source code](https://telepot.readthedocs.io/en/latest/_modules/telepot/helper.html#DefaultRouterMixin) and in the [examples](https://github.com/nickoala/telepot/blob/master/examples/callback/lover.py). I know that technically a argument name is not a bug... but since we mostly infer the role and type of an argument through its name I really think this could be misleading.

**Comment by pymaldebaran** [comment]
It seem the only new mandatory field since the recent update is `chat_instance` so even when doing my conversion to a `telepot.namedtuple.CallbackQuery`, I still got a warning but only about that specific field:

```python
>>> msg = CallbackQuery(msg)
/usr/lib/python3.5/site-packages/telepot/namedtuple.py:48: UserWarning: Unexpected fields: chat_instance
Bot API seems to have added new fields to the returned data. This version of namedtuple is not able to capture them.

Please upgrade telepot by:
  sudo pip install telepot --upgrade

If you still see this message after upgrade, that means I am still working to bring the code up-to-date. Please try upgrade again a few days later. In the meantime, you can access the new fields the old-fashioned way, through the raw dictionary.
  warnings.warn(s, UserWarning)
```
So it really seems we always receive a CallbackQuery object in the `msg` argument of `on_callback_query()`. Let's call this my 3rd clue).

But maybe you prefer to keep the `msg` name for all the arguments of the different `on_*(self, msg)` methods.

**Comment by nickoala** [comment]
For everything received by the bot, [I generically call them "message"](http://telepot.readthedocs.io/en/latest/#message-has-a-flavor), with a lowercase "m". A message can be a `Message` (uppercase "M"), `CallbackQuery`, `InlineQuery`, or `ChosenInlineResult`.

In a lot of places in the source code, I use the name `msg` in a generic sense. Which type a `msg` actually is, hopefully, should be obvious from the context. For example, in the case of `on_callback_query(self, msg)`, it obviously means a `CallbackQuery`.

I admit this can be confusing, but that's the decision I have made.

**Comment by pymaldebaran** [comment]
I thought it was something like that... but wasn't sure.

And, now that I know, it seems like a good decision. Though I think that your last sentence is very important:

> I admit this can be confusing, but that's the decision I have made.

And it should appear in the documentation and be emphatised... in the same way you do with the namedtuples in the [Message has a flavor]() tutorial/do:

> Pay attention to these things in the code:
> 
> * How I use namedtuple to construct an InlineKeyboardMarkup and an InlineKeyboardButton object

This would learn to the new user to pay attention to the context when using `msg` parameters. If ever I can be of any help to acheive this, just tell me (of course if you think it's a good thing).

Thank you anyway for your answer and explanation about your wonderful project.
