### ISSUE TITLE
Can't post photo without a photo file buffer

### ISSUE THREAD

**Issue by boxama** [nickoala/telepot#17]
I'm reading a file directly from a web source, so I've got its data as bytes.
Using io.BytesIO I can get the buffer for it, but attempting to post the photo will give me an error:

`telepot.TelegramError: ('[Error]: Photo has unsupported extension. Use one of .jpg, .jpeg, .gif, .png, .tif or .bmp', 400)`

This is how I was attempting it:

```python
bot.sendPhoto( chat, BytesIO(urlopen( imageURL ).read()) )
```
So I tried to use a cache file to store the data. You'll have to take my word for it, but the file was properly stored and I was able to open it:

```python
    with open( 'cache' , 'wb') as f:
        f.write( urlopen( imageURL ).read() )
    bot.sendPhoto( chat, open( 'cache', 'rb' ) )
```
This gave me the exact same error. 
However, appending '.jpg' to the end of the cached file name worked and the image was properly posted in the chat.

So my question is 'How do I post a photo without caching the data in a file with an image extension?'

**Comment by nickoala** [comment]
Hello, I just had a new version of telepot out, and am busy updating the documentations. Given that you've solved the problem by caching and changing the file name, I will come back to you after all the urgent stuff is done.

Thanks for presenting the complete story of your problem.

**Comment by ravxl** [comment]
dumb question, have you tried to append the file extension directly in the
first try? that one without the cache!

**Comment by boxama** [comment]
Not quite sure what you mean. If you meant appending an extension to the end of the data, that didn't work, unsurprisingly.

It seems that buffers created using `open` have an attribute/property 'name' attached when they're printed, which is the file name.

Looks like all I had to do was set the name myself `buffer.name = 'cache.jpg'` and everything works.
