### ISSUE TITLE
does it works with unlimited timeout?

### ISSUE THREAD

**Issue by jinsyu** [nickoala/telepot#170]
bot = telepot.DelegatorBot(TOKEN, [
    include_callback_query_chat_id(
        pave_event_space())(
            per_chat_id(types=['private']), create_open, WrongAnswer, timeout=10),
])
bot.message_loop(run_forever='Listening ...')

I assigned some values to my Class.
self.XXX = ''
it keeps initiating value after time out.
I just want to keep this value forever.
Is there any possible way to keep it??
I know it is ridiculously simple question, but please let me know,.

**Comment by nickoala** [comment]
After timeout, the original object becomes useless. Next time the bot receives a message from that user, a new `WrongAnswer` object is created. If you want a value persisting across multiple objects, you would have to keep it "outside" of the object, e.g. in a global variable, in a database, in a config file, etc.
