### ISSUE TITLE
max retry error

### ISSUE THREAD

**Issue by mpirbay** [nickoala/telepot#174]
Hello,
I am using telepot with the diceyclock example.
I get these errors:

> MaxRetryError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /xxxxxxxxxxxxxxxxxxxxxxxxxxxx/getUpdates (Caused by ProtocolError('Connection aborted.', gaierror(-2, 'Name or service not known')))

although these errors do not seem to affect the bot which keeps running, I would like to fix them.
Thank you

trace:

> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/telepot/**init**.py", line 756, in get_from_telegram_server
>     result = self.getUpdates(offset=offset, timeout=timeout)
>   File "/usr/local/lib/python2.7/dist-packages/telepot/**init**.py", line 624, in getUpdates
>     return self._api_request('getUpdates', _rectify(p))
>   File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 398, in _api_request
>     return api.request((self._token, method, params, files), *_kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/telepot/api.py", line 130, in request
>     r = fn(_args, *_kwargs)  # `fn` must be thread-safe
>   File "/usr/lib/python2.7/dist-packages/urllib3/request.py", line 135, in request_encode_body
>     *_urlopen_kw)
>   File "/usr/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 153, in urlopen
>     response = conn.urlopen(method, u.request_uri, *_kw)
>   File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 579, in urlopen
>     release_conn=release_conn, *_response_kw)
>   File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 579, in urlopen
>     release_conn=release_conn, *_response_kw)
>   File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 579, in urlopen
>     release_conn=release_conn, *_response_kw)
>   File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 559, in urlopen
>     _pool=self, _stacktrace=stacktrace)
>   File "/usr/lib/python2.7/dist-packages/urllib3/util/retry.py", line 265, in increment
>     raise MaxRetryError(_pool, url, error)

**Comment by nickoala** [comment]
It may be due to Telegram servers temporarily down. Can you try again?

**Comment by mpirbay** [comment]
Thank you for your quick reply.
Actually my server has benn running for days, and I have literally tens of this message. However, as I said before, it does not seem to prevent the bot from running: it works perfectly.
Maybe, instead of telegram servers being down, it could be because of my own internet link being down from time to time?

**Comment by nickoala** [comment]
Yes, it could also be an unreliable internet connection.

**Comment by mpirbay** [comment]
since these messages do not seem to prevent the bot from running, is there a way to avoid them?

**Comment by nickoala** [comment]
Please see **[How to mute Telepot logs?](https://github.com/nickoala/telepot/issues/139)**

Simply put, there's no easy way, unfortunately.
