### ISSUE TITLE
sendPhoto doesn't send image encoded anymore

### ISSUE THREAD

**Issue by andreasalvi** [nickoala/telepot#177]
Hello,
I've this code. frame is a Mat variable of opencv that contains an image

`img_str = cv2.imencode('.jpg', frame)[1].tostring()`
` bot.sendPhoto(chat_id,['image.jpg', img_str])`

I used this code some months ago and all worked fine but now don't.

**Comment by fedebecat** [comment]
We managed overcome this issue by using

import StringIO
bot.sendPhoto(chat_id,('image.jpg', StringIO.StingIO(img_str)))

**Comment by thalesmaoa** [comment]
Its not working here. I have a frame, mat numpy, and just want to sent with telepot.
