### ISSUE TITLE
Telepot version

### ISSUE THREAD

**Issue by suibaf** [nickoala/telepot#180]
How to ceck telepot version installed on raspberry?

**Comment by nickoala** [comment]
Sorry, there's no easy way :sweat_smile: 

You may go to where the library is installed, e.g. `/usr/lib/python2.7/dist-packages`, and see which version was downloaded. The version number should be indicated in the directory name or something like that.

**Comment by nickoala** [comment]
Now, with telepot 10.2, there is an easy way:
```
>>> import telepot
>>> telepot.__version_info__
(10, 2)
>>> telepot.__version__
'10.2'
```

**Comment by suibaf** [comment]
wonderfull!
