### ISSUE TITLE
telepot for building automation

### ISSUE THREAD

**Issue by suibaf** [nickoala/telepot#181]
Hi,
I send a message to my BOT: "open the door":

scenario 1) my BOT receive the message and open the door, but for some reason the feedback does not arrive to me, and I'm tempted to resend the same message. So I open the door 2 or more time

scenario 2) my Bot does not receive the message, for some reason, of course the feedback does not arrive to me. I resend the message.  After some time my BOT receice all the message "open the door" and open the door more time.

Is it possible to avoid this state?

**Comment by nickoala** [comment]
It seems like Telegram servers were just being slow. This kind of situation can happen once in a while. Is it still persisting?

**Comment by suibaf** [comment]
Under normal conditions this does not happen. But I have predict it.
If BOT's adsl connection go down, the user send messages, BOT does not response and the user resend the message. You can understand that if I use BOT to operate electrical mechanisms, there is good chance to create some problem. 
Is it possible to avoid this state?

**Comment by nickoala** [comment]
Well, if the ADSL connection goes down, there is **no way** the bot can get the messages. If you want the bot to operate reliably, you must get a consistent internet connection.
