### ISSUE TITLE
How to Host A Bot in Telepot On Web

### ISSUE THREAD

**Issue by dhruvramdev** [nickoala/telepot#182]
I am new to Telepot and Wanted to  how to host my bot for free.
Any free service will do on which bot could be hosted.
Your help is highly appreciated

**Comment by nickoala** [comment]
Well, this is really not the space to ask this question ....

In theory, any web hosting services would do. Free ones? I can think of Google App Engine. But you still have to learn the nuts and bolts of how to use it.
