### ISSUE TITLE
Update Telepot to Bot API 2.3

### ISSUE THREAD

**Issue by NotAFile** [nickoala/telepot#183]
Full changelog: https://core.telegram.org/bots/api#recent-changes

The big one seems to be channel post notifications, the other ones sound very simple to implement.

**Comment by nickoala** [comment]
Thanks. If all goes well, update should be available on or before Nov 30<sup>th</sup>.

**Comment by NotAFile** [comment]
I'll try to help if I can. Will channel messages just have a "channel" chat_type, or do you plan on doing more than that?
