### ISSUE TITLE
KeyError while Speaking to my Bot in Channel

### ISSUE THREAD

**Issue by boscolai1991** [nickoala/telepot#187]
Dear,

I was speaking to my bot in a Channel where my bot and I are both channel administrator. My bot is listening with the following simple code:

> 

```
def handle(msg):
    print(msg)

bot = telepot.aio.Bot(TOKEN)
loop = asyncio.get_event_loop()

loop.create_task(bot.message_loop(handle))

print('Listening ...')
loop.run_forever()
```

It give me this error `KeyError` when I say 'hi' or type some botcommand in the channel:

> Listening ...
Traceback (most recent call last):
  File "C:\Users\type_ok_login\AppData\Roaming\Python\Python35\site-packages\telepot\aio\__init__.py", line 419, in handle
    'chosen_inline_result'])
  File "C:\Users\type_ok_login\AppData\Roaming\Python\Python35\site-packages\telepot\__init__.py", line 61, in _find_first_key
    raise KeyError(keys)
KeyError: ['message', 'edited_message', 'callback_query', 'inline_query', 'chosen_inline_result']

**Comment by carloalbertobarbano** [comment]
Refer to this issue https://github.com/nickoala/telepot/issues/184
