### ISSUE TITLE
icon button

### ISSUE THREAD

**Issue by suibaf** [nickoala/telepot#189]
Is it possible to add a icon to buttons?
As this example: http://www.howtochoosealaptop.com/wp-content/uploads/2015/10/MyPokerBot2.jpg

**Comment by garciaw** [comment]
Yeah, just write them on the "text" field of your button, together with what you are already writing there.
I use http://emojipedia.org for most of my emoji searching.

**Comment by suibaf** [comment]
Hi garciaw,
tahnk you for your response. Now I can see the icon but
Python(2.7) give me the following error: UnicodeEncodeError: 'charmap' codec can't encode characters in position 18-19: character maps to <undefined>.

Best regards

**Comment by suibaf** [comment]
Ok, I used emoji 0.3.9 and I solved.
Thank you

**Comment by suibaf** [comment]
On raspberry Pi 2 work fine, on windows 7 (64) does not!
Can you tell me some advice?
BR

**Comment by suibaf** [comment]
But not all work fine! Only one every 10 icon!

**Comment by fabiocody** [comment]
Emojis are Unicode characters, and, if I'm not wrong, Python2+ doesn't use Unicode as default. Adding `# -*- coding: utf-8 -*-` at the beginning of your file (right after the shebang line if you have one) should fix your problem.
