### ISSUE TITLE
File_id

### ISSUE THREAD

**Issue by eldire** [nickoala/telepot#190]
Good night, when I am trying to retrieve the id of a file by
  Content_type, chat_type, chat_id, file_id, file_name = telepot.glance (msg, long = True), I do not receive the id, instead I get the date.and instead of the file name I get the id of the message
Can anybody help me?.
Thank you

**Comment by nickoala** [comment]
`glance(msg, long=True)` gives a tuple of `(content_type, chat_type, chat_id, msg_date, msg_id)`. It has nothing to do with file id of any kind.

What file id are you trying to get?

**Comment by eldire** [comment]
Hello again. I'm trying to get the bot to get .torrent files to move them to a specific directory. But I do not know how to get the file_id to be able to download. The example that appears on the page does not completely understand.

Thanks again.

**Comment by nickoala** [comment]
You may download files with the method [`download_file()`](http://telepot.readthedocs.io/en/latest/reference.html#telepot.Bot.download_file), after obtaining the `file_id` from the message's [`document`](https://core.telegram.org/bots/api#document) field. For example:
```python
file_id = msg['document']['file_id']
bot.download_file(file_id, '/path/to/downloaded/file')
```
