### ISSUE TITLE
Stop some function after some hour

### ISSUE THREAD

**Issue by suibaf** [nickoala/telepot#191]
Hi,

my bot work perfectly on Raspberry PI 2. I use it in my house to see some variable and it send me a message if I push some physical buttons. The problem is that sometimes after some hour of work it does not response to my command, but if I push a physical button (on piface digital 2), it send me a message.
The only way to restore all operation is to reboot the raspberry.
Below the code.
Have you some advice for me?
Thank you!

[Sbot.pdf](https://github.com/nickoala/telepot/files/619157/Sbot.pdf)

**Comment by nickoala** [comment]
Sorry I don't have time to analyze and test your code thoroughly. 

My advice is this: Start from the simplest program possible, and increase complexity until the problem occurs. Then, you should have some clue where the problem lies.

**Comment by suibaf** [comment]
OK, thank you!
