### ISSUE TITLE
Loop using the for for multiple articles

### ISSUE THREAD

**Issue by munod** [nickoala/telepot#193]
def on_inline_query(self, msg):
        def compute_answer():
            query_id, from_id, query_string = telepot.glance(msg, flavor='inline_query')
            print(self.id, ':', 'Inline Query:', query_id, from_id, query_string)
 
            conn = sqlite3.connect('knowledge.db')
            cursor = conn.execute("SELECT id, titulo, descricao  from problemas WHERE titulo like? ",
                                  ('%' + query_string + '%',))
 
            for row in cursor:
                print "ID = ", row[0]
                print "TITULO = ", row[1]
                print "DESCRICAO = ", row[2], "\n"
                articles = [{'type': 'article',
                             'id': 'abc', 'title': row[1], 'message_text': row[2]}]
 
 
 
                return articles
 
        self.answerer.answer(msg, compute_answer)

In the example, it only returns the first result.
How would it look to return all the results?

**Comment by nickoala** [comment]
You have to *append* to the list:
```python
articles.append({'type': 'article', 'id': 'abc', 'title': row[1], 'message_text': row[2]})
```

**Comment by munod** [comment]
Ok. Thanks
