### ISSUE TITLE
flask_counter.py example not working , there is no lines for https configuration 

### ISSUE THREAD

**Issue by molavy** [nickoala/telepot#196]
i try test flask_counter.py .
but seems it don't work by itself, all request return 400 bad requsst.
seems there is must be openssl load cert and extra lines that let flask work over https

**Comment by nickoala** [comment]
The activation of SSL certificate is not done in the program, but is done by communicating this need to the server admin.

One way to check the webhook URL is by accessing it over a web browser. It should return "OK" if set up properly. But always remember to type `https://` in the address bar. If you don't do that, the browser would assume `http://`.

**Comment by molavy** [comment]
but i found this
http://flask.pocoo.org/snippets/111/
flask debug can handle ssl by itself, there is also letsencrypt.org that allow has standalone example flask example

**Comment by nickoala** [comment]
Oh, I wasn't aware of that. I always ask my web-hosting provider to activate SSL certificates for me, so didn't know about doing it in flask.

I am also aware of your issue #198, but I really don't know how to help here and there. I tried the `flask_counter.py` last night, and everything worked perfectly for me. The thing is, there can be a variety of reasons why a webhook does not work. I can only point you to [this Marvellous Guide](https://core.telegram.org/bots/webhooks) and hopefully you can figure out what has gone wrong.
