### ISSUE TITLE
How would I get  a command to send the ip address of the bot?

### ISSUE THREAD

**Issue by seiterseiter** [nickoala/telepot#199]
Im wanting to use my telegram bot to send me the ip address of my raspberry pi so that I can connect to it from my laptop. My ip is not static so I cant just use the same one all the time.

**Comment by nickoala** [comment]
Haha, I did a very similar thing in my educational project, [IP Cam using Telegram as DDNS](https://github.com/nickoala/ipcam). You can check it out.
