### ISSUE TITLE
Unhandled empty HTTP response content

### ISSUE THREAD

**Issue by tmmsartor** [nickoala/telepot#203]
> Using python3.6 and python3.5 with async framework.

When trying to send very long text messages this error occurs: 

```
WARNING:aiohttp.client:Attempt to decode JSON with unexpected mimetype:

ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<Answerer.answer.<locals>.compute_and_answer() done, defined at telepot/aio/helper.py:100> exception=TypeError("'NoneType' object is not subscriptable",)>
Traceback (most recent call last):
  File ".. telepot/aio/helper.py", line 107, in compute_and_answer
    await self._bot.answerInlineQuery(query_id, ans)
  File ".. telepot/aio/__init__.py", line 296, in answerInlineQuery
    return await self._api_request('answerInlineQuery', _rectify(p))
  File ".. telepot/aio/__init__.py", line 68, in _api_request
    return await api.request((self._token, method, params, files), **kwargs)
  File ".. telepot/aio/api.py", line 110, in request
    return await _parse(r)
  File ".. telepot/aio/api.py", line 87, in _parse
    if data['ok']:
TypeError: 'NoneType' object is not subscriptable
```
##  Long messages

Text length limit sending **chat messages** are well define,
in fact api.telegram.org return the proper HTTP response error code for code like this:
```
async def handle(msg):
    text = "".join(["☆" for i in range(5000)])
    await bot.sendMessage(msg["from"]["id"],text)
```
The bot receive this HTTP response:
```
HTTP/1.1 400 Bad Request
Server: nginx/1.10.0
Date: Sun, 08 Jan 2017 00:18:49 GMT
Content-Type: application/json
Content-Length: 78
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Content-Length,Content-Type,Date,Server,Connection
```
With HTTP response content:
```
{"ok":false,"error_code":400,"description":"Bad Request: Message is too long"}
```
It raises a `TelegramError` and everything is handled fine.

## Very long messages
One believe that the error from the server will be the same for text of any length greater than the limit,
but this is not true, if one try to send even more text than before like with the following code, the error is different.
```
async def handle(msg):
    text = "".join(["1" for i in range(65536)])
    await bot.sendMessage(msg["from"]["id"],text)
```
This is not so infrequent, in fact when dealing with article **inline answers** in which each of the 50 result slots available have a lot of text is easy to exceed that limit without exceeding the text limit for the single inline article.
With the above code another telegram server limit is reached(~65kB)[1], in this case the HTTP response is different  (status [413 Request Entity Too Large]), and a 0 length response content is returned.
In `telepot` this error isn't caught by the exception handling block because aiohttp response.json() successfully return `None` instead of fail in parsing an empty string as json (not sure why).
And thus it fails later with an unhandled error and a traceback like the one at  the beginning.
The HTTP response received is:
```
HTTP/1.1 413 Request Entity Too Large
Server: nginx/1.10.0
Date: Sun, 08 Jan 2017 00:19:03 GMT
Content-Length: 0
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Content-Length,Content-Type,Date,Server,Connection
```
With empty response content:
```
```
Traceback:
```
Traceback (most recent call last):
  File "simple/skeletona.py", line 22, in handle
    await bot.sendMessage(msg["from"]["id"],text)
  File telepot/aio/__init__.py", line 79, in sendMessage
    return await self._api_request('sendMessage', _rectify(p))
  File telepot/aio/__init__.py", line 68, in _api_request
    return await api.request((self._token, method, params, files), **kwargs)
  File telepot/aio/api.py", line 111, in request
    return await _parse(r)
  File telepot/aio/api.py", line 88, in _parse
    if data['ok']:

```

[1] See it happen with:
```
for i in `seq 65500 10 66000`; do echo ""; echo $i; curl -i --data chat_id=<chat_id> --data-urlencode  "text=`printf '1%.s' $(seq 1 $i)`" https://api.telegram.org/bot<TOKEN>/sendMessage; done
```

**Comment by nickoala** [comment]
Thanks for laying out the entire story and describing it clearly. Telepot should handle the empty response properly and raises an exception. I will fix that in a later version.

**Comment by nickoala** [comment]
Fixed in 10.5. @tmmsartor, thanks for making telepot better.

Curiously, this issue does not occur in the *traditional* (non-async) version. When I send a very long message, it gives me a normal `TelegramError` saying `Message is too long`. Didn't bother to look deeper, though.

**Comment by Onofrio310817** [comment]
How can I solve this issue?
I had this error with my bot: "'Bad Request: message is too long', 400"
Where the text sent from my bot is very long because is a document text of 11000 words.

**Comment by nickoala** [comment]
@Onofrio310817, it seems like Telegram servers returned this error and telepot was simply relaying that error to you. In other words, Telegram servers were refusing your request because the "message is too long". The only way to fix it is to send shorter messages. Telepot cannot help you there :relaxed:

**Comment by Onofrio310817** [comment]
@nickoala thank you for your answer, infact I have to try a new way to send long message because I have just integrated Pocket apps with the bot and so in this case it has to send me message with text of article saved on Pocket.
