### ISSUE TITLE
how to set inline keyboard button without bot.message_loop

### ISSUE THREAD

**Issue by Sajadkamali** [nickoala/telepot#206]
Hi there 
I've seen this code before 
import sys
import time
import telepot
from telepot.namedtuple import InlineKeyboardMarkup, InlineKeyboardButton

def on_chat_message(msg):
    content_type, chat_type, chat_id = telepot.glance(msg)

    keyboard = InlineKeyboardMarkup(inline_keyboard=[
                   [InlineKeyboardButton(text='Press me', callback_data='press')],
               ])

    bot.sendMessage(chat_id, 'Use inline keyboard', reply_markup=keyboard)

def on_callback_query(msg):
    query_id, from_id, query_data = telepot.glance(msg, flavor='callback_query')
    print('Callback Query:', query_id, from_id, query_data)

    bot.answerCallbackQuery(query_id, text='Got it')

TOKEN = sys.argv[1]  # get token from command-line

bot = telepot.Bot(TOKEN)
bot.message_loop({'chat': on_chat_message,
                  'callback_query': on_callback_query})
print('Listening ...')

while 1:
    time.sleep(10)

I just wanna ask how can i send a message with an inline keyboard and call back query with a loop

**Comment by nickoala** [comment]
I don't quite understand your question (emphasis mine) "how can i send a message with an inline keyboard and call back query *with a loop*"?

The example you gave obviously sends *an inline keyboard with some callback query data*. What do you mean "with a loop"?

**Comment by nickoala** [comment]
And please format your post correctly in the future. Given those few correctly formatted fragments, it seems you know how to do the formatting. Just have to take more care, I guess. :smile:

**Comment by Sajadkamali** [comment]
Sorry about the formatting i was in a hurry on that time!!!
I've fixed my problem using an interesting way but let's explain the problem just for information purposes .

As you see in the above code, I have a loop involving callback and on_chat functions. using this code:
`bot.message_loop({'chat': on_chat_message,
'callback_query': on_callback_query})`

But in my primary project i have a handler function for handling user's input and i wanna use inline keyboard and callback query functions when needed(not as a loop in my code) for example  i want to send inline keyboard to a users when he needs to answer a question. So in my code i have this loop:
`bot.message_loop(handler)`

And as you now i cannot send inline keyboard using this loop because it doesn't include the on_chat and call back function. But i changed a the syntax of the loop code and now it works like a charm here is the fixed loop code:
`bot.message_loop({'chat': handler,
                  'callback_query': on_callback_query})`

As you see it sends chat data to handler and it also listens callback queries
Thanks for your answer and hope you enjoy the formatting!
