### ISSUE TITLE
How to send messages to a channel with ChatHandler

### ISSUE THREAD

**Issue by alesanmed** [nickoala/telepot#207]
I'm trying to handle a conversation with a user, thus I'm using a ChatHandler to handle the multi line commands.

When the conversation ends, I need to send a message to a channel with the conversation result. I'm trying to do it with the following code:
`await self.sender.sendMessage("Text")`

The sender already knows the chat ID so the sendMessage send the message always to the same chat. If I try to do the following:
`await self.sender.sendMessage(chat_id=channel_id, text="Text")`

I get the following error:
`sendMessage() got multiple values for argument 'chat_id'`

If there is a way to send a message to a channel using a ChatHandler I'd appreciate any help to do it.

Thank you very much in advance.

**Comment by mefuckin** [comment]
`await self.bot.sendMessage(channel_id, "Text")`

**Comment by alesanmed** [comment]
Thank you very much! That was just what I needed. You rock
