### ISSUE TITLE
PoolManager timeout

### ISSUE THREAD

**Issue by Gurulhu** [nickoala/telepot#208]
Hi!

I'm having recurring problems with the HTTPConnectionPool timeout. After some idle time, it fails, and only raise an error after a long wait.

After inspecting the code, I notice that there's no way to change the retries and timeout values for sendMessage and other send_ methods, since we can't reach the _pools dictionary.

Could you please add a way to do it in later versions? 

Maybe just a method like the one below, so we can have more control over the response time.

```
pools_config( np=3, ms=10, rt=3, to=30 ):
    global _pools
    _pools = { 
        "default": urllib3.PoolManager( num_pools=np, maxsize=ms, retries=rt, timeout=to )
    }

```

Sorry about bothering, and thanks o/

**Comment by nickoala** [comment]
You should be able to change the default PoolManager by re-defining it at the beginning of your program:
```python
import telepot

telepot.api._pools['default'] = urllib3.PoolManager(num_pools=?, maxsize=?, retries=?, timeout=?)
```
It is not meant to be done casually, so I am not exposing it through a function. You can still change it nonetheless.
