### ISSUE TITLE
Take the input of the user

### ISSUE THREAD

**Issue by Azzeccagarbugli** [nickoala/telepot#209]
Hey people,
I have a problem with my code, I would to take the "second" input of an user, after him has insert in the text box the primary command, but I can't. How can I do?

Thanks for help!

```
def handle(msg):
    content_type, chat_type, chat_id = telepot.glance(msg)

    chat_id = msg['chat']['id']
    command_input = msg['text']

    print(content_type, chat_type, chat_id)

    if command_input == '/help':

        help_text = '''Hey Francesco!'''
        bot.sendMessage(chat_id, help_text)

    elif command_input == '/frazionifica':

        input_numeratore_str = 'Insert the number'

        bot.sendMessage(chat_id, input_numeratore_str)

        input_numeratore = msg['text']  ##MY ERROR IS HERE

        print(input_numeratore)
        print("Hello")

bot = telepot.Bot('XXXX')
bot.message_loop(handle)

print('Sto ascoltando la tua voce...')

while 1:
    time.sleep(10)
```

**Comment by nickoala** [comment]
For that, you need to maintain a *state* indicating which step the user is at. This usually means an extra variable:

```python
step = 1

def handle(msg):
    if step == 1:
        if received the first answer:
            step = 2
        else:
            reply with an error message, step stays at 1
    elif step == 2:
        look for the second answer
```

You need to be careful thinking through the state transitions, but that's the basic idea.

**Comment by Fast0n** [comment]
step = 1
def comand(msg):
    content_type, chat_type, chat_id = telepot.glance(msg)
    chat_id = msg['chat']['id']
    command_input = msg['text']

    global step

    if step == 1 and command_input == '/help':
        bot.sendMessage(chat_id, 'Step = 1')
        step += 1

    if command_input == '/nome' and step == 2:
        bot.sendMessage(chat_id, "Step = 2")
        step = 1
