### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by Garmahis666** [nickoala/telepot#21]
It lacks the ability to set up a proxy to connect.

**Comment by nickoala** [comment]
Do you mean having a simple HTTP server to test webhook?

**Comment by Garmahis666** [comment]
I began to test the robot on a computer connected to the Internet through a proxy. And the request
import telepot
bot = telepot.Bot ('***** PUT YOUR TOKEN HERE *****')
bot.getMe ()
I get the appropriate error.
I looked implementation method.
def getMe (self): 
    r = requests.post (self._methodurl ('getMe'), timeout = self._http_timeout) 
    return self._parse (r)
The simplest thing you can do is write:
def getMe (self): 
    r = requests.post (self._methodurl ('getMe'), timeout = self._http_timeout, proxies = urllib.request.getproxies ()) 
    return self._parse (r)
so we work at least take those proxy settings that are registered in the system.

**Comment by ravxl** [comment]
never needed a proxy to it, but have you tested to set your env proxy
settings?

export http_proxy=http://proxy.vort.se:8080
export https_proxy=http://username:password@proxy.incolume.com.br:8080

**Comment by nickoala** [comment]
Yes, telepot lacks the ability to set proxies on requests.post().

According to requests' [documentations](http://docs.python-requests.org/en/latest/user/advanced/#proxies), you may achieve the same effect by:

```
$ export HTTP_PROXY="http://10.10.1.10:3128"
$ export HTTPS_PROXY="http://10.10.1.10:1080"
```

I may consider adding that configuration to some future release.

**Comment by nickoala** [comment]
After a night sleeping on it, I have decided not to add proxy configuration to telepot. It's rather ad-hoc, and can be gotten around quite trivially.

**Comment by Garmahis666** [comment]
I figured out the problem was really in my code. Everything works fine. Many thanks!
