### ISSUE TITLE
Best way to differenciate two types of users

### ISSUE THREAD

**Issue by polmp** [nickoala/telepot#210]
Hi to everyone!

First thanks for your help! I have the following doubt: what's the best way to differenciate two types of users? The only way I thought is having a list of userid for a specific type of user and check that list.

¿Can I create two class of DelegateBot and redireccionate all the messages of one type of user and use the other class for the others?
Thanks in advance!

**Comment by nickoala** [comment]
Except for the id, first name, last name, and username, I don't think you can get anything more specific about a user. This is reasonable, because anything more than that may entails privacy concerns.

**Comment by polmp** [comment]
Hi nickoala!

I mean what's the best way of progamming this. Doing two classes of delegate bot and redireccionate the messages of each class depending of the type of user? And not doing a list of userid and check that list

**Comment by polmp** [comment]
Solved my doubt with an example.
