### ISSUE TITLE
lack of method to properly stop the message_loop ?

### ISSUE THREAD

**Issue by sander76** [nickoala/telepot#212]
Writing a plugin for home assistant using telepot. https://home-assistant.io/

For this I use the `message_loop` method. But I cannot seem to find a method or signal which is able to nicely close the thread and scheduler.

Is there such a method available ?

**Comment by nickoala** [comment]
Sorry, there is no method or signal to stop the `message_loop` thread. You will have to stop the process with a shell script or something.
