### ISSUE TITLE
How to Answer Inline Keyboard Markup Choose on same Message

### ISSUE THREAD

**Issue by mojsho** [nickoala/telepot#213]
I wonder if possible to answer callback not in new message? I mean remove old message and alternate new message. Like such _BotFather_ does on `/mybots` command.
For more understanding my question, I need a property like `one_time_keyboard` in `ReplyMarkupKeyboard` in `InlineKeyboardMarkup`.
Thanks.

**Comment by mojsho** [comment]
I finally learned that from [this issue](https://github.com/nickoala/telepot/issues/145).
Thanks @nickoala :+1:

**Comment by zero59** [comment]
hi
this is my question too
@nickoala

**Comment by zero59** [comment]
@mojsho اقا اگر زحمتی نیست یه راهنمایی بکن مرسی

**Comment by zero59** [comment]
I learned too :))
1)send1= bot.sendMessage(chat_id, 'text', reply_markup=keyboard)
2)bot.editMessageText(telepot.message_identifier(send1),'new text',reply_markup=None)
