### ISSUE TITLE
ImportError: No module named 'telepot.async'

### ISSUE THREAD

**Issue by RYNEQ** [nickoala/telepot#216]
I'm trying to run [this](https://github.com/bmagyarkuti/inlinelatex) code on Ubuntu 16.04 but it can't find 'telepot.async' !
I installed telepot with:
`sudo pip3 install telepot`
But, when I try to run the script, I'm receiving:

```
Traceback (most recent call last):
  File "inlinetexbot.py", line 15, in <module>
    import telepot.async
ImportError: No module named 'telepot.async'  
```
`telepot.async` is not installed with `telepot` ? 
What is the problem?

**Comment by cooox** [comment]
See changelog [version 8.2](https://github.com/nickoala/telepot/blob/master/CHANGELOG.md#82-2016-07-04) (please note, current version is at 10.4!).
> Changed async version to telepot.aio to avoid collision with async keyword

The last update to your linked script is way too old, it's from February 2016! Therefore the new import `telepot.aio` is not correctly used even though the package from pip is valid. You could fetch the matching version from pypi, but the changes in Telegram API might break functionality.
