### ISSUE TITLE
I cant send bot.sendMessage(parse_mode='HTML', chat_id=********, text='<b>test</b>')

### ISSUE THREAD

**Issue by enginenode** [nickoala/telepot#218]
@nickoala Can you help me?
I have this code but  it doesnt works.
bot.sendMessage(parse_mode='HTML', chat_id=********, text='<b>test</b>')

error:

TypeError: Cannot create property 'chat_id' on string <b>test</b>

help me please.

**Comment by nickoala** [comment]
I tried both of the following, and both of them worked:
```python
bot.sendMessage(parse_mode='HTML', chat_id=******, text='<b>test</b>')
bot.sendMessage(******, '<b>test</b>', parse_mode='HTML')

```
