### ISSUE TITLE
Scheduling

### ISSUE THREAD

**Issue by jenkokov** [nickoala/telepot#22]
It is complicated to add periodic task to bot, when bot running message loop. 
Did you think about add possibility of scheduling tasks? 
Like "every day at 10:00 send a message to ... "
A config may be like django-celery (http://docs.celeryproject.org/en/latest/userguide/periodic-tasks.html) or something like that is good enough i think. 
Or maybe you can took me advise how to make it? 
P.S. Sorry about writing this question to "Issues" but i really can't found any information about this.

**Comment by nickoala** [comment]
It's OK. Issue or non-issue, I just try to help.

Periodic tasks can be easily implemented with threads or tasks (asyncio). It is a general programming technique and not a telegram-bot-specific thing. And I don't see telepot as such a "big" framework to encompass those non-core, albeit sometimes useful, features.

Sorry, there will not be scheduling in telepot.

**Comment by jenkokov** [comment]
Ok. Thank you. Issue can be closed i think
