### ISSUE TITLE
send img to telepot

### ISSUE THREAD

**Issue by sky7176** [nickoala/telepot#221]
First time: very good job.

I try to send a img from my telgram client to my bot, but in response not find a img path, sometime yes sometime no.

This a simple of response:
{u'date': 1489848670, u'document': {u'file_name': u'babbo_Natale_2.jpg', u'file_size': 9469, u'thumb': {u'height': 78, u'file_path': u'thumbnails/file_7.jpg', u'width': 90, u'file_id': u'AAQEABPiAqAZAASw_R0UWnVUo0h0AAIC', u'file_size': 3125}, u'mime_type': u'image/jpeg', u'file_id': u'BQADBAADGwAD_GxxUlx5rA4wHb3PAg'}, u'from': {u'username': u'****', u'first_name': u'****', u'last_name': u'****', u'id': ****}, u'message_id': 1949, u'chat': {u'username': u'****', u'first_name': u'****', u'last_name': u'****', u'type': u'private', u'id': ****}}

{u'date': 1489848749, u'document': {u'file_name': u'codogno.jpg', u'file_size': 210031, u'thumb': {u'height': 67, u'file_path': u'thumbnails/file_11.jpg', u'width': 90, u'file_id': u'AAQEABM-I6kZAASjTRybU7OetWUwAAIC', u'file_size': 1644}, u'mime_type': u'image/jpeg', u'file_id': u'BQADBAADHQAD_GxxUqsCy2AG8aq2Ag'}, u'from': {u'username': u'****', u'first_name': u'****', u'last_name': u'****', u'id': ****}, u'message_id': 1951, u'chat': {u'username': u'****', u'first_name': u'****', u'last_name': u'****', u'type': u'private', u'id': ****}}

{u'from': {u'username': u'****', u'first_name': u'****', u'last_name': u'****', u'id': ****}, u'caption': u'fffff', u'chat': {u'username': u'****', u'first_name': u'****', u'last_name': u'****', u'type': u'private', u'id': ****}, u'date': 1489848856, u'document': {u'file_name': u'codogno.jpg', u'file_size': 210031, u'thumb': {u'height': 67, u'file_path': u'thumbnails/file_11.jpg', u'width': 90, u'file_id': u'AAQEABM-I6kZAASjTRybU7OetWUwAAIC', u'file_size': 1644}, u'mime_type': u'image/jpeg', u'file_id': u'BQADBAADHwAD_GxxUtDYb3YeaRdFAg'}, u'message_id': 1952}

I use this code:
import time
import telepot

def handle(msg):
    chat_id=msg['chat']['id']
    #command=msg['text']
    sender = msg['from']['id']
    print msg

TelegramToken='********'

bot =telepot.Bot(TelegramToken)
bot.message_loop(handle)
print 'In attesa ...'

while 1:
    time.sleep(10)

Where I wrong?

**Comment by mefuckin** [comment]
Update should not contain a path to image file, but it contains a file id. Use [getFile](https://core.telegram.org/bots/api#getfile) method to retrieve a file path by id.

**Comment by sky7176** [comment]
Many thanks

Il 18/mar/2017 17:02, "Andrey Mishakin" <notifications@github.com> ha
scritto:
