### ISSUE TITLE
restarting the bot via trigger-command, trigger command not marked read on restart, results in loop

### ISSUE THREAD

**Issue by nakami** [nickoala/telepot#222]
i implemented a "/restart" trigger. my goal is to make changes to my code and let the bot restart itself via telegram message.
if triggered this gets called:
```python
def restart_me():
    python = sys.executable
    bot.sendMessage(my_chat_id, "```\nrestarting...\n```", parse_mode="Markdown")
    os.execl(python, python, * sys.argv)
    return 0
```
in the console i notice the expecting result at first, the bot receives the message and starts a new instance. however, the first message the bot gets is the last message **again** - therefore, it keeps restarting itself in a loop. it seems like the last message wasn't marked read by telepot. any ideas on an approach on this?

```zsh
 $ python3 -V
Python 3.4.2
 $ pip3 show telepot
[...]
Name: telepot
Version: 10.5
```

**Comment by nickoala** [comment]
The "acknowledgement" of received messages is done by the next call to `getUpdates()`. I suspect you didn't give it enough time to make that next call. Try to introduce a delay before executing the restart:
```python
bot.sendMessage(my_chat_id, "```\nrestarting...\n```", parse_mode="Markdown")
time.sleep(2)
os.execl(python, python, * sys.argv)```

**Comment by nakami** [comment]
workes like a charm.
thank you so much!

i assume getUpdates() gets called independently to handle()?
