### ISSUE TITLE
sendPhoto() sometimes takes 2-3 minutes with normal images and good network

### ISSUE THREAD

**Issue by ctrlbru** [nickoala/telepot#223]
I'm using sendPhoto to send some images from a local folder. It usually works but lately it happens that sometimes the call gets stuck for 2-3 minutes and finally sends the image. It does not depend on the image size, I'm using 60kb jpegs, nothing special. It's not connection dependant, that's quite good:

192 packets transmitted, 192 received, 0% packet loss, time 191275ms
rtt min/avg/max/mdev = 6.190/7.273/10.352/0.465 ms

and I'm not spamming too much. I just sent 3 images, then it got stuck for 2.5 mins, then I sent immediately another 13 images without issues.

#107 seems similar.

I just updated to the last telepot version to see if it was a known solved issue, but anyway when I first noticed this I had been using the same old version for months.

Last thing: when this started I was actually sending quite big images and I thought the time was related to the upload time, but after I resized them it's still happening... yes I double checked, I'm really using the resized version :)

**Comment by ritiek** [comment]
Is this still a problem?

I tried with 50 different photos in a single burst, it seems to be working fine.

**Comment by ctrlbru** [comment]
Uhmm no it's not happening anymore. It probably went away between 10.5 and 12.3 but I don't know exactly where.
