### ISSUE TITLE
Support for aiohttp2

### ISSUE THREAD

**Issue by Recursing** [nickoala/telepot#224]
Hello!
Thanks for working on telepot.
I see it has a fixed dependency for aiohttp==1.3, but supporting aiohttp2 doesn't seem too hard.
I think the only differences would be

- replacing `aiohttp.helpers.FormData` with `aiohttp.formdata.FormData`
- using an `aiohttp.ClientSession` for for sending post requests

A trivial way to do the second one would be creating a `ClientSession` and using it in `telepot.aio.api._transform` (replacing `aiohttp.post` with `session.post`), I did some tests and it seems to work.
The only problem might be closing the session

Could we work on a pull request to support aiohttp2?

**Comment by nickoala** [comment]
I need some time to investigate and think about it. Will get back to you in a week. Thanks for the suggestion.

**Comment by Duiesel** [comment]
Hello!
Is there any updates about an issue?
Thanks!

**Comment by AyumuKasuga** [comment]
Hello, I also played with aiohttp2. And everything works great except [this part](https://github.com/nickoala/telepot/blob/master/telepot/aio/hack.py )
This part is not working in aiohttp2 because of import error. So if you send file with space or other symbols which should be encoded -- user receives file name with encoded version of symbols. Could someone fix it?

**Comment by nickoala** [comment]
Sorry for the delay. My original decision to fix the dependency at `aiohttp==1.3` is to free myself from keeping up-to-date with aiohttp. It seems I can avoid it no longer.

Ok, I will bring telepot up to comply with aiohttp2 (and no longer compliant with aiohttp 1.x). I am going to get a semi-vacation from late April to very early May. Expect an update on or before May 10.

Thanks for using telepot.

**Comment by nickoala** [comment]
Telepot is now compliant with aiohttp2!!! (See #234) 

Thanks for raising this issue, and thanks for using telepot.
