### ISSUE TITLE
Connection reset by Peer

### ISSUE THREAD

**Issue by cesco78** [nickoala/telepot#225]
Hello, I've a problem like the Issue #87. I use Raspbian Jessie, Python 2, Telepot 10.5 and urllib3 1.9.1, If I do not interact with my bot over a couple of minute, at the first interaction a I send a command, the operation is executed, but the reply crashes
`Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 781, in collector
    callback(item)
  File "/home/pi/domotica_tucci/tvcc.py", line 192, in handle
    bot.sendMessage(id_chat, messaggio, reply_markup=hide_keyboard)
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 408, in sendMessage
    return self._api_request('sendMessage', _rectify(p))
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 397, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telepot/api.py", line 130, in request
    r = fn(*args, **kwargs)  # `fn` must be thread-safe
  File "/usr/local/lib/python2.7/dist-packages/urllib3/request.py", line 141, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 153, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 529, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1111, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 444, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 400, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 205, in recv
    return self.recv(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 188, in recv
    data = self.connection.recv(*args, **kwargs)
SysCallError: (104, 'Connection reset by peer')`

Following the issue #87 I downgraded the urllib3, but nothing changed

I reinstalled my raspberry after a crash, previous version, installed in Jan 2016 and never touched worked without errors...

Thanks for any help!

Best Regards

**Comment by Too-Naive** [comment]
It seems that this does not seem to happen to me alone. If the robot is idle for some time, this exception will occur.
I try to use this code to solve the problem:
```py
def __sendMessage(self,msgID,msgStr):
	try:
		self.bot.sendMessage(msgID,msgStr)
		except Exception as e:
		errmsg = "An exception of type {0} occured. Arguments:\n{1!r}"
		message = errmsg.format(type(e).__name__, e.args)
			print message
			return False
		return True
def __safeSendMessage(self,msgID,msgStr):
	while not self.__sendMessage(msgID,msgStr):
		time.sleep(0.1)
```
But there is no use.

**Comment by cesco78** [comment]
I tried with this code
```python
def SecureSendMessage(id_usr, msg, mark, keyboard):
       while True:
              try:
                     bot.sendMessage(id_usr, msg, parse_mode=mark, reply_markup=keyboard)
                     break
              except Exception, e:
                     err_code, err_text = e
                     if not((err_code == 104) and (err_text == 'Connection reset by peer')):
                            break

keyboard = {'remove_keyboard': True}
parse = 'Markdown'
message = "Hello"
SecureSendMessage(user_send, message, parse, keyboard)
```

After some testing time I think that it works for me

**Comment by Too-Naive** [comment]
Insert of catch exception, I find a way to keep connection alive:
```py
def __keepAliveThread(self):
	while True:
		self.bot.getMe()
		time.sleep(60)
def keepAlive(self):
	t = threading.Thread(target=self.__keepAliveThread)
	t.daemon = True
	t.start()
```

**Comment by cesco78** [comment]
Great idea! Thak You it works!

**Comment by lucatd4** [comment]
Where did you place the code please?
My script is this:

`bot = telepot.Bot('mytoken')

def handle(msg):
        chat_id = msg['chat']['id']
        text = msg['text']

	print(chat_id)

        if text == '/hello':
                bot.sendMessage(chat_id, 'Ciao Gilbert!')
	elif text == '/ciao':
                bot.sendMessage(chat_id, 'Ciao Luca!')		
        elif text == '/hei':
                bot.sendMessage(chat_id, 'Ciao Joelle!')
        else:
		        bot.sendMessage(chat_id, 'Messaggio non riconosciuto')
bot.message_loop(handle)

while 1:
        time.sleep(500)`

**Comment by cesco78** [comment]
I put the keep alive call (bot.getMe()) in the while 1

**Comment by lucatd4** [comment]
so I take off 
`time.sleep(500)`

**Comment by Too-Naive** [comment]
I change my code from keep alive call `bot.getMe()` to:
```python
while True:
	try:
		self.bot.sendMessage(chat_id, message, **kwargs)
		break
	except telepot.exception.TelegramError as e:
		Log.error('Raise exception: {}',repr(e))
		raise e
	except Exception as e:
		Log.error('Exception {} occurred',e.__name__)
		time.sleep(1) # wait 1 more second to send again
```
It pervert call `getMe()` frequently.

**Comment by Too-Naive** [comment]
Same as yours, but It work for me now.

**Comment by lucatd4** [comment]
The script generate an error:
```
 Traceback (most recent call last):
  File "scriptbot.py", line 25, in <module>
    Log.error('Exception {} occurred',e.__name__)
NameError: name 'Log' is not defined
```
