### ISSUE TITLE
Bot killed after ~48 hrs

### ISSUE THREAD

**Issue by joshquines** [nickoala/telepot#227]
bot would stop running after ~48 hours
"killed" message would appear and nothing else

not quite sure what is causing this as I set it up to run 24/7

**Comment by Blank517** [comment]
I think is not a problem of telepot api but of your server or python

**Comment by tuxskar** [comment]
Usually, this problem is due a memory+swap exhaustion, check this http://stackoverflow.com/a/726762
I'd recommend you to check other applications running on your server to see which one is taking more memory or upgrade the amount of ram in order to avoid this situation.

**Comment by Mahakam20000** [comment]
I had a problem like this, and it wasn't due lack of memory or CPU. I solved using the python's "with" statement  whenever I open a file, instead the open/close structure.
Example
the old: 
open(x)
do something with x (like send it as image)
close(x)

become the new:
with open(x)
        do something with x
