### ISSUE TITLE
Groupchat only working with prefix

### ISSUE THREAD

**Issue by mderksen** [nickoala/telepot#229]
Hello. I hope you can help me. I'm using the latest telepot 10.5.

I want my bot to listen to sended message and search in the message for a specific string without using prefix. When i have a private chat with my bot it works. When i'm using a group chat it doesn't work. 

This is my code for looking for a specific string.

`def handle(msg):
        chat_id = msg['chat']['id']
        command = msg['text']

        if 'somestring' in command:
                send_photo(chat_id, True, 'somestring')
`

In the group chat it replies when sending these messages:
/somestring
/test hello somestring

It doesn't work with:
The weather today is somestring

In a private chat this last example works. How can i get it to work in a group chat? :) 

Thanks in advance

**Comment by das7pad** [comment]
@mderksen The [privacy mode](https://core.telegram.org/bots#privacy-mode) is actived for bots by default.
You need to disable it with the command `/setprivacy` in your chat with `@BotFather`  to let your bot listen to all messages.

**Comment by mderksen** [comment]
Thank you, that fixed it. Didn't know about that.
