### ISSUE TITLE
After a certain period of time it did not receive the message

### ISSUE THREAD

**Issue by acidpop** [nickoala/telepot#23]
sorry, i'm use google translate.

please understand

i'm use telepot from xpenology system.

bot = telepot.DelegatorBot(TOKEN, [
        (per_from_id(), create_open(BotManager.BOTManager, timeout=120)),
    ])

class BOTManager(telepot.helper.UserHandler):
def __init__(self, seed_tuple, timeout):
        super(BOTManager, self).__init__(seed_tuple, timeout)

def on_message(self, msg):
  Message Processing Code...

def on_close(self, exception):
 on_close log write...

def close(code=None, reason=None):
  close log write

After the message was sent three hours after the teapot receive messages all

my source code is here
https://github.com/acidpop/xpebot

thank you~!

**Comment by nickoala** [comment]
Do you mean you receive all the messages 3 hours after they are sent?

**Comment by chustaschus** [comment]
I understand, if he sends some messages now, it does not receive the messages. He will receive the messages after 3 hours.
I think that means

**Comment by acidpop** [comment]
no..

1. telepot start
on_message -> message received success

but, after 3hour

i'm send message to bot

on_message - not received message..

no response

**Comment by chustaschus** [comment]
Ok, sorry
I do not use delegator in this moment, but my bot is in a synology and it works very good. 
I like to congratulate @nickoala  for this framework.

**Comment by nickoala** [comment]
@chustaschus Thank you.

@acidpop Can you somehow capture the program output? If I don't see the error messages, there is no way I can help.

**Comment by acidpop** [comment]
07:30 me -> bot : send message
on_message : message receive

08:30 me -> bot : send message
on_message : message receive

11:30 me -> bot : send message
on_message : no response

**Comment by feranto63** [comment]
I have a similar problem as @acidpop has.
This is an extract of my code:
```def handle(msg):
    
    msg_type, chat_type, chat_id = telepot.glance(msg)

    # ignore non-text message
    if msg_type != 'text':
        return

    command = msg['text'].strip().lower()
    
    if command == '/now':
        bot.sendMessage(chat_id, "command now")
    elif command == '/5m':
        bot.sendMessage(chat_id, "command 5m")
    else:
        bot.sendMessage(chat_id, "unknown command")

...

bot = telepot.Bot(TOKEN)
bot.notifyOnMessage(handle)
logging.info("Listening ...")

while True:
      time.sleep(60)
 ```
In some random conditions (I was not able to reproduce the issue) the program stops to process received message (they remain in the queue).
I have to kill the program and restart it to have received message processed by `handle`

Could you tell if there is any way to awake the thread?
Thank you very much @nickoala , telepot is a great job

**Comment by nickoala** [comment]
Ok, I need some time to figure this out. Thanks for all the feedback.

**Comment by nickoala** [comment]
For anyone who follows, I have set up a **simple bot program**, monitored by **[supervisord](http://supervisord.org/)** to capture any erroneous output, hopefully to get some clues on this. The setup is as follows:

Machine: **Raspberry Pi 2 Model B**
Raspbian: **Wheezy**
Python: **2.7**
telepot: **6.5**
Program: an **echo bot**, which only echoes the text message I have sent

```python
import sys
import time
import telepot

def handle(msg):
    msg_type, chat_type, chat_id = telepot.glance(msg)

    if msg_type != 'text':
        return

    text = msg['text']

    if chat_id != USER_ID:
        return

    bot.sendMessage(chat_id, text)

TOKEN = sys.argv[1]
USER_ID = long(sys.argv[2])

bot = telepot.Bot(TOKEN)
bot.notifyOnMessage(handle)
print 'Listening ...'

while 1:
    time.sleep(1)
```

In supervisord's program section, I have set `autorestart` to `false`, so the program would *not* get re-started after crashing.

As of now, it has been up for **48 hours** and is still receiving and echoing messages as expected. Except for the occasional `ConnectionError` encountered by `getUpdate` requests (which is normal), no other problems is apparent.

Stay tune for updates.

**Comment by nickoala** [comment]
A suggestion to @acidpop : You may also use **[supervisord](http://supervisord.org/)** to run your program to try to find out what the problem is. It can capture stdout and stderr, and it can restart programs that exit unexpectedly.

**Comment by acidpop** [comment]
OK. Test it.

Thank you!! ^^

**Comment by nickoala** [comment]
OK. The echo bot had been running for **nearly 8 days**, and still operated normally. I have stopped it.

To be closer to @acidpop 's original case, I am now running the [counter bot](https://github.com/nickoala/telepot/blob/master/examples/counter.py) example (monitored by supervisord), which uses `DelegatorBot`.

```python
import sys
import telepot
from telepot.delegate import per_chat_id, create_open

class MessageCounter(telepot.helper.ChatHandler):
    def __init__(self, seed_tuple, timeout):
        super(MessageCounter, self).__init__(seed_tuple, timeout)
        self._count = 0

    def on_chat_message(self, msg):
        self._count += 1
        self.sender.sendMessage(self._count)


TOKEN = sys.argv[1]  # get token from command-line

bot = telepot.DelegatorBot(TOKEN, [
    (per_chat_id(), create_open(MessageCounter, timeout=10)),
])
bot.notifyOnMessage(run_forever=True)
```

I will report back for any new developments.

**Comment by davidezanella** [comment]
Using python 3 and not python 2.7 will solve the disconnection of the bot caused by the SSL exception during the getUpdates method, please write this in the readme, cause it made me crazy :)

**Comment by acidpop** [comment]
Telepot 6.5 not yet no problem.

Thank you!
issue close!

**Comment by nickoala** [comment]
Ok, the counter bot (mentioned above) has been running for a little **over 3 days**, and still operates normally. I am stopping it.

Just for record, the two test periods span a total of **11 days**, and show no sign of stoppage in receiving messages. It even survived a period of Telegram server downtime. Once the server was back up, message reception resumed normally again.

I won't investigate this issue further, until more tangible clues emerge.

**Comment by acidpop** [comment]
Traceback (most recent call last):
File "build/bdist.linux-x86_64/egg/telepot/__init__.py", line 348, in get_from_telegram_server 
  result = self.getUpdates(offset=offset, timeout=timeout)
File "build/bdist.linux-x86_64/egg/telepot/__init__.py", line 272, in getUpdates 
  timeout=self._http_timeout+(0 if timeout is None else timeout))
File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 109, in post 
  return request(' post', url, data=data, json=json, **kwargs)
File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 50, in request 
  response = session.request(method=method, url=url, **kwargs)
File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request 
  resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send 
  r = adapter.send(request, **kwargs)
File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 433, in send 
  raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionFool(host='api.telegram.org', port=443): Read timed out. (read timeout=50)


Hi. 

I found yesterday telepot 6.5 Traceback log.

Please review.

is not reconnect try?

**Comment by nickoala** [comment]
It seems the same as **[issue #20](https://github.com/nickoala/telepot/issues/20)**. From my experience, it happens once in a while, and is quite normal.

This is because Telegram servers sometimes take too long to respond to the `getUpdates` request. If the message loop keeps running (that is, you can still receive messages), there is nothing to worry about.

**Comment by acidpop** [comment]
Thanks for your answer!

**Comment by javadfarah** [comment]
hi .ia have sam issue.
my bot have many requests at same time.
i guss when bot have too many requests it stop working.
i have not any error it's just stop responding .
