### ISSUE TITLE
Cpu usage 100%

### ISSUE THREAD

**Issue by siyanew** [nickoala/telepot#231]
when I upgrade telepot ,after about 5hours or more the bots get a lot of cpu usage and response slowly. It happens even on a simple bot ... is there anything wrong with aiohttp or telepot in new version?

**Comment by nylonee** [comment]
I'm also getting this issue on a project that's using telepot: hangoutsbot/hangoutsbot#825

**Comment by nickoala** [comment]
According to changelog, version 10.5's changes are as follows:

## 10.5 (2017-03-02)

- In `message_loop()`, delay longer between HTTP 502 responses
- Handled empty JSON responses (async version)
- Added `quote_fields` parameter to aiohttp hack
- Fixed dependency at `aiohttp==1.3`

They are in response to #205, #203, #214 respectively. By the look of them, the first two are unlikely to causes high CPU usage. The third one .... is harder to say, but impossible to know for certain until further investigation.

I am setting aside some time to work on telepot in a week's time. I will look into the issue. At the meantime, please revert back to an older version if that's what you desire.

**Comment by siyanew** [comment]
I'm not  sure which version I had before but it maybe causes changes from previous version for example 10.4 or ... ?! 🤔

**Comment by nylonee** [comment]
The leak could possibly be related to aio-libs/aiohttp#1667.
The fix however is to upgrade to aiohttp 2.0, which breaks compatibility with telepot

**Comment by siyanew** [comment]
@nylonee yes I think it's related to aiohttp ... @nickoala can you update telepot to make it compatible with aiohttp >= 2.0 ?

**Comment by nickoala** [comment]
Enough people ask me about this in #224 that I am upgrading telepot to comply with aiohttp2. Expect an update on or before May 10. Thanks for using telepot.

**Comment by nickoala** [comment]
Hello, telepot is now compliant with aiohttp2 (#234). 

I have not checked this issue per se. I hope aiohttp2 would fix it. If not, raise it here again. Thanks.

**Comment by siyanew** [comment]
I Updated the bot .Let me test it for two days and I will post the result here.
thanks to update telepot

**Comment by siyanew** [comment]
New version completely resolves this issue, thanks !
