### ISSUE TITLE
Threard and quene for sendMessage?

### ISSUE THREAD

**Issue by urpylka** [nickoala/telepot#233]
Hello, tell me, please. How sendMessage worked? If I understand that is simple api_request without consist quene and second thread? It's correct?

**Comment by nickoala** [comment]
Correct.

**Comment by urpylka** [comment]
Do you have any reasons? Why was this not done yet?

**Comment by nickoala** [comment]
What do you mean? `sendMessage` is there for you to use.

**Comment by urpylka** [comment]
I mean why the queue and the separate thread for sending messages have not been done. Do you have any reasons, why was this not done yet?
