### ISSUE TITLE
Formdata attributeerror

### ISSUE THREAD

**Issue by raku-cat** [nickoala/telepot#235]
I updated to v11 and when I started my bot was spammed with an attribute error, I pinpointed the issue and was able to fix it for myself, don't know how universal it is though. I'm on debian stretch, python3.5, aiohttp2, telepot v11
https://github.com/nickoala/telepot/blob/master/telepot/aio/api.py#L45 is the line in question, I had to change it to 
```
aiottp.FormData()
```
For it to work proper.

**Comment by nickoala** [comment]
Exactly which version of aiohttp are you using? Mine is aiohttp 2.0.7

**Comment by raku-cat** [comment]
Well when I updated it said it was updating it to 2.0.7 and an attempt to install --upgrade says the requirement is already satisfied, aiohttp 2.0.7, easy_install says 2.0.7, but pip freeze says 1.0.5. So this looks to be a problem on my end, I'll close the issue when I get the solution so anyone else with the problem has it too.

**Comment by raku-cat** [comment]
I had a 
```
~/.local/lib/python3.5/
```
With some packages, specifically the old aiohttp one, so I had to move any there that would have been missing and then moved it to lib.bak, looks to have fixed the issue.

**Comment by nickoala** [comment]
You remind me of something though, that aiohttp makes available a lot of classes from the top level. Instead of using `aiohttp.formdata.FormData()`, making it `aiottp.FormData()` will be more robust and less sensitive to module changes. Maybe I will do that in the next update.
