### ISSUE TITLE
DelegatorBot as session controller for MVC

### ISSUE THREAD

**Issue by MelomanCool** [nickoala/telepot#237]
I use MVC design with multiple View classes for my application, so it can be used either as a GUI app, or as a Telegram bot. I am trying to use DelegatorBot to spawn a session per each user.

What I need to do for each session:
* Create View, create Controller using that View
* Redirect user's messages to the created View

Also, each session should have a timeout, so it should also be destroyed properly.

This pushes me to the idea of some in-between class that would handle all that. I imagine that I should use create_open for initialization of that class. But it is hard for me to understand how the class should look like. Maybe I can somehow make use of telepot mixins or helpers?

**Comment by nickoala** [comment]
If you want to spawn a session per user, DelegatorBot is definitely the way to go. However, without knowing more concretely what you want to do, I can't say much more.

You probably don't need to use mixins explicitly. One of [ChatHandler](http://telepot.readthedocs.io/en/latest/reference.html#telepot.helper.ChatHandler) or [UserHandler](http://telepot.readthedocs.io/en/latest/reference.html#telepot.helper.UserHandler) should fit your needs. Exactly how to use them depends on whether you need to handle inline query or callback query or neither. Please study the [introduction](http://telepot.readthedocs.io/) and the [examples](https://github.com/nickoala/telepot/tree/master/examples) for further directions.

**Comment by MelomanCool** [comment]
Thanks, I'll try that!
