### ISSUE TITLE
Error with params.items() if key not in ['self']+more}

### ISSUE THREAD

**Issue by orondanelli** [nickoala/telepot#240]
Hi,

Today when i run my phython script i got this error:

Traceback (most recent call last):
  File "prueba.py", line 1, in <module>
    import telepot
  File "/usr/lib/python2.6/site-packages/telepot/__init__.py", line 234
    return {key: value for key,value in params.items() if key not in ['self']+more}

my script for test:
`import telepot

bot = telepot.Bot('123456789:bbGMRZBNiWBpRR_wGIVfy0jFJRJv9B7G_Vc')
bot.getMe()`

Yesterday i installed elastic search and kibana in the same server.

Could you help me for recorver my telepot?.

Thanks

**Comment by nickoala** [comment]
Can't you just re-install telepot?
