### ISSUE TITLE
Async mode database access

### ISSUE THREAD

**Issue by xen** [nickoala/telepot#246]
Hi @nickoala!

I like your project and trying to play with it recently. Now I'm considering to build some bot on top of telepot, but I need database access for it. Do you have any ideas how I can use something like https://github.com/MagicStack/asyncpg with bot?

**Comment by xen** [comment]
I'v tried this approach:

```
class MyBot(telepot.aio.Bot):
    def __init__(self, token, conf, loop=None):
        super(MyBot, self).__init__(token, loop)
        self.conf = conf
        self.db = None

    async def init_db(self):
        self.db = await init_db(conf, self._loop)  # function return pool instance

bot = MyBot(TOKEN, conf)

# and init db connector before main loop
print("Init db...")
loop.run_until_complete(bot.init_db())
print('Listening...')
loop.run_forever()

```

Now bot instance have database pool instance `bot.db` which can be used to access database. 
Hope it can help others.

**Comment by nickoala** [comment]
Thanks for sharing that!
