### ISSUE TITLE
Deep Linking

### ISSUE THREAD

**Issue by samira4237** [nickoala/telepot#247]
hi
I'm creating a bot for absorb members.The robot in this way act: I send a unique link to my bot users, then users send own unique link to other.by this way other absorb to my bot. I create a Deep Link for bot, and now i want to know who are click on own Deep Links.

**Comment by nickoala** [comment]
Hello, regarding deep linking, please refer to my [explanation](https://github.com/nickoala/telepot/tree/master/examples/deeplinking) and Telegram's [introduction](https://core.telegram.org/bots#deep-linking). They should be enough to get you started.
