### ISSUE TITLE
Forced event call

### ISSUE THREAD

**Issue by Duiesel** [nickoala/telepot#248]
Hello, Thanks for Your great work.
I'm using DelegatorBot class to handle all events from getUpdates or webhook.
Some times I need to stop event handling (in my class) and then on next event I need to call previous one using saved msg from stopped event.
For that purpose I'm using `DelegatorBot.handle` method.
To init the Delegator I'm using this 
`bot = telepot.aio.DelegatorBot(token=settings.TOKEN,
                                   delegation_patterns=[
                                    include_callback_query_chat_id(pave_event_space())(
                                     per_chat_id(),
                                     create_open,
                                     MyBotClass,
                                     timeout=10),
                                    ],
                                    loop=loop)`

When I need to call previous event(on_chat_message or on_callback_query) I'm using this 
`if event_type == 'chat':
            bot.handle(msg=message)
        elif event_type == 'callback_query':
            message['id'] = query_id
            bot.handle(msg=message)`

Is it proper way?
And if not what can I use for that purpose?

Many Thanks!
Best Regards,
Alan

**Comment by nickoala** [comment]
Hi Alan, let me first make sure I understand what you are trying to do. You want to manually invoke the bot to handle a message, like it has just received that message, right?

If so, then calling `bot.handle()` seems sensible to me. It is the default "point of contact" for every message received, if you have not provided your own message handling function. It should not cause any bad side-effect, as far as I can see. Give it a try.
