### ISSUE TITLE
Strange problem in "last_name" field

### ISSUE THREAD

**Issue by cesco78** [nickoala/telepot#25]
Hi,
I use this framework and I'm very happy :) but today, after some weeks of perfect works, my bot hangs when I try to record [from].[last_name].
The line 
`lastname_user = msg['from']['last_name']`
raise an exception:
`Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 379, in handle
    callback(update['message'])
  File "tvcc.py", line 101, in handle
    lastname_user = msg['from']['last_name']
KeyError: 'last_name'`

Before today, same code worked correctly.

Anything changed in API or telepot?

Thanks! :)

**Comment by chustaschus** [comment]
Hello. That field is working for me. I think the problem is in other place

**Comment by cesco78** [comment]
I found the problem! The user who sent the message have the surname not set, I think that is necessary to set a try for every field in message

**Comment by nickoala** [comment]
Correct. You should always refer to [Bot API's doc](https://core.telegram.org/bots/api#available-types) and pay attention to which fields are optional. Before accessing optional fields, you should always check `if 'field' in message`, or use a `try` block catching a `KeyError`.

Alternatively, you may use [`telepot.namedtuple.namedtuple()` function](https://github.com/nickoala/telepot/blob/master/REFERENCE.md#telepot-namedtuple) to turn the dict into a namedtuple. In this case, all fields are guaranteed to be present; those absent from the dict will have a value of `None`. Depending on your application, this way of accessing fields may be more convenient, especially if you need to access many optional fields. (But then, you may still have to check for `None`. Again, that depends on your application.)

**Comment by cesco78** [comment]
Thanks! I'll move with "if 'fiedl' in"
