### ISSUE TITLE
Avoid fetching of previous messages while bot is down

### ISSUE THREAD

**Issue by UpsetPelican** [nickoala/telepot#252]
Is there a way to prevent the bot from reading or making it disregard past messages sent while bot is down?

**Comment by UpsetPelican** [comment]
This is just a nice to have, not an issue at all.

**Comment by nickoala** [comment]
Telepot does not have that feature at this moment. You will have to check the message time yourself, or ignore the first batch of messages on startup :relaxed:

**Comment by das7pad** [comment]
You could fetch the last updates with no specified offset and once again using the last updateid from the received updates.
async: ``await bot.getUpdates(offset=(await bot.getUpdates())[-1]['update_id'])``
synced: ``bot.getUpdates(offset=(bot.getUpdates())[-1]['update_id'])``
This code requires previous updates that are not confirmed to be received. So I would wrap this into a try/except block.

**Comment by UpsetPelican** [comment]
Thanks @nickoala!
Interesting workaround @das7pad I'll try that out, thank you!

I'll mark this as closed.
