### ISSUE TITLE
Offset on galance

### ISSUE THREAD

**Issue by Disinterpreter** [nickoala/telepot#26]
Galance don't accept 4 argument in inline? (offset) https://core.telegram.org/bots/api#inlinequery
`query_id, from_id, query_string, query_offset = telepot.glance(msg, flavor='inline_query')
ValueError: not enough values to unpack (expected 4, got 3)`

**Comment by nickoala** [comment]
You forgot to take a "long" glance:

```python
query_id, from_id, query_string, query_offset = telepot.glance(msg, 
                                                               flavor='inline_query',
                                                               long=True)
```

**Comment by Disinterpreter** [comment]
thanks)
