### ISSUE TITLE
 How can I get information from the user? 

### ISSUE THREAD

**Issue by xFraz** [nickoala/telepot#265]
For example, the bot sends "Send me your name", "Send me your last name" and saves this data in two variables.  Sorry for this stupid question.

**Comment by samira4237** [comment]
Its my question too.thank you for your question

**Comment by nickoala** [comment]
Well, it's not a stupid question, but a *lazy* question. Have you gone through telepot's [introduction](http://telepot.readthedocs.io/en/latest/)? Have you gone through Python basics?

**Comment by samira4237** [comment]
thank you, I didn't find any example that use this.
"the bot sends "Send me your name", "Send me your last name" and saves this data in two variables"
