### ISSUE TITLE
run python script telegram bot with webhook

### ISSUE THREAD

**Issue by samira4237** [nickoala/telepot#266]
I'm writing a telegram bot by python telepot package.I used getupdate method, so I want to use webhook method ,how can i do it?
I can set webhook another  script that is very simple on my host, but i dont know how convert getupdate to webhook.i use telepot.

**Comment by nickoala** [comment]
For webhook usage, please refer to the [webhook examples](https://github.com/nickoala/telepot/tree/master/examples/webhook).

Simply put, instead of using `MessageLoop`, you use `OrderedWebhook`:
```python
from telepot.loop import OrderedWebhook

def handle(msg):
    # ......

bot = telepot.Bot(TOKEN)
webhook = OrderedWebhook(bot, handle)

webhook.run_as_thread()
```

And then, you have to make the webserver, on receiving some HTTP requests, feed data to the `OrderedWebhook` object. Using flask as an example, you may do something like this:
```python
from flask import Flask, request

app = Flask(__name__)

@app.route('/webhook_path', methods=['GET', 'POST'])
def pass_update():
    webhook.feed(request.data)
    return 'OK'
```

Good luck.

**Comment by samira4237** [comment]
thank you, is there another way?my server doesn't support flask.

**Comment by nickoala** [comment]
My example illustrates the principle. It's your job to find a way do that in your own webserver.

**Comment by samira4237** [comment]
yes, thank you.you are all right
 

    On Thursday, July 20, 2017 12:40 PM, Nick Lee <notifications@github.com> wrote:
 

 My example illustrates the principle. It's your job to find a way do that in your own webserver.—

**Comment by samira4237** [comment]
Hello I need your help please guide me.first I have to thanks to your good example in github about telepot.I write a script that wich i use telepot and handle(msg). I want to set web hook for it , you already told me i have to use flask and orderwebhook in my script to set webhook,my server doesnt support flask and I dont have another way to set webhook for my script.please help me to set webhook on my telegram bot.thank you.

**Comment by nickoala** [comment]
So, which webserver are you using?

**Comment by samira4237** [comment]
I use heliohost.org site as my web server.
 

    On Sunday, July 23, 2017 3:55 PM, Nick Lee <notifications@github.com> wrote:
 

 So, which webserver are you using?—

**Comment by Duiesel** [comment]
Hello, I can't understand the right way to send certificate with setWebhook method.
Many Thanks!
