### ISSUE TITLE
_asdict() issue with python 3.3.5

### ISSUE THREAD

**Issue by bwess** [nickoala/telepot#269]
Just FYI: The python 3 that came with my Linux distribution calls itself 3.3.5, but as I had to painfully find out it also has the broken _asdict() issue. I had to change telepot/namedtuple.py:72 to 3,3 to get telepot to handle inline keyboards correctly.

**Comment by nickoala** [comment]
Can you upgrade to at least Python 3.5? I probably should say it explicitly somewhere, but I am only prepared to support Python 3.5 and higher.

**Comment by bwess** [comment]
Not on this server, but I fixed it for me. I'm just saying that the version distinction you put in namedtuple.py is doing the wrong thing for some versions, but I can't easily test either on which side each minor version of python 3.3 is.
