### ISSUE TITLE
How to send a message to user that you only know his/her telephone number?

### ISSUE THREAD

**Issue by pvieytes** [nickoala/telepot#27]
Hi,
I'm sorry but I don't know if this is the best place to write this message.

But I can't figure out how to send a message to a user if you only know his/her telephone number.

Thanks in advance

**Comment by jonaskpb** [comment]
This is not possible I think, since the Telegram Bot API only allows you to answer requests of users after the user has initiated a conversation with the bot. Otherwise spam bots would be a problem. Once a user initiates a conversation, you get the user_id.

**Comment by nickoala** [comment]
@jonaskpb is correct. There is no correlation between user id and telephone number. You cannot send messages to someone by knowing his phone number alone. The closest thing I can think of is [deep linking](https://github.com/nickoala/telepot#deep-linking), where you can associate a website user with a Telegram user id.
