### ISSUE TITLE
how to use markdown style in telepot?

### ISSUE THREAD

**Issue by zero59** [nickoala/telepot#270]
how can use markdown style in telepot?
I did not find any guidance here : 
http://telepot.readthedocs.io/en/latest/reference.html

**Comment by zero59** [comment]
bot.sendMessage(chat_id, "this is sample [text](www.test.com)",parse_mode= 'Markdown')

**Comment by das7pad** [comment]
Take a look at the Telegram Bot API Documentation for more details on message formatting: https://core.telegram.org/bots/api#formatting-options
