### ISSUE TITLE
Call a second Inline keyboard 

### ISSUE THREAD

**Issue by DavidePajot** [nickoala/telepot#272]
How to call a second inline keyboard when i press the first inline keyboard button?

**Comment by das7pad** [comment]
Have you tried to delete the first keyboard and post the second one for the same message?

**Comment by DavidePajot** [comment]
You could give me an example, I tried to see the example of the quiz but I do not understand much?

Sorry for my English but I'm Italian

**Comment by garciaw** [comment]
Just edit the message sending the new keyboard in `reply_markup`, you don't even have to delete the previous keyboard.

If you call [`editMessageText`](http://telepot.readthedocs.io/en/latest/reference.html#telepot.Bot.editMessageText), the keyboard of the message will be replaced by whatever new keyboard you pass to `reply_markup` parameter (including `None`, which will remove the keyboard). Of course, if you don't need to update the text of the message itself, calling [`editMessageReplyMarkup`](http://telepot.readthedocs.io/en/latest/reference.html#telepot.Bot.editMessageReplyMarkup) will also replace the keyboard with whatever you pass to `reply_markup`.

**Comment by DavidePajot** [comment]
Thx garciaw
