### ISSUE TITLE
Error 400 Bad Request IMAGE_PROCESS_FAILED

### ISSUE THREAD

**Issue by YielShelion** [nickoala/telepot#274]
Trying to send a photo via bot by using
`bot.sendPhoto(msg['chat']['id'],open(filepath))`

Got this error on Python 2.7 on Windows 10.
This script works on Python 2.6 on Raspberry Pi 3 though.
```
Traceback (most recent call last):
  File "C:\Python27\lib\telepot\__init__.py", line 1034, in collector
    callback(item)
  File "C:\Users\YielShelion\Desktop\Docs\reipi.py", line 37, in handlemsg
    bot.sendPhoto(msg['chat']['id'],open(filepath))
  File "C:\Python27\lib\telepot\__init__.py", line 483, in sendPhoto
    return self._api_request_with_file('sendPhoto', _rectify(p), 'photo', photo)
  File "C:\Python27\lib\telepot\__init__.py", line 442, in _api_request_with_file
    return self._api_request(method, _rectify(params), files, **kwargs)
  File "C:\Python27\lib\telepot\__init__.py", line 434, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "C:\Python27\lib\telepot\api.py", line 131, in request
    return _parse(r)
  File "C:\Python27\lib\telepot\api.py", line 126, in _parse
    raise exception.TelegramError(description, error_code, data)
TelegramError: (u'Bad Request: IMAGE_PROCESS_FAILED', 400, {u'error_code': 400, u'ok': False, u'description': u'Bad Request: IMAGE_PROCESS_FAILED'})

```

I possibly messed up while installing the libraries like urllib3 but I already tried reinstalled it many times.
Can anyone help me pinpoint the problem? I'm curious as to why this only occurs in Windows PC and not on Raspbian.

**Comment by das7pad** [comment]
@YielShelion Could you give this a try:
Add ``import os`` to the beginning of your script and replace your call to send the image with the following
``bot.sendPhoto(msg['chat']['id'], (os.path.basename(filepath), open(filepath)))``

This addition also sends the filename of your image to the Telegram server and the server may now recognize the image type correctly.

**Comment by ritiek** [comment]
Opening and reading the file in binary mode before sending should work too.

```
bot.sendPhoto(msg['chat']['id'], (open(filepath, "rb")))
```

**Comment by YielShelion** [comment]
@das7pad 
Hello and thanks for helping!
`import os` is already at the beginning and I have tried your solution but still have the same error as before.

@ritiek
IT WORKED! Oh my God, thanks a lot! I was confused for 3 hours for this. Thanks again!

**Comment by asqarov07** [comment]
telepot.exception.TelegramError: (u'Bad Request: wrong file identifier/HTTP URL specified', 400, {u'error_code': 400, u'ok': False, u'description': u'Bad Request: wrong file identifier/HTTP URL specified'})
