### ISSUE TITLE
SendMessage to a channel

### ISSUE THREAD

**Issue by MarS7** [nickoala/telepot#275]
I need to send from a private chat with bot to a provate channel 
what can i do ?
i tried with chat_id='code channel' but i recive a error 'too many values to unpack' 
python3.6 and latest relase of telepot

**Comment by nickoala** [comment]
Please post a short segment of your code. That would be more helpful.

**Comment by MarS7** [comment]
import sys
import time
import telepot
from telepot.loop import MessageLoop

def handle(msg):
    content_type, chat_type, chat_id = telepot.glance(msg)
    print(content_type, chat_type, chat_id)

    if content_type == 'text':
        bot.sendMessage(chat_id, msg['text'])
        bot.forwardMessage(chat_id='@harmonyraid',from_chat_id=chat_id,message_id=msg['text'])


bot = telepot.Bot('token')
MessageLoop(bot, handle).run_as_thread()
print ('Listening ...')

while 1:
    time.sleep(10)

**Comment by MarS7** [comment]
solved
