### ISSUE TITLE
Get message and put it into a string

### ISSUE THREAD

**Issue by ilglere** [nickoala/telepot#276]
HI,
I'm sorry for my bad english and for my inexperience in coding.
(I'm just a sysadmin who never learned how to code :cry:  ).

My target is to get weather of a specific city (i'll send a text to my bot with the name of this city) from my bot with OpenWeatherMap API.

This is what I'm trying to do with my bot:
- user: send command '/weather'
- bot: send message 'Write down a city. E.g.: London,uk'
- user: send text 'London,uk'
- bot: get this text and put into a string and than use this string into OpenWeatherMap function.

Is there a way to do this with telepot?

Many thanks!

**Comment by nickoala** [comment]
It's certainly possible to do what you are trying to do. But I am afraid you really should spend some time to learning programming. I can quickly give you a segment of code, but it would be meaningless to you, and you would not be able to modify it if you want something slightly different. Once you get the basics down, writing that piece of code should not be too hard.

**Comment by ilglere** [comment]
I really appreciate your suggestion!
I'll start to learn python seriously.
And sorry for my (noob) question.
