### ISSUE TITLE
could't send a *.wav file

### ISSUE THREAD

**Issue by funknerGER** [nickoala/telepot#28]
Hello,
the command "bot.sendAudio(chat_id, open('dgdg.mp3', 'rb'), title='Ringtone')" can't send a wav- file.
It returns the follow error- message on a RPI.

```
    bot.sendAudio(ChatId, open(sys.argv[2], 'rb'))
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 234, in sendAudio
    return self._sendFile(audio, 'audio', p)
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 226, in _sendFile
    return self._parse(r)
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 177, in _parse
    raise TelegramError(data['description'], data['error_code'])
telepot.TelegramError: (u'[Error]: AUDIO_EXT_INVALID', 400)
```
It is possible to include this issue in the project?

**Comment by nickoala** [comment]
I think the error is saying the file extension being invalid. Make sure the extension is consistent with the content:

```python
bot.sendAudio(chat_id, open('f.wav', 'rb'), title='Ringtone')
```

**Comment by funknerGER** [comment]
@nickoala 
Thank you.
I found my mistake. I forget to insert the third parameter (title='Ringtone').
At mp3 files works it without the third parameter.
