### ISSUE TITLE
conversation with bot

### ISSUE THREAD

**Issue by samira4237** [nickoala/telepot#280]
Hello nickoala
I'm writing my telegram bot , in some part of my script i need to get user information.for example when i send message"what's your name?" i need to get the reply from the user.I used telepot and i send "whats your name?" with sendMessage() method, but i don't know how can i get this message's reply.please guide me.thank you.

**Comment by garciaw** [comment]
The [examples](https://github.com/nickoala/telepot/tree/master/examples) folder has some simple examples dealing with reacting to received messages from the user. [guess.py](https://github.com/nickoala/telepot/blob/master/examples/chat/guess.py) and [diceyclock.py](https://github.com/nickoala/telepot/blob/master/examples/simple/diceyclock.py) are very basic and should give you an idea of how messages are received.

**Comment by samira4237** [comment]
Hello garciaw and thank you for your help.
I have written a very heavy project with telepot and I can not change the package. Will this be possible on my request with the telepot package? If it does not work, I have to change the package. Thanks for your help.
I want to ask you what is your name. The answer I get is to be stored in a variable named first name and when I ask what your last name is stored in another variable named last name.
The response of both variables is in the string, and I want to distinguish between the two.
In Example guess.py, only one question is asked, and it is a given number and the user only needs to give the number, so it's easy to get the answer because it's enough to define it. But what I want is a few questions that answer All of them are in the string, so I wan to link any answer to my specific question. Let's take a look. Thank you.
Meanwhile, I've read all the telepot examples and this request was not available in any of the examples.

**Comment by samira4237** [comment]
this is answer, that i find out today:
import telepot
from telepot.loop import MessageLoop
import time
bot = telepot.Bot('my_token')
def handle(msg):
    content_type, chat_type, chat_id = telepot.glance(msg)
    send1 = bot.sendMessage(chat_id,'whats your name?')
    if send1:
        text1 = msg['text']
        print(text1)


MessageLoop(bot,handle).run_as_thread()
while 1:
    time.sleep(1)

**Comment by garciaw** [comment]
Hi, samira, Telepot is certainly capable of doing what you want.

The examples I showed you teach some basic functionality of receiving messages and how to deal with different commands. If you understand the basic building blocks of an example, you can then use them to build what you want. You will never find an example that perfectly does an entire complex behavior that you have in mind.

Take your time to understand how each piece woks together, in what part of the code a message is sent, in what part a message is received. It also looks like you need to review Python's [control flow](https://en.wikipedia.org/wiki/Control_flow), and have a better view of which part of the example is executed for each message that is received.

**Comment by samira4237** [comment]
Thank you Garcia.yes you are all right.I'm very new in python
