### ISSUE TITLE
Send a notification when user click on a inline button

### ISSUE THREAD

**Issue by EmadHelmi** [nickoala/telepot#281]
in some bots i saw that when you click on a keyboard(both inline or custom keyboards) bot send a notif-like message at the top of the bot or at the center of the chat screen that says accept. how can i do this with telepot?

**Comment by Pella86** [comment]
`answerCallbackQuery(callback_query_id, text=None, show_alert=None, url=None, cache_time=None)`
See: https://core.telegram.org/bots/api#answercallbackquery

This is I think what you look for.
