### ISSUE TITLE
telepot- group

### ISSUE THREAD

**Issue by gabrix27** [nickoala/telepot#283]
Hi, I would like to make a bot that just added to a group sends a message,
how can I do?

**Comment by Murkowk** [comment]
Hi, checking content type new member, if new participant is your bot, you will know it has been added to a group.

**Comment by das7pad** [comment]
As per the [api-changes in may this year](https://core.telegram.org/bots/api-changelog#may-18-2017) `new_chat_member` will be dropped soon, I would rather implement a check on the `new_chat_members` list.

**Comment by Murkowk** [comment]
oh , thanks for advice I will check. currently I just check content to be new chat member but get information from new_chat_participant (so I guess it will still exist)
thanks!
