### ISSUE TITLE
Sender.editMessageText

### ISSUE THREAD

**Issue by fabiocody** [nickoala/telepot#285]
Why isn't there any editMessageText method in the Sender class?

**Comment by nickoala** [comment]
The Sender class helps you send things to a certain `chat_id`. `editMessageText()` aims at a certain *message* (more technically, a *message identifier*). The class **[Editor](http://telepot.readthedocs.io/en/latest/reference.html#telepot.helper.Editor)** helps you target a message and make changes to it. It has what you are looking for.

**Comment by fabiocody** [comment]
Perfect. Is there a way to create an Editor class instance inside a ChatHandler subclass?

**Comment by fabiocody** [comment]
Forget it, I made it. Thanks
