### ISSUE TITLE
Getting the name or username of a user

### ISSUE THREAD

**Issue by codingsett** [nickoala/telepot#286]
I have been able to create bots using this framework easily but lately i have been wondering how do i get the name of user or the username.I have gone through the documentation and i cant seem to find how i can do that?I know this is a minimal issue but i would really appreciate if anyone could help me out on this

**Comment by das7pad** [comment]
Every Message contains a [User](https://core.telegram.org/bots/api#user) object which has the users first/last name and - if set - a username as well.

**Comment by codingsett** [comment]
I have been able to do it thanks a lot
