### ISSUE TITLE
ModuleNotFoundError: No module named 'telepot.loop.MessageLoop'; 'telepot.loop' is not a package

### ISSUE THREAD

**Issue by MaxMatti** [nickoala/telepot#289]
The error (see title) occurs when trying to run my program.

My file:

	#!/usr/bin/env python3
	# -*- encoding: utf-8 -*-
	#[...]
	import telepot, telepot.loop.MessageLoop
	#[...]

When I try to run it this output appears:

    Traceback (most recent call last):
      File "./telegram-bot.py", line 9, in <module>
        import telepot, telepot.loop.MessageLoop
    ModuleNotFoundError: No module named 'telepot.loop.MessageLoop'; 'telepot.loop' is not a package

When I remove `, telepot.loop.MessageLoop` from the import and run it this output appears:

    Traceback (most recent call last):
      File "./telegram-bot.py", line 185, in <module>
        main()
      File "./telegram-bot.py", line 181, in main
        loop = telepot.loop.MessageLoop(bot, {"chat":handleMsg,"edited_chat":handleEdit,"callback_query":handleQuery})
    AttributeError: module 'telepot' has no attribute 'loop'

My software versions:
Python 3.6.2
telepot 12.2
urllib3 1.22
aiohttp 2.2.5
yarl 0.12.0
multidict 3.1.3
chardet 3.0.4
async-timeout 1.3.0

How do I use the new `MessageLoop`? The docs say I should use it instead of the old `mesage_loop` function because that one is deprecated.

**Comment by res0nance** [comment]
`import telepot.loop
telepot.loop.MessageLoop(...)`

This should work

**Comment by das7pad** [comment]
`loop` is a **_module_** of the **_package_** `telepot` and `MessageLoop` is a **_class_** in `telepot.loop`.
```python
import telepot.loop
my_loop = telepot.loop.Messageloop()
```

**Comment by MaxMatti** [comment]
This solved my issue. Thank you.
