### ISSUE TITLE
Error on CounterBot

### ISSUE THREAD

**Issue by AlejandroC90** [nickoala/telepot#29]
I'm trying to test the counter bot but I only get:

"ERROR:root:on_close() called due to NotImplementedError: "

when I send a message.
I don't know what is wrong, I just copied the code and put my Token there.

**Comment by nickoala** [comment]
I could not reproduce the error.

Which message counter example did you try? What command did you use to run it?

**Comment by AlejandroC90** [comment]
Well, I wanted to try the counter bot. So I copied the code:

`import sys`
`import telepot`
`from telepot.delegate import per_chat_id, create_open`


`class MessageCounter(telepot.helper.ChatHandler):`
    `def __init__(self, seed_tuple, timeout):
        super(MessageCounter, self).__init__(seed_tuple, timeout)
        self._count = 0`

    `def on_chat_message(self, msg):
        self._count += 1
        self.sender.sendMessage(self._count)`


`TOKEN = 'I put my token here just like this'`

`bot = telepot.DelegatorBot(TOKEN, [
    (per_chat_id(), create_open(MessageCounter, timeout=10)),
])`
`bot.notifyOnMessage(run_forever=True)`

and run it with:  python mybot.py
When I send a message to get the count, I just get: "ERROR:root:on_close() called due to NotImplementedError: " in the terminal. Did I miss something?

**Comment by nickoala** [comment]
My email address is: lee1nick@yahoo.ca

Please send your python source file to me as an **attachment**. That way I can better diagnose your problem.

**Comment by nickoala** [comment]
Thanks. I run the code without problem. I suspect it's because you have not updated telepot to the latest version, 6.5.

`pip install telepot --upgrade`
or
`easy_install --upgrade telepot`

**Comment by AlejandroC90** [comment]
Yes!, well... Thank you!
next time, before asking something I will update first for sure.
Thank you again.

**Comment by nickoala** [comment]
Actually, I should have thought about reminding you to upgrade sooner. :smile:

**Comment by AlejandroC90** [comment]
jaja, Well...
Thank you, my problem is solved after all. 
:)
