### ISSUE TITLE
Callback Data Problem

### ISSUE THREAD

**Issue by magribenson** [nickoala/telepot#293]
When I do something like this:

InlineKeyboardMarkup(inline_keyboard=[
					[InlineKeyboardButton(text='Lo último', callback_data='/addfeed http://estaticos.elmundo.es/elmundo/rss/portada.xml')]
 ])
it works, but when I change, "portada" in the url above and I write "internacional", it doesn't work. 
Looks like magic.

 File "/usr/local/lib/python2.7/dist-packages/telepot/api.py", line 126, in _parse
    raise exception.TelegramError(description, error_code, data)
TelegramError: (u'Bad Request: BUTTON_DATA_INVALID', 400, {u'error_code': 400, u'ok': False, u'description': u'Bad Request: BUTTON_DATA_INVALID'})

**Comment by das7pad** [comment]
> Looks like magic.

Actually it is just an API-limit you have reached:

> ## [InlineKeyboardButton](https://core.telegram.org/bots/api#inlinekeyboardbutton) 
> Field | Type | Description 
> -- | -- | -- 
> text | String | Label text on the button 
> callback_data | String | Optional. Data to be sent in a callback query to the bot when button is pressed, 1-64 bytes 


```python
>>> len('/addfeed http://estaticos.elmundo.es/elmundo/rss/portada.xml')
60
>>> len('/addfeed http://estaticos.elmundo.es/elmundo/rss/internacional.xml')
66
```
