### ISSUE TITLE
self.answerer.answer does not have any arguments to answerInlineQuery

### ISSUE THREAD

**Issue by Duiesel** [nickoala/telepot#295]
Hello!
Thanks for Your great work!

I'm trying to use inline mode with Your example.

I can't find any arguments that can be passed to `answerInlineQuery` called inside `self.answerer.answer` for e.g. `cache_time`.

I found only one way: using answerInlineQuery method directly.

Best Regards,
Alan

**Comment by nickoala** [comment]
Looking at the [docs](http://telepot.readthedocs.io/en/latest/reference.html#telepot.helper.Answerer.answer) on the method `Answerer.answer()`, the compute function may return one of the following:

- a list of `InlineQueryResult`
- a tuple whose first element is a list of `InlineQueryResult`, **followed by positional arguments** to be supplied to `answerInlineQuery()`
- a dictionary representing **keyword arguments** to be supplied to `answerInlineQuery()`

So, to pass a `cache_time` to `answerInlineQuery()`, the compute function can return either of these:

- a tuple: `([result1, result2, ...], cache_time)`
- a dictionary: `{'results': [result1, result2, ...], 'cache_time': 999}`

Good luck.

**Comment by Duiesel** [comment]
Oh, God!
Great, thank You!

Could You please improve docstring of `Answerer.answer()` in next releases.
Thanks a lot!
