### ISSUE TITLE
InlineQueryResult

### ISSUE THREAD

**Issue by jefri1375** [nickoala/telepot#298]
hi dear 
why doesn't InlineQueryResultPhoto/video/gif/... work at **inline** mode ?

only **InlineQueryResultArticle** correct ...

**Comment by nickoala** [comment]
Well, `InlineQueryResultPhoto` certainly works for me. Look at the usage [here](https://github.com/nickoala/telepot/blob/617cae29a2a892650007bc0fbd77fc0d598f65f7/examples/simple/skeleton_route.py#L100) and [here](https://github.com/nickoala/telepot/blob/617cae29a2a892650007bc0fbd77fc0d598f65f7/test/test3_inline.py#L54).

**Comment by jefri1375** [comment]
That's Right

Thanks
