### ISSUE TITLE
telepot greeting

### ISSUE THREAD

**Issue by ZaynJarvis** [nickoala/telepot#299]
Could I set a message to be sent only the first time one start the conversation with it?

and could I make the bot process other queries after clicking on the inline keyboard button?

**Comment by das7pad** [comment]
> Could I set a message to be sent only the first time one start the conversation with it?

You could set a reply to the `/start` command.


> and could I make the bot process other queries after clicking on the inline keyboard button?

sure. Take a look at the [example for the `inline` mode](https://github.com/nickoala/telepot/tree/master/examples/inline).

**Comment by ZaynJarvis** [comment]
but what if i want to set it as no matter what the first input is, it replys nice to meet you.


Get Outlook for Android







On Wed, Sep 13, 2017 at 4:39 PM +0800, "das7pad" <notifications@github.com> wrote:













Could I set a message to be sent only the first time one start the conversation with it?



You could set a reply to the /start command.



and could I make the bot process other queries after clicking on the inline keyboard button?



sure. Take a look at the example for the inline mode.

**Comment by das7pad** [comment]
> but what if i want to set it as no matter what the first input is, it replys nice to meet you.

This is your part of the coding.

Please note: `telepot` is a framework for the Telegram-Bot-API, it can not serve you with a complete solution in every usecase. A good start is reading the documentation of both `telepot` and the Telegram-Bot-API.
