### ISSUE TITLE
Get a Normal Message from group

### ISSUE THREAD

**Issue by waterple** [nickoala/telepot#300]
I am making a simple bot with telepot, and I want to get normal message from a group.
This means not like `/help(@id_bot)` like `get order foo`

In JS i can get this msg, but in telepot i cant get a message. How can i get it?

**Comment by waterple** [comment]
Sorry..
I just had to change botfather's  privacy option...

**Comment by nickoala** [comment]
If you can get them in JS, I don't see how you cannot get them in Python/telepot. The thing that affects which messages the bot receives from a group is [privacy mode](https://core.telegram.org/bots#privacy-mode). Check the requirements there.

If you still can't get it working, try to distill the code down to the bare minimum that illustrates the problem and state concretely what you are trying to do. That would be more helpful for anyone trying to help.
