### ISSUE TITLE
kickChatMember with username

### ISSUE THREAD

**Issue by gabrix27** [nickoala/telepot#302]
**kickChatMember with username**

 _it's possible use kickchatmember with
username, if not possible is there a way to use it with username?_

**Comment by das7pad** [comment]
The Telegram-Bot-API does provide only the resolution of a `user_id` -> `username`.

You could cache all `User` objects of users that interact with your bot and do a lookup in your cache then to find the `user_id` for a given `username`. But note that a user can change his/her `username` at any time.
