### ISSUE TITLE
Can't print status

### ISSUE THREAD

**Issue by NeutronS21** [nickoala/telepot#304]
I'm trying to print the https://core.telegram.org/bots/api#chatmember -> status object but I don't see any way...

**Comment by das7pad** [comment]
Would you mind sharing the code part that does not print as expected?

**Comment by NeutronS21** [comment]
status = msg['reply_to_message']['from']['user']['status']
This is my code

**Comment by das7pad** [comment]
You mixed [`User`](https://core.telegram.org/bots/api#user) with [`ChatMember`](https://core.telegram.org/bots/api#chatmember). There is an additional api-request needed to get the data you want:
- a `User` is part of every [`Message`](https://core.telegram.org/bots/api#message) sent into groups/supergroups/private chats
- a `ChatMember` can be received via the method [`getChatMember`](https://core.telegram.org/bots/api#getchatmember)

**Comment by NeutronS21** [comment]
So:
status = msg['reply_to_message']['from']['chat_member']['status']
Should work?

**Comment by das7pad** [comment]
No. As mentioned in my last comment, you have to do an additional api-request to get a `ChatMember`.

```python
user = msg['reply_to_message']['from']
try:
    chat_member = <bot>.getChatMember(user_id=user['id'], chat_id=msg['chat']['id'])
except telepot.TelegramError as err:
    print(repr(err))
    status = None
else:
    status = chat_member['status']
```

**Comment by NeutronS21** [comment]
Thank you! U're awesome :)
