### ISSUE TITLE
Multi - threading

### ISSUE THREAD

**Issue by operiordark** [nickoala/telepot#306]
Hello everyone, i am currently working on a telegram bot for my school's project and i m using telepot. I have a query, does telepot supports multithreading for multi user, or do i have to import some other modules. Also, i would appreciate some advice on how i should tackle this problem of running my bot in parallel instances to cater for multi user. Thank you :)

**Comment by das7pad** [comment]
### Short version
As a very beginner with python and `asyncio` I would start with a normal `telepot.Bot` and move to a `telepot.aio.Bot` if the performance is far lower than expected.
Where _performance_ refers to the interaction with external services such as doing an api-request at  Telegram.

### Long version
Telegram only allows one long-polling request per api-key for `Update`s, which include messages, InlineQuerys, etc. Which is next to the `GIL` of python your main limitation.
You can use [`asyncio`](https://docs.python.org/3.5/library/asyncio.html) and `telepot.aio` to do things in parallel: e.g. receiving and sending data - but be warned: `asyncio` is quite complex and your script can be [_at multiple positions at the same time_](https://docs.python.org/3.5/library/asyncio-task.html#example-chain-coroutines).
That being said the access on other resources may be done with more care, as multiple instances of a message handler could access them.

**Comment by nickoala** [comment]
`DelegatorBot` in the traditional version is using multiple threads to handle multiple users (one thread per user). As a developer, you don't need to manage the threads yourself. Telepot takes care of that for you. If traffic is not too high, this approach is enough. I encourage beginners/students to use the traditional version. Async version is really for advanced developers.

**Comment by operiordark** [comment]
@das7pad @nickoala  I am currently working with the delegator bot and its working nicely. Thank you for your time in crafting these replies! really appreciate it~
