### ISSUE TITLE
How to set proxy for telepot ,I use it in China

### ISSUE THREAD

**Issue by 631068264** [nickoala/telepot#309]
How to set proxy for telepot ,I use it in China

**Comment by das7pad** [comment]
Proxy support is coming soon, see #294.

**Comment by nickoala** [comment]
#294 is only for async version. I am not sure about traditional version (urllib3). But if someone is trying to use it from China, that certainly increases my motivation (I am from Hong Kong) ... no guarantee though.

**Comment by nickoala** [comment]
Now, the newest version 12.4 has proxy support.

Traditional version:
```python
telepot.api.set_proxy('http://........')
telepot.api.set_proxy('http://........', ('username', 'password'))
```

Async version:
```python
telepot.aio.api.set_proxy('http://........')
telepot.aio.api.set_proxy('http://........', ('username', 'password'))
```

Hope it helps you use it from China.
