### ISSUE TITLE
Example 'lover' problem

### ISSUE THREAD

**Issue by zimka** [nickoala/telepot#323]
Hello!
I tried to run 'lover.py' example (no asyncio) and faced some problems.
After my initial message bot is sending inline keyboard, but pressing them is not triggering on_callback_query (I checked it). Waiting circle is rotating at the corner of the button, and then on__idle cancels interaction with bot with relevant message.
This happens for both buttons and timeout increase doesn't influence this behavior.
 I am running [example](https://github.com/nickoala/telepot/blob/master/examples/callback/lover.py) from cl and my token without any changes.

**Comment by nickoala** [comment]
Sorry for the slow reply ...

I have just tried `lover.py` and it works as expected. After an initial message, bot replies with an inline keyboard. I press one of the buttons, and it responds accordingly.
