### ISSUE TITLE
handler function + inline

### ISSUE THREAD

**Issue by mndhkr** [nickoala/telepot#325]
Is there a way to have as the normal handler function as the inline methods?

i.e.: i know this
MessageLoop(bot, handle).run_as_thread()
and this
MessageLoop(bot, {'inline_query': on_inline_query,
                  'chosen_inline_result': on_chosen_inline_result}).run_as_thread()

Is there a way to have both functionalities in the same bot?

Thank you :-)

**Comment by nickoala** [comment]
1. Extend from `telepot.Bot`
2. Implement `on_inline_query(self, msg)` and `on_chosen_inline_result(self, msg)`
3. `MessageLoop(bot).run_as_thread()`

That should do it.
