### ISSUE TITLE
Connecting through a proxy with authentication results in 407

### ISSUE THREAD

**Issue by Vendarr** [nickoala/telepot#327]
When trying to connect through a proxy following error occurs:

```
Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required',))
```

Changing` headers=h` to `proxy_headers=h` in telepot.api.set_proxy works

[https://github.com/shazow/urllib3](https://github.com/shazow/urllib3/commit/267a865cd6d29b0ffe25b544d5d1d172941b24dc)

**Comment by odadev** [comment]
Same problem here. Thanks for that information. Now its working. Hope this error get fixed very soon.
