### ISSUE TITLE
Telepot not working well with multiprocessing.

### ISSUE THREAD

**Issue by jarhill0** [nickoala/telepot#329]
I wrote the following demo script which demonstrates the issue:

https://gist.github.com/jarhill0/811b297770513b8684cc18d2c4d38321

This script uses [multiprocessing](https://docs.python.org/3/library/multiprocessing.html) to process long-running tasks without making the bot hang. What I expect to happen is that when the bot receives a message, it starts a new process where:

- it immediately prints to the console that it is about to sleep
- it sleeps
- it prints to the console that it is about to send a message
- it sends that message _immediately_
- it prints to the console that that message has been sent

This process, due to multiprocessing, would be able to happen for more than one message at once. Instead, what is happening is this: When the bot receives a new message, 

- it immediately prints to the console that it is about to sleep
- it sleeps
- it prints to the console that it is about to send a message
- it sends that message **after some arbitrary delay**
- it prints to the console that that message has been sent

Below is sample output of running that script above. I sent messages of "A," "B," and "C" from my telegram account. The "at [x]" in the output is seconds since an arbitrary but consistent point in time.

```
long_process(329098275, A) sleeping for 4 at 97
long_process(329098275, B) sleeping for 8 at 98
long_process(329098275, C) sleeping for 8 at 98
long_process(329098275, A) sending message at 101
long_process(329098275, B) sending message at 106
long_process(329098275, C) sending message at 106
long_process(329098275, A) sent message at 120
long_process(329098275, C) sent message at 120
long_process(329098275, B) sent message at 120
```

As you can see, there is a 19-second difference between when the script attempts to send a message and when it actually does. I suspect this is caused in some way by the interaction between multiprocessing and telepot.

**Comment by das7pad** [comment]
What are you trying to accomplish with multiple processes?

For concurrent sending you could take a look at `telepot.aio` or `asyncio` in general.

**Comment by jarhill0** [comment]
I was refactoring a bot made with telepot that uses `matplotlib.pyplot` to create graphs based on input. These graphs take a few (<5) seconds to generate, and I was hoping I could make it so the bot would generate these while continuing to respond to new commands.

**Comment by das7pad** [comment]
You could run the heavy calculation in a different thread with `asyncio.run_in_executor`.

**Comment by das7pad** [comment]
I forked your gist, exchanged the print statements with logging and dropped the random delay in favour of an actual calculation. You can compare the sync version to the async one now. There are just a few changes needed.
