### ISSUE TITLE
Can't whitelist some users to use the Bot

### ISSUE THREAD

**Issue by DrumSergio** [nickoala/telepot#33]
As far as I've seen, if you want to use the bot for personal reasons (for example, domotic projects), you can't have a whitelist of users you want to allow talking to the Bot.

Is there any way to do it? I've seen that [here](https://github.com/onedr0p/telegram-sonarr-bot/issues/4) have implemented something similar.

I would like to know how to perform it even if now this functionality is not implemented yet.

Thank you!

**Comment by nickoala** [comment]
You can easily implement this on your own:

```python
def handle(msg):
    content_type, chat_type, chat_id = telepot.glance(msg)

    # Filter away undesirable users
    if chat_id not in whitelist:
        return

    # Do stuff for authorized users

...

bot.notifyOnMessage(handle)
```

For `DelegatorBot`, you may:

```python
bot = telepot.DelegatorBot(TOKEN, [
    # only create handler for whitelisted users
    (per_chat_id_in(whitelist), create_open(CustomHandler, timeout=10)),
])
```

In fact, the examples **[indoor climate monitor](https://github.com/nickoala/telepot#indoor-climate-monitor)** and **[IP Cam](https://github.com/nickoala/telepot#ip-cam-using-telegram-as-ddns)** both use the first technique to ensure they are not used by unauthorized human beings.

**Comment by DrumSergio** [comment]
Thank you! I'm using Delegators, so, how do I refer to that whitelist when you create the `DelegatorBot()`? I am implementing in the __init__ def function, a `self._whitelist`, and refering to it in the on_chat_message as `self._whitelist` also. 

PS. I've made some more questions in the Google mailing list of telepot. Sorry for not being an expert in python, nor in telepot! I would be so thankful if anybody could help me.

**Comment by nickoala** [comment]
I am afraid you have to specify your problem more concretely before I, or anyone, could give any assistance.

**Comment by DrumSergio** [comment]
Ok. Posted in the mailing list! Thank you for your kind help, nickoala!

**Comment by nickoala** [comment]
In case anyone is interested, [here is the link](https://groups.google.com/d/msgid/telepot/515a767d-6d9f-4d71-967d-1352cb2ec958%40googlegroups.com?utm_medium=email&utm_source=footer).

Sergio, try this:

```python
class EMARTINEZBOT(telepot.helper.ChatHandler):
    whitelist = [12345, 123456, 1234567]

    # the rest of class definition

bot = telepot.DelegatorBot(sys.argv[1], [
    (per_chat_id_in(EMARTINEZBOT.whitelist), create_open(EMARTINEZBOT, timeout=60)),
])
```

Summary of changes:

- `whitelist` is moved outside the constructor, so it becomes a *class* variable instead of an *instance* variable. As for their difference, it is outside the scope of this limited space. I encourage you to read up on Python object-oriented programming.
- Use `per_chat_id_in()` instead of `per_chat_id()`
- Single quotes around `sys.argv[1]` were removed

Good luck,

**Comment by nickoala** [comment]
By the way, I think you should get more solid on Python fundamentals before proceeding any further.

**Comment by DrumSergio** [comment]
Thank you for your kind help! I had to modify the app to post it, that's why you may have found the error of the quotes, or other errors that must contain.
Thank for the suggestion on `per_chat_id_in()`, I didn't read anything about that before.
I am currently finishing the 3rd course out of 4 of the Coursera's course of Charles Severance about Python, so that's why I am mistaking so much on objected-oriented programming. But thank you for your effort having helped me! I appreciate it a lot.

**Comment by nickoala** [comment]
The opposite of `per_chat_id_in()` is `per_chat_id_except()` - it starts a handler if `chat_id` is *not* on the whitelist. If you want to reply with a notice to those who is *not* on the whitelist, `per_chat_id_except()` is your choice.

**Comment by a1mo** [comment]
Hi, Nickoala!
`
bot = telepot.aio.DelegatorBot(TOKEN, [
    pave_event_space()(
        per_callback_query_origin(), create_open, SubscribeProcessing, timeout=config.sessionTimeout),
    pave_event_space()(
        per_chat_id_in(s = config.mastersChatIds), create_open, Master, timeout=config.sessionTimeout),
    pave_event_space()(
        per_chat_id_except(s = config.mastersChatIds), create_open, ChatStarter, timeout=config.sessionTimeout),
])
`

If add new values to config.mastersChatIds while the bot is running, it continues to respond to ChatStarter class. How to avoid this?
Thx!
