### ISSUE TITLE
/examples/inline/inline.py not working

### ISSUE THREAD

**Issue by Mambazx** [nickoala/telepot#330]
When I click on inline button `InlineHandler` does not react, that is not called `on_inline_query` and `on_chosen_inline_result`.

**Comment by nickoala** [comment]
I just tried `inline.py` and it works as expected. You type `@WhateverYourBotIs querystring`, it echoes back your query string (meaning `on_inline_query()` is invoked). If you select the option, the chosen inline result is printed on the console (meaning `on_chosen_inline_result()` is invoked).
