### ISSUE TITLE
telepot.helper.ChatHandler and handle function does'nt work 

### ISSUE THREAD

**Issue by aminhyper** [nickoala/telepot#334]
hello
I want to make a project and a section of my project i need to get information from users.
I can get these information with telepot.helper.ChatHandler but when i put my handle function in the cod, it doesnt work.this is my cod:

    import time
    import telepot
    from telepot.loop import MessageLoop
    from telepot.delegate import per_chat_id, create_open, pave_event_space
    import config

    class Messagechat(telepot.helper.ChatHandler):
        QUESTIONS = [
             'whats your name',
            'whats your post address',
  
        ]
        def __init__(self, *args, **kwargs):
            super(Messagechat, self).__init__(*args, **kwargs)
            self._qindex = -1

        def on_chat_message(self, msg):
            if msg['text'] == '/done':
                if 0 <= self._qindex < len(self.QUESTIONS):
                   answer = msg['text']
                   print(answer)
                self._qindex += 1
                if self._qindex < len(self.QUESTIONS):
                    self.sender.sendMessage(self.QUESTIONS[self._qindex])
                else:
                    self.sender.sendMessage('no more question')

    def handle(msg):
        content_type, chat_type, chat_id = telepot.glance(msg)
        if msg['text'] == '/start':
            bot.sendMessage(chat_id,'ok')

    TOKEN = config.token  
    bot = telepot.DelegatorBot(TOKEN, [
        pave_event_space()(
            per_chat_id(), create_open, Messagechat, timeout=30
        ),
    ])
    MessageLoop(bot,handle).run_as_thread()
    print('Listening ...')

    while 1:
        time.sleep(10)

**Comment by aminhyper** [comment]
Hello Nick Lee
Thanks to the good package you provided,This package makes me feel very comfortable and thank you very much
I studied more on the telepot,And I found the answer to my question.
I apologize for the overwhelming question

**Comment by nickoala** [comment]
Good to know that you have solved your own problem. Thanks for lightening my workload :smile:
