### ISSUE TITLE
telepot.exception.BadHTTPResponse when sending a Photo when using Ansyc

### ISSUE THREAD

**Issue by icebergyy** [nickoala/telepot#335]
I keep getting an error with my bot of a BadHTTPResponse when sending a photo with the Async library aio.  I get a 504 Gateway time out.  I can not figure out why there is an error.  Has anyone experienced this problem?

**Comment by nickoala** [comment]
`504 Gateway timeout` likely means that Telegram servers are down. Try again later.

**Comment by icebergyy** [comment]
Do you know of a good way to handle that error?

**Comment by nickoala** [comment]
Sorry, there is really no way to handle that error specifically. It's caught inside `telepot.loop.GetUpdatesLoop` (which is used by `MessageLoop`). But don't worry. The message loop will keep running despite the error.
