### ISSUE TITLE
Problem importing telepot

### ISSUE THREAD

**Issue by andionline** [nickoala/telepot#337]
Hello together,

I tested telepot with a new installed telegram bot with my raspi and python 2.7. Everything works fine.

When I use the python code with python 3.4 I receive the error message 
"ImportError: No module named 'telepot'".

In the documentation I read, that telepot supports python 3.4, so I don't understand what's wrong.

Do you have a tip for me? Is it correct to use telepot with python 3.4?
Let me know, if you need more detailed informations.

![screenshot](https://user-images.githubusercontent.com/33910778/33147428-fcf2b96c-cfc7-11e7-935b-78329eccbf72.PNG)

Best regards,
Andi

**Comment by aminhyper** [comment]
My python is 3.4 and my telepot works finely.

**Comment by andionline** [comment]
Is it possible that the links to the libs are wrong on my Raspi? Maybe they are only acessable for Python 2 and not fpr Python 3?
How can I check this?

**Comment by das7pad** [comment]
`$ python3` and `$ sudo python3` may call different `python` executables and can access different libraries. Try
```
sudo pip3 install telepot
```
if you want to use `telepot` in a script started via `sudo python3`.

**Comment by andionline** [comment]
Thank you das7pad, your hint was successful. Everything works fine now also in python 3.
