### ISSUE TITLE
Can't delete message via callback

### ISSUE THREAD

**Issue by Sithell** [nickoala/telepot#352]
I have handle_callback method that handle callbackQuery objects from InlineKeyboardButton, and delete messages with buttons.
```
def handle_callback(self, callback):
    bot.deleteMessage(callback['message']['message_id'])

```
But I have got this exception:
`telepot.exception.TelegramError: ('Bad Request: chat identifier is not specified', 400, {'description': 'Bad Request: chat identifier is not specified', 'error_code': 400, 'ok': False})`

**Comment by takasurazeem** [comment]
How did you fixit?

**Comment by danieldiasm** [comment]
Yes! How did you fixed?

**Comment by danieldiasm** [comment]
I`ve found out...
First I've extracted the message ID into a tuple inside the main handler and put it into a global tuple
message_id = telepot.message_identifier(msg)_
Then  I've used the instantiated bot to call the method deleteMessage
bot.deleteMessage(last_msg_id)
The method must receive a tuple with those two values...I haven't tested if a list is also valid.

What I did was to read closely the documentation...

Take a close look on these...
https://telepot.readthedocs.io/en/latest/reference.html?highlight=delete#telepot.message_identifier
https://telepot.readthedocs.io/en/latest/reference.html?highlight=delete#telepot.Bot.deleteMessage
https://stackoverflow.com/questions/23944657/typeerror-method-takes-1-positional-argument-but-2-were-given

I hope it help out someone sometime...

I'm not a great programmer, but I try to study as much as I can and solve problems by myself first, take a look on documents helps a lot (as I have a embedded systems background, datasheets help you a lot).
