### ISSUE TITLE
How to get Message by message_id

### ISSUE THREAD

**Issue by jpaczia** [nickoala/telepot#358]
Is there a way to get a message from a specific chat by the message_id?

I want to access a specific message from a bot, but I can not find a way to get it.
The getUpdates() method only returns messages from the user, but none of the bot.

Kind regards

**Comment by codingsett** [comment]
hello try this (the snippet below helps you get the message_id)
`previous=self.sender.sendMessage("Your message")
self.previous = telepot.helper.Editor(self.bot, previous)`

now to edit the message later on ...
`self.previous.editMessageText("Your new message")`

I hope this helps
