### ISSUE TITLE
Pass image from a chat to OpenCV in an easy way.

### ISSUE THREAD

**Issue by ludusrusso** [nickoala/telepot#366]
hi!
I'm working on a project that requires to pass a photo from a chat to opencv. 
I've find a very ugly solution that uses `bot.download_file` to download the image
on a file and then loads the image with `cv2.imread`.

```
        bot.download_file(msg['photo'][-1]['file_id'], 'image.png')
        img = cv2.imread('image.png')
```

Is there a better solution to do it?

Thanks!

**Comment by das7pad** [comment]
You could skip the disk access:
```
raw_img = io.BytesIO()
bot.download_file(..., raw_img)
```
and adapt this snippet: https://stackoverflow.com/a/47389660

**Comment by ludusrusso** [comment]
Tanks you :D
