### ISSUE TITLE
Private bot

### ISSUE THREAD

**Issue by Arky92** [nickoala/telepot#369]
Hi, I want to exclude from my bot all the chat ids different from mine, is there a simple way to do this?
I was also thinking about that, how can I extract an information from a chat id? (like first name)

**Comment by Eyedema** [comment]
Simply log the chat_id when the bot receives a message, then send a message to it. Annotate your chat_id and in your code add something like:

`if chat_id != my_id:
    return`

All messages are constructed as a JSON file, so you can extract everything you need. Try to print the msg you receive (not the text, the whole package) and see if what you need is there.

**Comment by Arky92** [comment]
Thank you very much!
