### ISSUE TITLE
Error 414 while answering inline query

### ISSUE THREAD

**Issue by zumoshi** [nickoala/telepot#37]
Hello,
first thanks for making telepot , it made my work a lot easier.

in \__init__.py:316 [answerInlineQuery function] you send the results to requests.post as `params` rather than post data, therefor its added to the url resulting in a potentially very long url (in my case i have 12 pictures each with up to 200 characters of utf-8 description and a long link) resulting in a 17144 character link!

you can find similar issue with other bot api modules in the following links:
https://github.com/yagop/node-telegram-bot-api/issues/19
https://github.com/irazasyed/telegram-bot-sdk/issues/38

in case it might help here's the [url generated](https://gist.github.com/zumoshi/3c02111faf7fb9f7821c)

stack trace:
```
Traceback (most recent call last):
  File "C:\Users\------\AppData\Local\Programs\Python\Python35\lib\site-packages\telepot\__init__.py", line 164, in _parse
    data = response.json()
  File "C:\Users\------\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\------\AppData\Local\Programs\Python\Python35\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Users\------\AppData\Local\Programs\Python\Python35\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\------\AppData\Local\Programs\Python\Python35\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\------\AppData\Local\Programs\Python\Python35\lib\site-packages\telepot\__init__.py", line 332, in handle
    callback(update['inline_query'])
  File "C:/Users/------/.../main.py", line 27, in handle_telegram
    bot.answerInlineQuery(query_id, articles)
  File "C:\Users\------\AppData\Local\Programs\Python\Python35\lib\site-packages\telepot\__init__.py", line 319, in answerInlineQuery
    return self._parse(r)
  File "C:\Users\------\AppData\Local\Programs\Python\Python35\lib\site-packages\telepot\__init__.py", line 166, in _parse
    raise BadHTTPResponse(response.status_code, response.text)
telepot.exception.BadHTTPResponse: (414, '<html>\r\n<head><title>414 Request-URI Too Large</title></head>\r\n<body bgcolor="white">\r\n<center><h1>414 Request-URI Too Large</h1></center>\r\n<hr><center>nginx/1.6.2</center>\r\n</body>\r\n</html>\r\n')
```

it should be easy to fix , just have to change method of sending data from get to post.

since the bot is currently in production (we missed the issue since it only happens in some cases ...) it would be nice if you could fix it as a priority .

thanks in advance.

**Comment by nickoala** [comment]
Got it, and thanks. Expect a fix within 3 days.

**Comment by nickoala** [comment]
Telepot version is now 6.6. This issue has been fixed.

However, if the results are too long, Telegram servers still return this error:

```
telepot.exception.TelegramError: ('[Error]: Bad Request: RESULTS_TOO_MUCH', 400)
```

I don't know what the limit is though.

As a final note, I am quite embarrassed to say that I had been using POST all along and never *intended* to pass parameters on the URL. The underlying call is `requests.post(...)` but I mistakenly  passed parameters using `params` which embedded the query string in URL. I now use `data` to pass parameters, and the URL is clean. Thanks for bringing this up.

However, as mentioned above, your results still cannot be too big. There is a limit to the size of HTTP requests.

**Comment by nickoala** [comment]
Another note: The fact that results cannot be too big may be why [there is an `offset` field in `InlineQuery` object and a `next_offset` parameter in `answerInlineQuery` method.](https://core.telegram.org/bots/api#inline-mode)

I can certainly see how you may return results "page by page" that way. I haven't tried it myself, so cannot say more.

**Comment by zumoshi** [comment]
thanks for the fast fix , it works flawlessly now.
the limits are way more than i need , there is a limit for answer inline query (50 results per query, i was sending up to 12) , and 200 characters max for `InlineQueryResultPhoto`'s caption.
