### ISSUE TITLE
Inline answer don't show up

### ISSUE THREAD

**Issue by ismtabo** [nickoala/telepot#38]
I am running InlineQueryResult sample but with InlineQueryResultPhoto instead of `article` as shown elow: 
```python
articles = [InlineQueryResultPhoto(id='123', 
    photo_url='http://www.html5rocks.com/en/tutorials/speed/img-compression/len_std.jpg',
    thumb_url='http://www.html5rocks.com/en/tutorials/speed/img-compression/len_std.jpg')
]
```

I've had import `InlineQueryResultPhoto` from `telepot.namedtuple` with:
```python
from telepot.namedtuple import *
```

But when I test it on Telegram Desktop or mobile versions, I can't see the query answers. 
![err-and](https://cloud.githubusercontent.com/assets/9568287/13920463/6e15055a-ef73-11e5-995e-cb84a9c2daa9.jpg)
Desktop view.

![err-desk](https://cloud.githubusercontent.com/assets/9568287/13920464/6e20b2ec-ef73-11e5-9c0b-f6a62b3c7840.png)
On Android version.

Console show this error after timeout is finish:
```sh
$ python inline_sample.py <token>
(49873, ':', 'Inline Query:', u'214204250116192', 49873, u'')
ERROR:root:on_close() called due to WaitTooLong:

```

Image is:
![photo-test](http://www.html5rocks.com/en/tutorials/speed/img-compression/len_std.jpg)

Any idea how can I solved my problem.

**Comment by nickoala** [comment]
Put in `photo_width` and `photo_height`. That should solve the problem.

```python
articles = [InlineQueryResultPhoto(id='123',
    photo_url='http://www.html5rocks.com/en/tutorials/speed/img-compression/len_std.jpg',
    thumb_url='http://www.html5rocks.com/en/tutorials/speed/img-compression/len_std.jpg',
    photo_width=256, photo_height=256)
]
```

My experience is, the width and height don't have to be accurate. They are for the purpose of displaying the results. As long as the two numbers are of the correct proportion, they should be fine. For example, this is good too:

```python
articles = [InlineQueryResultPhoto(id='123',
    photo_url='http://www.html5rocks.com/en/tutorials/speed/img-compression/len_std.jpg',
    thumb_url='http://www.html5rocks.com/en/tutorials/speed/img-compression/len_std.jpg',
    photo_width=1, photo_height=1)
]
```

**Comment by ismtabo** [comment]
Thanks, that works for me. :smile:
