### ISSUE TITLE
Problem daemon tool in MessageLoop

### ISSUE THREAD

**Issue by franalotto94** [nickoala/telepot#380]
Hi  everyone. I want to light and unlight a led connected to my raspberry using a simple telegram BOT.
The communication through Bot and raspberry has to be ensure trough MQTT protocol.
`import sys
import time
import telepot
import random
import datetime
from telepot.namedtuple import ReplyKeyboardMarkup, KeyboardButton
import paho.mqtt.client as PahoMQTT

from telepot.loop import MessageLoop

message = None
class MyPublisher:
	def __init__(self, clientID):
		self.clientID = clientID

		# create an instance of paho.mqtt.client
		self._paho_mqtt = PahoMQTT.Client(self.clientID, False)
		# register the callback
		self._paho_mqtt.on_connect = self.myOnConnect

	def start (self):
		#manage connection to broker
		self._paho_mqtt.connect('iot.eclipse.org', 1883)
		self._paho_mqtt.loop_start()

	def stop (self):
		self._paho_mqtt.loop_stop()
		self._paho_mqtt.disconnect()

	def myPublish(self, topic, message):
		# publish a message with a certain topic
		self. _paho_mqtt.publish(topic, message, 2)

	def myOnConnect (self, paho_mqtt, userdata, flags, rc):
		print ("Connected to message broker with result code: "+str(rc))

def on_chat_message(msg):
    content_type, chat_type, chat_id = telepot.glance(msg)
    print('Chat Message:', content_type, chat_type, chat_id)

    if content_type == 'text':
        if msg['text'] == '/key':

            bot.sendMessage(chat_id, 'testing custom keyboard',
                            reply_markup=ReplyKeyboardMarkup(
                                keyboard=[
                                    [KeyboardButton(text="HIGH")],
                                     [KeyboardButton(text="LOW")]
                                ]
                            ))
    content_type, chat_type, chat_id = telepot.glance(msg)
    print msg['text']
    message= msg['text']

def on_call(msg):
    query_id,from_id,query_data= telepot.glance(msg,flavor='callback_query')
    bot.answerCallbackQuery(query_id,text='CIAO')

if __name__ == "__main__":

    TOKEN = sys.argv[1]  # get token from command-line

    bot = telepot.Bot(TOKEN)
    print('Listening ...')

    test = MyPublisher("MyPublisher")
    test.start()

    while 1:
        for i in range(10):
            MessageLoop(bot).run_as_thread()
            
            time.sleep(1)
        if message=='HIGH':
            test.myPublish ('progettoIOT/paziente1/luci/on', message)
        elif message=='LOW':
            test.myPublish('ProgettoIOT/paziente1/luci/off',message)

test.stop()
`

I don't know how to manage MessageLoop. Everytime I running it I receive error: RuntimeError: cannot set daemon status of active thread . What is the problem? please help me!

**Comment by nickoala** [comment]
Your code is quite problematic:

1. `MessageLoop(bot).run_as_thread()` is being called 10 times
2. `MyPublisher` seems like one of those `*Handler` classes, but it is not a subclass explicitly.
3. `MyPublisher` seems like it should be passed to a `DelegatorBot`, but you are using a basic `Bot`.
4. Do you mean to pass the function `on_chat_message()` to `Bot` simply? Due to bad formatting, I cannot be sure `on_chat_message()` belongs to the top level or to `MyPublisher`.

I think you are taking too big a step. Try to master simpler stuffs before integrating MQTT into your project.

**Comment by franalotto94** [comment]
Thanks for your reply.
At the end I've adjusted  the code as below and all seems working.

> 
import sys
import time
import telepot
import random
import datetime
from telepot.namedtuple import ReplyKeyboardMarkup, KeyboardButton
import paho.mqtt.client as PahoMQTT

from telepot.loop import MessageLoop


message = None
class MyPublisher:
	def __init__(self, clientID):
		self.clientID = clientID

		# create an instance of paho.mqtt.client
		self._paho_mqtt = PahoMQTT.Client(self.clientID, False)
		# register the callback
		self._paho_mqtt.on_connect = self.myOnConnect

	def start (self):
		#manage connection to broker
		self._paho_mqtt.connect('iot.eclipse.org', 1883)
		self._paho_mqtt.loop_start()

	def stop (self):
		self._paho_mqtt.loop_stop()
		self._paho_mqtt.disconnect()

	def myPublish(self, topic, message):
		# publish a message with a certain topic
		self. _paho_mqtt.publish(topic, message, 2)

	def myOnConnect (self, paho_mqtt, userdata, flags, rc):
		print ("Connected to message broker with result code: "+str(rc))




def on_chat_message(msg):
    content_type, chat_type, chat_id = telepot.glance(msg)
    print('Chat Message:', content_type, chat_type, chat_id)

    if content_type == 'text':
        if msg['text'] == '/key':

            bot.sendMessage(chat_id, 'testing custom keyboard',
                            reply_markup=ReplyKeyboardMarkup(
                                keyboard=[
                                    [KeyboardButton(text="HIGH")],
                                     [KeyboardButton(text="LOW")]
                                ]
                            ))
    content_type, chat_type, chat_id = telepot.glance(msg)
    print msg['text']
    message= msg['text']
    if message=='HIGH' or message =='LOW':
        Pubblicainfo(message)
    
    

def Pubblicainfo(message):
    
    if message=='HIGH':
        test.myPublish ('progettoIOT/paziente1/luci/on', message)
        message=None
    elif message=='LOW':
        test.myPublish('progettoIOT/paziente1/luci/off',message)
        message=None
    







if __name__ == "__main__":

    TOKEN = sys.argv[1]  # get token from command-line

    bot = telepot.Bot(TOKEN)
    print('Listening ...')
    test = MyPublisher("MyPublisher")
    while 1:
        try:
            test.start()
            bot.message_loop({'chat': on_chat_message},run_forever=True)
        except KeyboardInterrupt:
            test.stop()
           
       





>
