### ISSUE TITLE
Inlinekeyboard issue only for telegram desktop MAC users

### ISSUE THREAD

**Issue by codingsett** [nickoala/telepot#383]
Hello..i have had this issue with MAC users...whenever they click an inlinekeyboard button on the bot it keeps sending the same data over and over again causing it spam users. This doesnt affect all the other platform clients ..it only happens on MAC(I make bots that receive around 10k users in traffic).
If anyone can help i would be pleased because the code is totally fine.I also logged the buttons being pressed and noticed that it kept on saying that the button has being pressed even when the user is not touching the bot.Thanks!

**Comment by andragui** [comment]
It only happens on few Telegram Desktop version. I have 3.8.2 version and the bot keep sendings the same data. I have also tried in the versions 1.2.6 and 1.2.15 and doesn´t happend.
