### ISSUE TITLE
help for a dummy...

### ISSUE THREAD

**Issue by dany250** [nickoala/telepot#39]
well .. i have no idea on how to send you a msg.. or where ask for help about your project...
so sorry if i made something wrong .. writing this msg as issue!!!!

well.. i dont know anything about python... but i know something of php.. mysql.. and visual basic..
so.. i try to understand as best as i can...

well.. right now .. im not stil able to ANSWER...
for example :
/start
- please select a feature  from A , B, C
... at this point i cant grab the answer... and i cannot find a tutorial on how TO DO THAT...

i tried to do something like that.. but i (obviously) FAILED... 
this is the "amazing" code i tried....
(bad code deleted)
works well till it ask me "dammi un comando".. then when i write "sposta"...
it answers me "Scusa.. mi aspetto un pin numerico..."... That's so sad!!
please help me to understand how to manage this answers!!!!

**Comment by nickoala** [comment]
Hi @dany250 , you have to help me help you. Please look at your own post, and make sure you posted the code correctly. I can't help if your question is so poorly asked.

**Comment by dany250** [comment]
yeah.. i know.. my english sucks! sorry..
so i'm going to try again.
i would like to know, how to receive answers to bot questions.
for example:
 Users send /start...
 bot replies: "Hello and welcome to my services... what's your name?"
 user send " dany"
bot replies: "sorry i didn't catch that"..

i would like to find the way to: ask questions, get and store the answer, make a new question, get another answer... 
but how to do that?

**Comment by ravxl** [comment]
It look likes you should get the basics in python before trying that! Your
question is about coding/developing not about the telepot! :/

**Comment by dany250** [comment]
i just think it's more like.. IS THERE ANY VAR TO GRAB OR..  ID OR SOMETHING ELSE that i can use FROM TELEPOT  to obtain that result?! ... or simply.. can just show me a simple example!?

**Comment by dany250** [comment]
`#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import os
import telepot
import datetime
import time
import httplib2

"""
Ctrl-C per uscire.
"""
 
id_a = [118999303,83415040,175390409,4444444,5555555]
stato = "off"
def handle(msg):
    chat_id = msg['chat']['id']
    command = msg['text']
    sender = msg['from']['id']
 
 
    print 'Got command: %s' % command
    
    if sender in id_a:
    
        if command == '/start':
            global stato
            bot.sendMessage(chat_id, 'Benvenuto in AreaGest_Bot ATTENZIONE! NON USARE LETTERE ACCENTATE!')
            stato = "on"
        elif stato == "off":
            print 'Untente escluso'
            bot.sendMessage (chat_id, '..sei disconnesso.. per incominciare scrivi o TOCCA >>> /start')
        elif command == '/registrami':
            resp, content = httplib2.Http().request("http://nevada2000.altervista.org/testpage.php")
            bot.sendMessage(chat_id, 'Comando eseguito! risposta del server:')
            bot.sendMessage(chat_id, content)
            print 'Ricevuto risposta da server'
            print content
        elif (command == 'Buona serata') or (command == 'Buona giornata'):
                 bot.sendMessage(chat_id, 'Grazie anche a te!')
        elif (command == '/stop') or (command == '/Stop'):
                 bot.sendMessage(chat_id, 'Bot arrestato')
                 stato = "off"
        elif command == '/ciao':
                bot.sendMessage(chat_id, 'Hey, ciao!')
        elif (command == 'Chi sei?') or (command == 'Come ti chiami?' or (command == 'Come ti chiami')):
                 bot.sendMessage(chat_id, 'Sono AreaGest_Bot! .. un bot PRIVATO')
        elif command == 'Ciao' or command == "Ciao!":
                 bot.sendMessage(chat_id, 'Ciao!')
        elif (command == 'Chi e il tuo programmatore?') or (command == 'Chi e il tuo programmatore'):
                 bot.sendMessage(chat_id, 'Per qual motivo vorresti conoscere chi è il mio programmatore?')
        elif (command == 'Help') or (command == '/help'):
                 bot.sendMessage(chat_id, 'Spiacente! nessun help disponibile...')
        elif (command == 'Login') or (command == '/login'):
                 bot.sendMessage(chat_id, 'Oh si! loggati tutto!.. anzi no.. lascia scritto username e password del tuo paypal!')
        elif command == '/riavviailraspberrypihkjgkghjkghkghjghjghjgjhghjgjhgjhghjghjvbvvvv':
            bot.sendMessage(chat_id, 'Riavvio in corso...')
            os.system("sudo reboot")
        else:
             bot.sendMessage(chat_id, 'Non ho capito..')
         
    else:
         bot.sendMessage(chat_id, 'Spiacente, non ti conosco!')
         bot.sendMessage(chat_id, 'Codice conversazione: %s' % sender)
         print 'tentativo di contatto da utente sconosciuto: %s' % sender
         

TOKEN = 'ToKeN'
bot = telepot.Bot(TOKEN)
bot.notifyOnMessage(handle)
print 'Sono in attesa ...'

while 1:
    time.sleep(5)
`

this is what i can reach... no more..

**Comment by nickoala** [comment]
Here is a quick example. It should be quite close to what you want:

```python
import sys
import telepot
from telepot.delegate import per_chat_id, create_open

class Questioner(telepot.helper.ChatHandler):
    QUESTIONS = [
        'What is your name?',
        'How old are you?',
    ]

    def __init__(self, seed_tuple, timeout):
        super(Questioner, self).__init__(seed_tuple, timeout)

        # Remember which question you are asking
        self._qindex = -1

    def on_chat_message(self, msg):
        # Display answer to your questions
        if 0 <= self._qindex < len(self.QUESTIONS):
            answer = msg['text']
            print '%d. %s %s' % (self._qindex, self.QUESTIONS[self._qindex], answer)

        # Advance index to next question
        self._qindex += 1

        # Send question to user, or tell him no more questions.
        if self._qindex < len(self.QUESTIONS):
            self.sender.sendMessage(self.QUESTIONS[self._qindex])
        else:
            self.sender.sendMessage('No more questions. I am done.')


TOKEN = sys.argv[1]  # get token from command-line

bot = telepot.DelegatorBot(TOKEN, [
    (per_chat_id(), create_open(Questioner, timeout=20)),
])
bot.notifyOnMessage(run_forever=True)
```

1. You should maintain a separate sequence for each user. That's why I use `DelegatorBot` instead of the basic `Bot`. Each user will be served by a separate `Questioner` object.

2. Inside `Questioner`, there is a list of `QUESTIONS`.

3. Each `Questioner` has a `_qindex` remembering which question is being asked. Initially, there is no question being asked, so `_qindex` is `-1`.

4. On receiving a message from a user, `_qindex` is incremented and the next question is sent.

This should be a good starting point for you. But I want to remind you that there is no substitute for learning the craft yourself. There is only so much I can do in this limited space, with my limited resources and time.

**Comment by dany250** [comment]
@nickoala  uhm.. could you please contact me on skype? 
danyhome87

**Comment by dany250** [comment]
Well... this probably will be kinda messy... but seems working for me!
[http://www.speedyshare.com/2j45C/Alternative-working.py](url) <<< can you download my code for check how i did?
is it a good way or not?

**Comment by nickoala** [comment]
Sorry, I really don't have time to review your code. As long as it is working for you, it is good.

**Comment by dany250** [comment]
@nickoala could you tell me how to block the script if the system is offline?
i tried to get the headers of www.google.com with httplib .. and it works.. but
i can't find the way to stop the script.. because every time the connection fails i get lots of errors of the system trying to retrive updates.. and the script halts.. (sorry that i'm so dummy!!)
