### ISSUE TITLE
Help needed [InlineKeyboardMarkup and InlineKeyboardButton]

### ISSUE THREAD

**Issue by its0x08** [nickoala/telepot#394]
Hello, is there any possible way to change InlineKeyboardButton's text after getting clicked ?
And if there is no way doing it using this library can you please add it?
Thanks in advance.

**Comment by QPotato** [comment]
You can [editMessageReplyMarkup](http://telepot.readthedocs.io/en/latest/reference.html#telepot.Bot.editMessageReplyMarkup) when receiving the Inline Button clicked update.

**Comment by its0x08** [comment]
@QPotato ive tried that but theres still something missing in my code..
