### ISSUE TITLE
Custom keyboard (help

### ISSUE THREAD

**Issue by devianpctek** [nickoala/telepot#397]
Hello, is there by any chance an example of using a custom keyboard like the one in the image?
I have this code I'm working on, but I would like to use this type of buttons instead of the user sending the commands, thanks in advance
`if command == 'start':
           bot.sendMessage(chat_id, "Bienvenido")
        elif command == '/snapshot':
           requests.get('http://localhost:8080/0/action/snapshot')
        elif command == '/status':
           webcontrol(chat_id, 'detection', 'status')
        elif command == '/pause':
           webcontrol(chat_id, 'detection', 'pause')`
![screenshot from 2018-06-06 21-26-21](https://user-images.githubusercontent.com/1848859/41075071-95a0ac8a-69d0-11e8-959b-ff5bd75407c9.png)

**Comment by nickoala** [comment]
Try:
```python
keyboard = ReplyKeyboardMarkup(keyboard=[['Add', 'List'], ['Settings', 'Web']])
bot.sendMessage(chat_id, 'Some text ...', reply_markup=keyboard)
```
As for the graphic icons, I don't think you can do that in Bot API. The closest thing is using an emoji. You have to look up the unicode of the emoji, though.

**Comment by devianpctek** [comment]
Sorry I just had time to test it until today, it works fine, thank you, about the graphics, that keyboard is from a bot called Skeddy, I don't know which framework they're using, I will try with unicode.

Thank you.

One more question, I'm using Telepot to get images/videos from https://github.com/Motion-Project
And everything works fine when I send the commands from Telegram, but I want to automatically send the most recent video created from Motion to Telegram, I know where and how to get it Motion has this configuration file where I can set a script to fetch that file, but I don't know how to pass it to my listener_bot can you give me a hint?

**Comment by devianpctek** [comment]
Well, I managed to set emoticons using https://pypi.org/project/emoji/
Looks pretty good to me

![image](https://user-images.githubusercontent.com/1848859/41502109-57fdff86-7178-11e8-913e-c2b255c7b21f.png)
