### ISSUE TITLE
"Sending video" status (help)

### ISSUE THREAD

**Issue by devianpctek** [nickoala/telepot#401]
Hello, I'm using a bot to send videos and pictures, I already accomplished this, but I want to get the "sending video" status when the bot is sending the video, just like in the attached picture, is it possible?
![image](https://user-images.githubusercontent.com/1848859/41679680-a75bb374-7494-11e8-8a62-58945c7327f0.png)

**Comment by nickoala** [comment]
Use [`sendChatAction`](https://core.telegram.org/bots/api#sendchataction)?

**Comment by devianpctek** [comment]
Thanks Nickoala, the telegram documentation tells me that I have to use the "upload_video" or "record_video" but I get a
NameError: global name 'upload_video' is not defined 😕

**Comment by devianpctek** [comment]
Got it, I need to use single quotation marks
bot.sendChatAction(chat_id, action = 'upload_video')
