### ISSUE TITLE
Missing `forward_from` in forwarded messages from channels

### ISSUE THREAD

**Issue by zumoshi** [nickoala/telepot#41]
Hello,
this is a typical update for a forwarded message (e.g. forwarded from a user to the bot):
```
{
    "update_id": 777882727,
    "message": {
        "message_id": 808,
        "from": {
            "id": 12312312,
            "first_name": "Bor",
            "last_name": "691",
            "username": "------"
        },
        "chat": {
            "id": 12312312,
            "first_name": "Bor",
            "last_name": "691",
            "username": "------",
            "type": "private"
        },
        "date": 1458924324,
        "forward_from": {
            "id": 32132132,
            "first_name": "his name",
            "last_name": "his lastname",
            "username": "------"
        },
        "forward_date": 1458826816,
        "text": "zarar ke nadare"
    }
}
```

as you can see a `User` object with key `forwarded_from` is present which informs that message was forwarded. however when a message is forwarded from a channel to the bot : 

![image](https://cloud.githubusercontent.com/assets/4184939/14048959/6fbaaf90-f2cf-11e5-8f6f-940ab3b68147.png)

_note: content type of message is irrelevant , a simple text message is also missing the forward_from_

as you can see the `forward_from` key is missing , as a result there is no way to tell if user has sent the message himself or it's forwarded from a channel , yet if the bot forwards the message it would appear from channel not the user.

i know there is not much that can be done at telepot to fix it , however i have tried contacting telegram support , telegram bot support ( @BotSupport ) and all the other ways i knew of.

due nature of my bot this is crucial for me to be able to tell the difference between a normal message and a forwarded one , so question is , can you think of any workarounds or if not , how should i proceed to submit a bug report to the telegram bot api ?

also as a side question , am i correct to assume this is a bug ? or is it working as intended ?

**Comment by nickoala** [comment]
Is this a bug? Well, only Telegram knows the true answer. According to the [Message object format](https://core.telegram.org/bots/api#message), the `forward_from` field is a `User`, which I believe cannot represent a channel.

My experience with @BotSupport is quite satisfactory. They may not reply quickly, but they do respond eventually. And they take real issues seriously.

So, I am afraid I cannot help you further on this issue. Telling Telegram about it is the most you can do.

**Comment by zumoshi** [comment]
ok , thank you. i'll report back when i hear from @BotSupport.

**Comment by nickoala** [comment]
You may re-open on any new development, if you want. I just hate looking at so many "issues".

**Comment by zumoshi** [comment]
no problem , i understand . the only thing i got so far from bot support was this after a week:

> Hi, thanks for pointing it out. I'll ask teh developers about this to see if it is intended or not.

**Comment by zumoshi** [comment]
they've added a `forward_from_chat` attribute to update on May 6th to messages forwarded from channels, it looks like this:
```json
"forward_from_chat": {
"id": -1001018114910,
"title": "Sharif CodeCup",
"username": "codecup",
"type": "channel"
},
```

**Comment by nickoala** [comment]
Cool. I am aware of that too. Telegram finally responds to your need!
