### ISSUE TITLE
User ID in Groups/Channel

### ISSUE THREAD

**Issue by PeterPawn2018** [nickoala/telepot#412]
I want to set up a Bot in an Group an a Channel, where the bot is listening to the messages.
The Problem is: i want the sender ID logged with the message.
through the "bot.message_loop(handle)" i only have the possibility to get the chat id (from the group/channel) but never the ID from the person who send the message.
Are there any Parameters i could Change for the message loop? 
Or how could i write a Message loop myself in python to get the whole string from the Telegram API?

**Comment by nickoala** [comment]
To get the sender ID, you look at the `from` `id` of the message. For example:
```python
msg['from']['id']
```

**Comment by PeterPawn2018** [comment]
Well i found the problem i had. Since the bot is in a channel and recieves the Message, it says "channel_post" instead of "message" in the beginning of the string.
It looks like this:
`{"ok":true,"result":[{"update_id":xxxxx,
"channel_post":{"message_id":`
instead of
`{"ok":true,"result":[{"update_id":xxxxx,
"message":{"message_id":25,"from":{"id":`

**Comment by nickoala** [comment]
To distinguish a channel post, I think you have to rely on `chat` `type`:
```python
msg['chat']['type']
```

**Comment by PeterPawn2018** [comment]
Ah thank you for the help. I got it now.
