### ISSUE TITLE
ReplyKeyboardMarkup and emojis. How can I add emojis to a custom keyboard

### ISSUE THREAD

**Issue by ducadegliabruzzi07** [nickoala/telepot#422]
How can I add an emoji to a custom keyboard to make it look like this?
![private_table_en](https://user-images.githubusercontent.com/43351999/45642058-7769bd00-bab7-11e8-876d-5541481f957c.png)
Can anyone give me some examples plz?

**Comment by nickoala** [comment]
Each emoji has a unicode. Search "emoji unicode" on the web and you should find some things.

**Comment by ducadegliabruzzi07** [comment]
Thanks. I have resolved my problem.
Go Telegram!
