### ISSUE TITLE
How can I call sendMessage in another thread?

### ISSUE THREAD

**Issue by Lukkasss** [nickoala/telepot#44]
Hello.

First of all, thank you for making this great work, I found your framework pretty good, and it's helping me alot.

I've ran into an issue, It's code-related to how can I call it from a thread... I've never worked with threads before, but now I need to receive messages using on_chat_message method and I need to pull data from a website in the same time.

Then I need to save this data do a database and send to registered users after.

So far, I managed to save it do DB working, but I can't send it to users, because I don't know how I can call it inside the getJSON thread...

Can you help a novice with an advice? :)

Here's the code I've so far:

https://gist.github.com/anonymous/b690bfe36bf4f454b49376fa3ac80ff4

Thanks in advance!

**Comment by nickoala** [comment]
Sorry, I have no time to review your code. If you can distill the issue to its core and reproduce it in the fewest lines of code, I may be able to help.

**Comment by Lukkasss** [comment]
Sorry for that... I just put the entire code because sometimes it's better to check if something else is causing the issue.

I'll put it in less lines, I need you help in this, I don't know what to do...


Here's a small part:

https://gist.github.com/Lukkasss/d04b6b0c6005f86e6ccd257734e213b1

I need to run always run getJSON() with 10 second delay, but I also need to run the bot message handle, because I can send a command to bot and it responds.

I didn't know if it's the better approach, but I put getJSON() function in another thread, so far is good, I can check the JSON in a 10 second loop, I can also insert the data into a database. What It's not working is, I need to call bot.sendMessage from inside this getJSON() function, to send the new data to registered users on bot.

Example:

Bot connects to a webside
Bot download the data
Bot saves the data on a database
Bot send the new data to users through bot.sendMessage() method
Repeat.

at the same time bot do the routine above, I need the bot to keep working and receiving chat commands if they are available, and so do work for a certain command, from a command list function.


Please, help me on this, I've no idea what to do anymore, I've tried to get help on Reddit and Stackoverflow but no lucky, no one seems to know how to do it right...

**Comment by nickoala** [comment]
So basically, you want to do two things simultaneously:

1. Respond to chat messages received by the bot
2. Retrieve some data from a JSON database, and send messages to some users

Is that correct?

**Comment by Lukkasss** [comment]
Yes. That's it.

I've been trying with threads, but haven't luck in getting bot.sendMessage to work... I guess it's because the instance is from another thread.

I've not tested with asyncio or coroutines, because I don't know how to do, and if it can do it.

**Comment by nickoala** [comment]
It seems you are quite new to programming. I suggest you use the traditional version of telepot, *not the async version*. So, do not use `telepot.async...`.

That said, I suggest you split your program into two. The first one, responsible for responding to incoming messages, looks like this:

```python
def on_chat_message(msg):
    # create a response and send

bot = telepot.Bot(TOKEN)
bot.notifyOnMessage(on_chat_message, run_forever=True)
```

The second one, responsible for querying database and send messages to users, looks like this:

```python
bot = telepot.Bot(TOKEN)

def getJSON():
    # query database and send
```

Just give the same token to both scripts. It is ok as long as **you don't receive messages in more than one script**. Script no.1 does both receiving and sending. Script no.2 does only sending. So you are ok.

**Comment by Lukkasss** [comment]
@nickoala Thank you, I'll follow your advices. I didn't know that I could run two programs with same token at same time.

Again, thank you for your clarification.
