### ISSUE TITLE
bot to chk activity over a particular period

### ISSUE THREAD

**Issue by ookOok101** [nickoala/telepot#45]
a bot that when called will look at the whole chat in a particular group and report the active users during a particular time , and then report the people in the group who did not participate during a particular time period from the list of group's users. Can this be done? How to go about it

**Comment by nickoala** [comment]
I am afraid I don't have time to answer such a general programming question with no clear specifications.

**Comment by ookOok101** [comment]
I wanted to know which functions to use and if such a bot is possible. whether the bot can read all activity in a particular group between particular times even when the activity is not initiated by the bot or when the messages are not directed towards the bot

**Comment by nickoala** [comment]
Such a bot would not be possible. Bots can only see messages addressed to them. I don't see how a bot can monitor "all activities" in a group.

**Comment by ravxl** [comment]
Nick,

  I`m afraid that you are wrong this time! You should check the privacy
mode: https://core.telegram.org/bots#privacy-mode The bot can be able to
get all messages or only those which starts with /


Att,
Ravel Leite

**Comment by chustaschus** [comment]
In groups the bot can not get all messages. You can check the telegram api


-All messages that start with a slash ‘/’ (seeCommands
<https://core.telegram.org/bots#commands> above)
-Messages that @mention the bot by username
-Replies to the bot's own messages

-Service messages (people added or removed from the group, etc.)

The bot does not receive all msg. You are wrong, Nick Lee is right


On 9 Apr 2016 3:19 a.m., "ravxl" <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> Nick,
>
> I`m afraid that you are wrong this time! You should check the privacy
> mode: https://core.telegram.org/bots#privacy-mode The bot can be able to
> get all messages or only those which starts with /
>
>
> Att,
> Ravel Leite
>
>
> On Fri, Apr 8, 2016 at 2:35 PM, Nick Lee <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > Such a bot would not be possible. Bots can only see messages addressed
to

**Comment by nickoala** [comment]
Ok, here's my understanding.

By default, privacy mode is enabled. When privacy mode is enabled, a bot will not receive all messages that people send to the group. It will only receive selected messages, e.g. those starting with a slash, those that @mention the bot by username, etc.

But privacy mode can be disabled, so that the bot will begin receiving all messages like an ordinary user.

@ravxl , if disabling privacy mode can achieve what you want, great! The lesson here is don't trust me. You can often get a quicker and better answer by reading the stuff yourself.
