### ISSUE TITLE
Async example doubles all the messages

### ISSUE THREAD

**Issue by par-n-go** [nickoala/telepot#46]
When running the code below I get double the messages for every message I send:
Normal Message: text private 888888888
Normal Message: text private 888888888

What am I doing wrong?

```
import sys
import asyncio
import telepot
import telepot.async

def on_chat_message(msg):
    content_type, chat_type, chat_id = telepot.glance(msg)
    print('Normal Message:', content_type, chat_type, chat_id)

def on_inline_query(msg):
    query_id, from_id, query_string = telepot.glance(msg, flavor='inline_query')
    print('Inline Query:', query_id, from_id, query_string)

    def compute_answer():
        articles = [{'type': 'article',
                        'id': 'abc', 'title': query_string, 'message_text': query_string}]

        return articles

    answerer.answer(msg, compute_answer)

def on_chosen_inline_result(msg):
    result_id, from_id, query_string = telepot.glance(msg, flavor='chosen_inline_result')
    print('Chosen Inline Result:', result_id, from_id, query_string)


TOKEN = sys.argv[1]  # get token from command-line

bot = telepot.async.Bot(TOKEN)
answerer = telepot.async.helper.Answerer(bot)

loop = asyncio.get_event_loop()
loop.create_task(bot.messageLoop({'normal': on_chat_message,
                                  'inline_query': on_inline_query,
                                  'chosen_inline_result': on_chosen_inline_result}))
print('Listening ...')

loop.run_forever()
```

**Comment by nickoala** [comment]
I run your code (using Python 3.4.2 and 3.5.1), send the bot **3 messages**, and this is what I got:

```
Normal Message: text private 01234556
Normal Message: text private 01234556
Normal Message: text private 01234556
```

3 messages, 3 lines of output. There is no double message.

What more clues can you give me?

**Comment by par-n-go** [comment]
Running in virtualenv on ubuntu 14.04 and Python 3.4.3. Have no clues to what can give this result. Normal version (not async) is working normally as expected.

**Comment by nickoala** [comment]
Can you modify the code to print out the actual messages? That way, we can be more sure that it is doubly-received.

**Comment by par-n-go** [comment]
```
import sys
import asyncio
import telepot
import telepot.async

def on_chat_message(msg):
    content_type, chat_type, chat_id = telepot.glance(msg)
    print('Normal Message:', content_type, chat_type, chat_id)
    print(msg['text'])

def on_inline_query(msg):
    query_id, from_id, query_string = telepot.glance(msg, flavor='inline_query')
    print('Inline Query:', query_id, from_id, query_string)

    def compute_answer():
        articles = [{'type': 'article',
                        'id': 'abc', 'title': query_string, 'message_text': query_string}]

        return articles

    answerer.answer(msg, compute_answer)

def on_chosen_inline_result(msg):
    result_id, from_id, query_string = telepot.glance(msg, flavor='chosen_inline_result')
    print('Chosen Inline Result:', result_id, from_id, query_string)


TOKEN = sys.argv[1]  # get token from command-line

bot = telepot.async.Bot(TOKEN)
answerer = telepot.async.helper.Answerer(bot)

loop = asyncio.get_event_loop()
loop.create_task(bot.messageLoop({'normal': on_chat_message,
                                  'inline_query': on_inline_query,
                                  'chosen_inline_result': on_chosen_inline_result}))
print('Listening ...')

loop.run_forever()
```

Listening ...
Normal Message: text private 186680214
test
Normal Message: text private 186680214
test
Normal Message: text private 186680214
test2
Normal Message: text private 186680214
test2

**Comment by nickoala** [comment]
Thanks. Can you try not using the routing table and only use a single handling function, like this:

```python
def handle(msg):
   ...

loop.create_task(bot.messageLoop(handle))
```

Thanks for doing that "on my behalf". I am just trying to whittle down the problem while not being able to reproduce it myself.

**Comment by par-n-go** [comment]
Same result.
I'll try to do it on another server
```
import sys
import asyncio
import telepot
import telepot.async

print(sys.version)
def handle(msg):
    content_type, chat_type, chat_id = telepot.glance(msg)
    print('Normal Message:', content_type, chat_type, chat_id)
    print(msg['text'])

def on_chat_message(msg):
    content_type, chat_type, chat_id = telepot.glance(msg)
    print('Normal Message:', content_type, chat_type, chat_id)
    print(msg['text'])

def on_inline_query(msg):
    query_id, from_id, query_string = telepot.glance(msg, flavor='inline_query')
    print('Inline Query:', query_id, from_id, query_string)

    def compute_answer():
        articles = [{'type': 'article',
                        'id': 'abc', 'title': query_string, 'message_text': query_string}]

        return articles

    answerer.answer(msg, compute_answer)

def on_chosen_inline_result(msg):
    result_id, from_id, query_string = telepot.glance(msg, flavor='chosen_inline_result')
    print('Chosen Inline Result:', result_id, from_id, query_string)


TOKEN = sys.argv[1]  # get token from command-line

bot = telepot.async.Bot(TOKEN)
answerer = telepot.async.helper.Answerer(bot)

loop = asyncio.get_event_loop()
loop.create_task(bot.messageLoop(handle))
#loop.create_task(bot.messageLoop({'normal': on_chat_message, 'inline_query': on_inline_query,'chosen_inline_result': on_chosen_inline_result}))
print('Listening ...')

loop.run_forever()
```

3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4]
Listening ...
Normal Message: text private 186680214
test
Normal Message: text private 186680214
test
Normal Message: text private 186680214
test2
Normal Message: text private 186680214
test2

**Comment by nickoala** [comment]
Yeah, give it a try on another environment. I have nothing intelligent to say ....

**Comment by par-n-go** [comment]
I still cannot understand why, but when I created another bot - problem disappeared. Still don't really understand why and how.
Thank you a lot for your time

**Comment by nickoala** [comment]
You can also try this:

1. Send a message to your bot
2. Open a browser, enter: `https://api.telegram.org/bot<token>/getUpdates`

Let me see the result. Thanks.

**Comment by nickoala** [comment]
Then, please do try that on the browser for me (for the *old* bot). I am suspecting it is very LARGE `update_id` that is causing the problem.

**Comment by par-n-go** [comment]
{"ok":true,"result":[{"update_id":345074195,
"message":{"message_id":1509,"from":{"id":888888,"first_name":"test","last_name":"test"},"chat":{"id":8888888,"first_name":"test","last_name":"test","type":"private"},"date":1459759719,"text":"test"}},{"update_id":345074196,
"message":{"message_id":1509,"from":{"id":888888,"first_name":"test","last_name":"test"},"chat":{"id":8888888888,"first_name":"test","last_name":"test","type":"private"},"date":1459759719,"text":"test"}}]}

**Comment by par-n-go** [comment]
for each message it receives two messages with the same message id, but with different update_id. The problem occurs only with one bot out of 3

**Comment by par-n-go** [comment]
recreated the bot and problem disappeared.

**Comment by nickoala** [comment]
I have considered for one moment, maybe I can make telepot to filter out the second duplicate message according to `message_id`, but then I realize this is clearly Telegram's problem. I should not cover up the problem for them.

Maybe you can report to @BotSupport about this issue, but since it can be solved so easily, maybe we will just keep silent and let Telegram do some more important things.

**Comment by par-n-go** [comment]
Thank you for such a great support and for amazing module that simplifies life a lot

**Comment by Onlinehead** [comment]
@par-n-go Got totally same situation with one of my bots and also cannot reproduce it with another one. That is 100% Telegram problem, not an API etc.
