### ISSUE TITLE
How to pass parse_mode

### ISSUE THREAD

**Issue by asbumste** [nickoala/telepot#48]
Is there a way to pass parse_mode via the sendMessage command? I want to send a message with links in it and need to set the parse_mode to markdown.

**Comment by nickoala** [comment]
Do it like this:
```python
bot.sendMessage(chat_id, 
                '*bold text*\n_italic text_\n[link](http://www.google.com)', 
                parse_mode='Markdown')
```

**Comment by asbumste** [comment]
Thanks, I tried that and it didn't work, turned out to be a different error
