### ISSUE TITLE
Sanitisation

### ISSUE THREAD

**Issue by martinsa0182** [nickoala/telepot#49]
Hi Nickoala.

This is a really excelent module and it's been a pleasure to work with...

Just a quick question, Does Telepot or the Telegram API sanitise the input?

I presume it is still vunerable to ddos attacks but wondering if there are any other security measures I need to put in place,

Thanks and looking forward to hearing from you,

TM

**Comment by nickoala** [comment]
What do you mean by "sanitise the input"?

By the way, I don't really know much about "security", so I don't expect to give any intelligent answers here. All communications with Telegram is over https, so the system is "secure" in this regard. Other than that, I don't know how to say more.

**Comment by martinsa0182** [comment]
I'm sure that's fine, It was mainly stuff like escape characters and such but I've been doing some testing and it seems to handle them fine.

Thanks for the speedy response,

TM
