### ISSUE TITLE
Async support will start at Python 3.5.1

### ISSUE THREAD

**Issue by nickoala** [nickoala/telepot#50]
#### To all Async Version Users
I am going to stop supporting Python 3.4 on around May 31<sup>th</sup>, 2016. **Async support will start at Python 3.5.1.** Keyword `async` and `await` will be used. Main reason for the change is that **it is much easier to ensure closing of connection using `async with`**, which is not available in Python 3.4. Let's all move with the times, and not get bogged down by the past.

Currently, telepot's async version already works with Python 3.5.1.

**This announcement only concerns telepot's async version. Traditional version is not affected.**

**Comment by ttsda** [comment]
this is great! I am really liking the async features in 3.5.1+
async python is the future :)

**Comment by nickoala** [comment]
This change is early by 2 weeks, in telepot 8.0
