### ISSUE TITLE
Location support

### ISSUE THREAD

**Issue by DrumSergio** [nickoala/telepot#51]
I've heard that Telegram Bots 2.0 now support location asking support. 

Will be this feature implemented in telepot?

Thank you!

**Comment by nickoala** [comment]
Hi @DrumSergio, thanks for asking. I am sure many people have the same question.

If everything goes well, expect **[Bot API 2.0](https://core.telegram.org/bots/2-0-intro)** support on or before **19<sup>th</sup> April, 2016**. Also expect some backward-incompatible naming changes. I am taking this opportunity to make names more consistent across telepot. Don't worry. The naming changes only involve replacing old names with new names. I will provide a migration guide once the new version is up.

**Comment by zumoshi** [comment]
@nickoala do you need any help with adding support for bot api v2 ? i can create some pull requests if it'll help speed up the update.

**Comment by nickoala** [comment]
@zumoshi, that's ok. I can manage it myself. I appreciate your offer. Heartfelt thank-you.

**Comment by nickoala** [comment]
Telepot updated, now at **version 7.0**, supporting **Bot API 2.0**

I have also made some backward-incompatible changes. Please see **[Migration Guide](https://github.com/nickoala/telepot/blob/master/migration-7-0.md)** for details.
