### ISSUE TITLE
`new_chat_participant` vs `new_chat_member`

### ISSUE THREAD

**Issue by zumoshi** [nickoala/telepot#54]
Hello,
while reading the bot api v2 changes i noticed they changed `new_chat_participant` to `new_chat_member`. right now api sends both these keys:
```
{'chat': {'id': -141713840, 'title': 'ASCII', 'type': 'group'},
 'date': 1460909329,
 'from': {'first_name': 'Bor',
          'id': 614*****,
          'last_name': '691',
          'username': '******'},
 'message_id': 1420,
 'new_chat_member': {'first_name': 'b_devbot',
                     'id': 190782732,
                     'username': 'b_devbot'},
 'new_chat_participant': {'first_name': 'b_devbot',
                          'id': 190782732,
                          'username': 'b_devbot'}}
```

right now telepot glance returns `new_chat_participant` as `content_type`. what are your plans when updating telepot , will you change glance to return `new_chat_member` instead?
that would break compatibility with old code , yet not changing it will break scripts in the future when they remove the duplicates eventually.

**Comment by nickoala** [comment]
Telepot just updated, now at **version 7.0**

I have decided to introduce other backward-incompatible changes. Please see **[Migration Guide](https://github.com/nickoala/telepot/blob/master/migration-7-0.md)** for details.

**Comment by zumoshi** [comment]
since you have changed the Major version number i can't complain about the breaking changes. if this was a bigger project i would've probably asked you to continue 6.x branch and back-port new features while keeping it compatible , but maintaining another branch would be too much hassle specially since you already have 2 versions (async/traditional). it seems i just can't postpone learning to use virtual envs anymore. on to having two versions of telepot until i find time to update all bots.
