### ISSUE TITLE
adding some kind of message routing

### ISSUE THREAD

**Issue by zumoshi** [nickoala/telepot#56]
Hello,
this is mostly a feature request , but before we add it to telepot we should discuss to see what would be the best way to add it.

so i saw this library today https://github.com/eternnoir/pyTelegramBotAPI .
while i prefer telepot there are some nice ideas implanted there. like the following : 
```python
@bot.message_handler(commands=['start', 'help'])
def send_welcome(message):
    bot.reply_to(message, "Howdy, how are you doing?")
```

you can specify `commands` , `content_types`, a `regex` or a lambda to determine which handler to be called. i don't specifically like the decorator syntax , but i feel something similar is missing from telegram.

i was thinking maybe we can subclass delegator bot to make an alternative class based handling , where instead of only dividing by message flavor we can have `on_audio_message` kind of functions , the new class should check availability of `on_{content_type}_message` method , if it was not present use`on_chat_message` or if that wasn't present either `on_message` would get the message.

furthermore we can add a routing scheme for commands , with a naming convention . i would propose something like `cmd_start` , where if message content type was text , and `text` started with `/start` availability of `cmd_X` would be checked before other methods described above.

a class constant could be used to define an array of command starters for them to be customizable.
e.g.:
```python
class MyBot(RouterBot):
    command_indicators = ['!','#','/']
```

with this class `cmd_start` would be callable by `/start` , `!start` and `#start`.
also it would be nice if we could override methods used for routing to add functionality and keep telepot extensible.

as for regex or lambda based routing , we can either have a new naming convention like `handler_X` which should return a tuple of `(condition, callback)` or some way of registering methods to the routing system. for example in the __init__ of class.
```python
class MyBot(RouterBot):
    def __init__(self):
        self.routes.append(condition, self.handler)
```

where condition would either be a regex (would be checked against `text` of message if available) or a lambda. or we can use decorators .

what is your opinion on this?
btw sorry for the long issue, i tried to write it briefly.

**Comment by wowkin2** [comment]
I prefer to use decorators, and possibility to specify commands, content types and lambdas - is great.
It is easy to implement and convenient to use

**Comment by wowkin2** [comment]
Currently, I use Django style: regexp with methods or simple dict with '/command': function

**Comment by zumoshi** [comment]
i prefer [cherrypy style routing](http://tools.cherrypy.org/wiki/RoutesUrlGeneration) , with function names as command. this way we can also provide any additional text as parameters. for example for handling a deep link we can have the following method:
```python
class MyBot(RoutingBot):
    def cmd_start(self):
        self.sender.send("welcome")

    def cmd_start(self, query):
        # do something with deep link query
        self.start()
```

so `/start` will call the first method while `/start abc` when bot is launched from `telegram.me/botname?start=abc` use the second method.

although decorators may be better suited for regex or lambda based routing but i personally prefer this over decorators for normal commands.

---

other than command based routing i also think an extra routing based on last sent keyboard would be nice. so we can define a method to handle keyboard responses and if user sends something from last sent keyboard that method would be called , we should be able to define such method while sending the keyboard to have different methods for each set of keys.

```python
class MyBot(RoutingBot):
    def cmd_start(self):
        # calculate or hardcode some_keyboard
        self.sender.send("welcome", reply_markup=some_keyboard, markup_callback=self.start_keys)

    def start_keys(self, selected_key):
        # do something with the selected_key
```

when `markup_callback` is defined sender method should store keys in a list and check that list in the routing method. of course this would only work in `per_chat_id` and `per_user_id` delegator bots and won't function properly for a `per_application` setup.

alternatively we may use a separate parameter for markup with callback, which would take a list of tuples with `(key_text, key_callback)` to be able to define a separate callback for each key.

**Comment by nickoala** [comment]
First of all, I don't prefer the decorator style in this case. It seems convenient, but I think it doesn't scale well to bigger applications - routing info scatters all over the places.

Second, thanks for bringing this up. You let me showcase the foresight/flexibility built into telepot. :smile: All routing scenarios you mentioned can be quite easily implemented within telepot's current structure. Let me explain.

Here is a Bot's `handle()` method. It just relays the message to an internal router's `route()` method ([source](https://github.com/nickoala/telepot/blob/master/telepot/__init__.py#L191)):

```python
def handle(self, msg):
    self._router.route(msg)
```

A `***Handler` does it similarly, except the first point of contact is `on_message()` ([source](https://github.com/nickoala/telepot/blob/master/telepot/helper.py#L324)):

```python
def on_message(self, msg):
    self._router.route(msg)
```

The key, as you can see, is the router, which is created this way ([source](https://github.com/nickoala/telepot/blob/master/telepot/helper.py#L313)):

```python
self._router = Router(telepot.flavor, {'chat': lambda msg: self.on_chat_message(msg),
                                       'callback_query': lambda msg: self.on_callback_query(msg),
                                       'inline_query': lambda msg: self.on_inline_query(msg),
                                       'chosen_inline_result': lambda msg: self.on_chosen_inline_result(msg)})
```

1. The routing table is easy to understand. The reason I sandwich in a `lambda` is because I don't want to force subclasses to implement *all* `on_***` methods. `lambda` basically delays evaluation to runtime, so those `on_***` methods can be defined as needed.

2. Pay attention to the first argument, the function `telepot.flavor` in this case. It is a *digest function* which turns a message into a key.

So, the routing goes like this. First, the message goes through the digest function, which produces a key. The router then uses the key to look up the routing table and calls the resulting function.

The digest function does not have to return the key *only*. It can return a tuple, first element of which is the key, followed by additional arguments to be supplied to the destination function.

If you don't like the default settings, `Router` has the methods [`set_key_function()`](https://github.com/nickoala/telepot/blob/master/telepot/helper.py#L284) and [`set_routing_table()`](https://github.com/nickoala/telepot/blob/master/telepot/helper.py#L287) which allow you to change them. As you subclass the bot or some handlers, you may re-set the router to your liking:

```python
self._router.set_key_function(...)
self._router.set_routing_table({...})
```

For example, if you want this:

- If chat message is a photo, call `on_photo`
- If chat message is a text and starts with `!`, `#`, or `/`, call `on_command` with the text behind as an argument
- For text that does *not* start with special characters, call `on_text`with the text as an argument
- Ignore everything else.

Digest function would be:

```python
def digest(msg):
    # get flavor and glance in one call
    f,g = telepot.flance(msg)

    if f != 'chat':
        return None

    content_type, chat_type, chat_id = g

    if content_type == 'photo':
        return 'photo'
    elif content_type == 'text':
        text = msg['text']
        if text.startswith(('!', '#', '/'))
            return ('command', text[1:])
        else:
            return ('text', text)

    return None
```

Routing table would be:

```python
{'photo': lambda *args: self.on_photo(*args),
 'command': lambda *args: self.on_command(*args),
 'text': lambda *args: self.on_text(*args),
  None: lambda msg: 0,
```

Methods would be:

```python
def on_photo(self, msg):
    ...

def on_command(self, msg, text):
    ...

def on_text(self, msg, text):
    ...
```

Haven't tested it, but should not be far off.

Yes, it takes some thinking, but it is so general that you can make up any kinds of routing imaginable.

Looking forward, if we want to include more forms of routing in telepot, **all we need is to provide more digest functions and more routing tables**. In fact, if you find any routing generally useful enough, I encourage you to just make it up and contribute to telepot if you don't mind.

**Comment by nickoala** [comment]
I guess I was too eager to showcase the foresight/flexibility of telepot :smile: that I forgot to mention something very obvious.

An easier way to create your own routing scheme is simply to override the method `handle()` (for `Bot`) or `on_message()` (for `***Handler`), like this:

```python
def on_message(self, msg):
    if something:
        self.on_something(msg)
    else:
        self.on_everything_else(msg)
```

Isn't it? :smile:

The value of digest functions and routing tables is their capability to be **packaged and distributed**. But if all you want is a routing scheme for your own one-time use, overriding that first point of contact may be the way to go.

**Comment by zumoshi** [comment]
i have used the on_message method to implant my own routing logic (although a lot more complicated than a few if's with over 95 lines in 3 methods :-s) but didn't notice the built in `Router` class. it seems interesting but somehow limited.

i propose the following 3 changes

1.nested routing tables
---
currently only one digest method is allowed, which makes digest method unnecessarily complicated.
it should be able to route the method using a nested routing table, so instead of making one method that can return `photo, cmd_start, cmd_help, cmd_about, inline_query` we would have two digest methods.
first one would return `photo, command, inline_query`.
than if the value was command instead of just calling the end method , second routing table would be called to determine the final method.

so something like this:
```python
{'photo': lambda *args: self.on_photo(*args),
 'command': (digest_method, {
     'start': self.cmd_start,
     'help': self.cmd_help,
     None: lambda msg: 0,
 }),
 'text': lambda *args: self.on_text(*args),
 None: lambda msg: 0}
```
where second digest method would be something like:
```python
lambda msg: re.split('[@\s]', msg['text'][1:])[0]
```

this can even go one lever further so we would first do flavor, than content_type than command.
to implant it we can add a check to see if `fn` is callable if it was not we can assume its a nested routing table, and call route method recursively.

2.dynamic routing table
---
the second limitation is that routing table is static. i would like to use a callable that returns a dict instead of a static dict.

assume that i have a bot that has my username hard coded in , and has two extra commands only for use by admin. in the current system i have to put a check in every single method accessible only to admin to check if user is admin. while with a dynamic system i could do this:

```python
self._router.set_routing_table({
    'text': self.on_chat_message,
    'command':(lambda msg: re.split('[@\s]', msg['text'][1:])[0], command_routes)
})

def command_routes(self, msg):
    routes = {
        'start': self.cmd_start,
        'help': self.cmd_help,
    }
    if msg['from']['id'] == self.admin:
        routes.update({
            'restart': self.cmd_restart,
            'block_user': self.cmd_blockusr,
        })
    return routes
```

any routing table regardless of nested level of it (whether the root one or just a sub table) should be able to have a callable instead of a dict.

3.ability to route keyboard commands
---

my last bot supports internationalization so the text for keyboard keys can't be hard coded and i don't know what they may be when coding. i would like to define a callback alongside the reply_markup to the sender helper function which would be called instead of normal routes if a key was chosen from keyboard (examples above in last post). for that to work we need the routing function to have a list alongside the routing table to check the response text against.
but since this feature also requires changes to sender class i suggest we focus on the first two for now. having nested dynamic routes allow this to implanted easily on the router side.

---
full example of a routing table that i would want to work:
```python
(lambda msg: flavor(msg), {
    'chat': (lambda msg: glance(msg)[0], {
        'text': (lambda msg: 'keyboard' if msg['text'] in self.last_sent_keys else 'other',{
            'keyboard': self.on_keyboard,
            'other': (lambda msg: 'command' if msg['text'][0] in ['#', '!', '/'] else 'text',{
                'command': (lambda msg: re.split('[@\s]', msg['text'][1:])[0], {
                    'start': self.cmd_start,
                    'help': self.cmd_help,
                    # or we can even supply a function here that dynamically generates this
                    # based on list of methods in class starting with cmd_X
                    # this method can be in included in helper class of telepot 
                }),
                'text': self.on_chat_message
            })
        }),
        'photo': self.on_photo,
        None: self.on_other,
    })
    'inline': self.handle_inline,
})
```

---
so to summarize:

- instead of two methods taking digest method and routing separately , we should get `(digest, routing_table)` as tuple
- each `route` can itself be another tuple of `(digest, routing_table)`
- each `routing_table` may be a callable returning a dict instead of a dict

if you apply all these and than add some extra logic to it covering different states of bot (sub menus) and accept strings instead of callable as route (which is name of a text stored in db to be sent) also accept lists of tuples for routes (can_handle*, callback**) where instead of a centralized digest method you let each route decide whether it can handle the route or not , you get something near my current 95+ line routing method.

_*each can_hanle  can be a string, a regex, or a callable_
_**each callback can itself be another nested route table , a string (to get from db and send) or a callable_

P.S. i'm not asking you to include my routing method in telepot (its a mess and extremely complicated , and not useful for all but very specific bots) but those three points can help a lot to make the routing more extensible.

**Comment by zumoshi** [comment]
i made a routing class based on my idea , please review it here:
https://gist.github.com/zumoshi/79b2bd5827aaa345d3f8cfcd4ad8fec9
the `proposed_router.py` file is backward compatible with current router.

please tell me of any bugs you find , or concerns that you have about it , also if you think i can improve it in any way. when it got good enough to get approved by you i'll make a pull request to replace telepot router with it.

i also suggest that we embed another router with pre-configured routes for a naming scheme similar to the one described in my first post in this issue. an example of such router is available in the same gist in  `example_extended_router.py`. although the extended router still has room for improvement.

**Comment by nickoala** [comment]
I admit I have not fully grasped the rationale behind your suggestions. That being said, here is what I think.

The essence of your suggestions revolve around two things:

- Nested routing
- Changing routing scheme on the fly

In my opinion, telepot already supports what you request, and it is *not* more complicated than what you have made. For example, nested routing can be accomplished like this, *easily*:

```python
sub_router = Router(...)

top_router = Router(digest, {'key1': ...,
                             'key2': sub_router.route})
```

Coupled with the methods `set_key_function()` and `set_routing_table()`, routing at all levels can be changed on the fly.

Another thing is, I find that you are too object-oriented :smile: Not everything has to be built into a class. If we want to include more routing schemes in telepot, **all we need is more digest functions and more routing tables, and probably some functions to generate pairs of them**. You don't have to put them in a subclass of `Router`, and then embed that new type of router in a `Mixin`, and then subclass that `Mixin` to make another type of handler, which I am expected to subclass from.

Imagine a module called `telepot.routing`, in which there are every exotic kind of digest functions and routing tables (generators) you can think of, two of which are:

```python
def chat_content_type(msg):
    content_type = telepot.glance(msg)[0]
    return content_type

def generate_content_type_routing_table(obj):
    return {
        'photo': lambda msg: obj.on_photo(msg),
        'text': lambda msg: obj.on_text(msg),
        ...,
        ...,
    }
```

When you want to route by content type, just do:

```python
routing_table = telepot.routing.generate_content_type_routing_table(self)

self._router.set_key_function(telepot.routing.chat_content_type)
self._router.set_routing_table(routing_table)
```

If a routing table does not fit your requirements exactly, change it:

```python
routing_table['text'] = my_router.route  # nested routing accomplished

self._router.set_routing_table(routing_table)
```

Imagine a plethora of digest function and routing tables floating around, you grab whatever you need to make a router, and nest the routers however you want.

Really, there is no need to create any more classes. It may still not fit your exact requirements, but I think it's flexible enough, if only you know how to use it. The only things that are worth adding, as I said, is more digest functions and more routing tables, and some functions that generate them (pairs of them, or classes of them).

Seriously, **your content-type routing and command-routing are good suggestions**. They would be a worthy addition to `telepot.routing` module. But one does not have to be embedded within the other (that is, the nesting does not have to be built in). They should be "on the same level". Let the developer nest them as he wants.

As of now, I think I WILL add the module `telepot.routing` encapsulating all kinds of fancy routing schemes. My priority is on some other issues right now. When I have time, I will try to replicate your suggestions in the way described above, if you haven't done that by then.

**Comment by zumoshi** [comment]
making things simple is usually harder. it would seem you have more skill than i do at that. while i may be able to accomplish the same task it usually results in a really complicated piece of code. so i usually like to hide the complicated part somewhere else and have code that does the important part visible only (hence why in my example i've created a complex and rather lengthy routing to get a readable and short usage code)

since telepot is very cleverly designed i was able to use my own routing class in my project without any patching to telepot being necessary so i'm not in a hurry but i would really like it to have pre-made routings similar to digest methods available for delegator bot in telepot itself.

i'm going to leave the design up to you since you outdid my expectations in both custom exceptions and the routing class that was embedded (and i've missed it :-s), but some suggestions for things to route based on:

- message mode (plain, replied message, forwarded message)
- message content_type
- message command (in case it included `/` as the first letter), this would preferably also send command and parameters (separated by space from command) as extra args
- message flavor

but the sending files with utf-8 in file name is a priority over this even for me, so no rush on this before that is solved.

as a side note, two extra things that my example did that was not addressed in your suggestion:
- letting the upper level handle the route if it was not handled in nested table, e.g. if message is a command, but cmd_command is not implanted, and there is no `None` key in the nested table for commands, `None` key in upper level would be called. but having another instance of routing class won't do this
- handling keyboard commands. you didn't really commented on the idea to add an option to sender class that would remember the last sent markup and signal the router to route differently if a key from keyboard was used.

**Comment by nickoala** [comment]
@zumoshi, just to give you a timeline, expect the new module `telepot.routing` on or before May 17<sup>th</sup>, 2016.

As for your two extra points:
- You want "error bubbling"? Here is a simple solution. In the sub-routing table, you can just include a `None` key which points to your top error handler. I am sure you can think of some situations where this simple solution may not be adequate, but for now, please just accept it as a solution. Telepot can't do everything for you.
- Recognize commands from the last custom keyboard? Solution: Why don't you just re-set the key function and routing table as you send the custom keyboard?

**Comment by zumoshi** [comment]
i'm using the custom router i gave in the gist for that particular project, most of my other projects won't need something as complicated and your solutions would be more than enough for them. thanks for considering my suggestions and working on them.

**Comment by nickoala** [comment]
New module `telepot.routing` and `telepot.async.routing`is now out, in 8.0. A bunch of key-function generators and routing-table generators. Please see **[reference](https://github.com/nickoala/telepot/blob/master/REFERENCE.md#telepot-routing)**.
