### ISSUE TITLE
Timeout problem

### ISSUE THREAD

**Issue by ShanksSGV** [nickoala/telepot#57]
Recently (I suppose nearly 10days) I'm getting this timeout error: 

  

> File "/usr/lib/python2.7/telegram/telegramclient.py", line 44, in sendMsg
>     self.bot.sendMessage(self.id_chat, self.message_notification)
>   File "/usr/lib/python2.7/telegram/telepot/__init__.py", line 203, in sendMessage
>     timeout=self._http_timeout)
>   File "/usr/lib/python2.7/telegram/telepot/__init__.py", line 147, in _post
>     response = requests.post(url, **kwargs)
>   File "/usr/lib/python2.7/telegram/requests/api.py", line 107, in post
>     return request('post', url, data=data, json=json, **kwargs)
>   File "/usr/lib/python2.7/telegram/requests/api.py", line 53, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/usr/lib/python2.7/telegram/requests/sessions.py", line 468, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/lib/python2.7/telegram/requests/sessions.py", line 578, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/lib/python2.7telegram/requests/adapters.py", line 449, in send
>     raise ReadTimeout(e, request=request)
> requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed    out. (read timeout=30)
> Exception in thread telegram (most likely raised during interpreter shutdown):
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
>   File "/usr/lib/python2.7/ciaotools.py", line 79, in run
> <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'ExitNow'

I've already updated the library (this morning), but the problem persists... 

Thank you for every support you can give me

Regards
Danny

**Comment by nickoala** [comment]
Can you post a simplified version of your code here?

**Comment by ShanksSGV** [comment]
I just call this sendMsg function (which calls telepot API), from another scritp:

```
import telepot

class TelegramClient():

def __init__(self, telegram_params):

        self.token = telegram_params["token"]
        self.id_chat = telegram_params["id_chat"]
        self.message_notification = telegram_params["message_notification"]
        
        self.bot = telepot.Bot(self.token)

def sendMsg(self):
        self.logger.debug("Invio Msg...")
        self.logger.debug(self.id_chat)
        self.logger.debug(self.message_notification)
        self.bot.sendMessage(self.id_chat, self.message_notification)
```

**Comment by nickoala** [comment]
I modified your code, removed the logger, and added a few lines that takes info from command line and calls `sendMsg()`:

```python
import telepot

class TelegramClient():
    def __init__(self, telegram_params):
        self.token = telegram_params["token"]
        self.id_chat = telegram_params["id_chat"]
        self.message_notification = telegram_params["message_notification"]

        self.bot = telepot.Bot(self.token)

    def sendMsg(self):
        self.bot.sendMessage(self.id_chat, self.message_notification)

import sys
token, id_chat, msg = sys.argv[1:]  # take info from command line

c = TelegramClient(dict(token=token, id_chat=id_chat, message_notification=msg))
c.sendMsg()
```

And everything works fine.
