### ISSUE TITLE
How do I test inline?

### ISSUE THREAD

**Issue by ninajlu** [nickoala/telepot#58]
Hi, I got the skeleton example working but was a bit confused how to test the inline functionality.
If I type @BOT_NAME into the inline, are the inline suggestions supposed to pop up? They don't currently and I'm not sure entirely why. One thing I noticed was that the @BOT_NAME did not autocomplete like the other bots I've seen with inline enabled. How do I fix this?

**Comment by nickoala** [comment]
You probably forgot to tell BotFather to enable inline mode for your bot:

- [`/setinline`](https://core.telegram.org/bots/inline) to get inline query
- [`/setinlinefeedback`](https://core.telegram.org/bots/inline#collecting-feedback) to get chosen inline result

**Comment by OrKoN** [comment]
I have the same problem. I have turned on inline settings via BotFather but I cannot sent an inline query in the Telegram - tried different clients.

**Comment by ninajlu** [comment]
Setinline solved it for me

**Comment by OrKoN** [comment]
@ninajilu so after setting setinline could you use your bot name for inline queries? Nothing extra?

**Comment by ninajlu** [comment]
Yes, that was all I needed to do.

On Fri, Apr 22, 2016 at 9:50 AM, Oleksii Rudenko <notifications@github.com>
wrote:

> @ninajilu so after setting setinline could you use your bot name for
> inline queries? Nothing extra?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/nickoala/telepot/issues/58#issuecomment-213334706>
>



-- 
Nina Lu
Jerome Fisher Program in Management and Technology
Class of 2016
University of Pennsylvania
(301)283-1645

**Comment by zumoshi** [comment]
in my experience telegram specially the desktop version tend to cache whether or not bots are inline, so if you have tried `@botusername` for inline before sending `/setinline` you have may to close/reopen the client for it to work. or wait a few minuets.
but nothing extra is needed , even if bot is not running telegram should display the Prompt for inline and display the loading spinner.
