### ISSUE TITLE
Need some help (force delegator bot end)

### ISSUE THREAD

**Issue by jaimehrubiks** [nickoala/telepot#6]
I need an easy way to force the end of a Delegator class instance. For example, imagine I want to use "/end" to force disconnection. I'm not very keen on python 3 and a little bit lost. Is it enough with throwing an exception? Thanks in advance.

**Comment by nickoala** [comment]
Assuming you are using the `ChatHandler` class, it has a method `close()`, which raises a `StopListening` exception, which would cause the task (or thread in the case of Python 2.7) to terminate.

And yes, you may terminate the task (or thread in Python 2.7) by raising any exceptions.

As further info, any classes decorated with the `@openable` class decorator have the `close()` method, which you may use to terminate the task (or thread in Python 2.7).

Sorry for the task/thread repetitions. I want to make it absolutely clear. Hope this helps.

**Comment by jaimehrubiks** [comment]
I'm sorry to annoy you again, but If you can help me with this i'd be grateful to you :)
The thing is, I managed to close connection in both ways:

* raise telepot.helper.WaitTooLong
* yield from self.close() #I think i did it this way too

But I need further help. I managed to make it work but don't know what changed and stopped working.
I am doing:

    if self._id not in playerList: playerList[self._id] = self

and then i need to call methods of other instances from another like this:

    yield from playerList.get(self._otheruserID).startPeer(self._id)

Also tried without "yield from". It seems to be throwing an exception and it restarts session

**Comment by josephhajduk** [comment]
Make sure startPeer is marked as an @asyncio.coroutine

**Comment by jaimehrubiks** [comment]
Everything working now, thanks to both

**Comment by nickoala** [comment]
A reminder to @jaimehrubiks , `self.close()` can be called directly like a regular function, without `yield from`.

And thanks to @josephhajduk for pointing out a mistake I used to make all the time. :smile:
