### ISSUE TITLE
Add import traceback in telepot/async/delegate.py

### ISSUE THREAD

**Issue by Jankovyj** [nickoala/telepot#70]
File "/usr/local/lib/python3.4/dist-packages/telepot/async/delegate.py", line 62, in wait_loop
    traceback.print_exc()
NameError: name 'traceback' is not defined

**Comment by nickoala** [comment]
Oops ... I will add `import traceback` in the upcoming version. Thanks for pointing it out.

**Comment by nickoala** [comment]
Fixed in 8.0
