### ISSUE TITLE
Confirm button for bot command

### ISSUE THREAD

**Issue by alavela** [nickoala/telepot#71]
Hi Nick,
I'm challenging to find the best way to implement a bot interaction requiring a command confirmation, such as /reboot (system reboot) with reply keyboard (better to use inline keyboard?) including the buttons "Confirm" and "Cancel". Can you suggest me the method to handle the user feedback with the buttons, avoiding to add the command "Confim" that must ONLY be selectable by the user within the /reboot interaction? With the below implementation, if customers sends anytime "Confirm" the reboot will be executed without any further confirmation... 
One last thing: the bot replies to only one specific chat_id, so I don't need to differentiate the users.
Thanks in advance!

Antonio

```
import sys
import telepot
from telepot.namedtuple import ReplyKeyboardMarkup, KeyboardButton, ReplyKeyboardHide, ForceReply

def on_chat_message(msg):
    content_type, chat_type, chat_id = telepot.glance(msg)
    print 'Chat:', content_type, chat_type, chat_id
    if content_type != 'text':
        return
    command = msg['text'].lower()
    if command == '/reboot':
        markup = ReplyKeyboardMarkup(keyboard=[[KeyboardButton(text='Confirm')], [KeyboardButton(text='Cancel')]], one_time_keyboard=True)
        bot.sendMessage(chat_id, 'Reboot?', reply_markup=markup)
    elif command == 'Confirm':
    ## EXECUTE sudo reboot...
    else:
        bot.sendMessage(chat_id, str('Wrong command!'))

TOKEN='xxxxx'
bot = telepot.Bot(TOKEN)
bot.message_loop({'chat': on_chat_message})
while 1:
    time.sleep(10)

```

**Comment by nickoala** [comment]
I want to confirm what do you mean by this?
> the bot replies to only one specific chat_id, so I don't need to differentiate the users.

**Comment by alavela** [comment]
The code above is just a snippet of the entire bot script so the mentioned filtering is missing...anyhow, I meant to say that I would be the only one, with my chat_id to talk to the bot...yes, in fact, this info might be worthless for my question...

**Comment by Enfors** [comment]
I'm new (hi!) so I have no idea what I'm talking about, but how about
setting a variable called awaiting_boot_confirmation to True when the
/reboot command is issued, and ONLY reboot when the confirm key is pressed
IF awaiting_boot_confirmation is true?

ons 4 maj 2016 kl 15:18 skrev alavela <notifications@github.com>:

**Comment by alavela** [comment]
Sorry @Enfors but it is not enough...I still not have a way to manage interaction using ReplyKeyboardMarkup and buttons not including other commands, such as /Confirm, /Yes, /No... I guess that the only way is with inline keyboard...

**Comment by nickoala** [comment]
@alavela, I want to make sure what you want to achieve before answering your question. Do you envision this sequence?

1. user sends a command `/reboot`
2. bot replies with a custom keyboard, with a "Confirm" and a "Cancel" button
3. user presses either button
4. bot responds accordingly, either go ahead with the reboot or not doing anything at all

**Comment by alavela** [comment]
@nickoala Yes! Exactly! thank you!

**Comment by nickoala** [comment]
You need a global variable to remember whether it is in the process of confirming:

```python
reboot_confirming = False

def on_chat_message(msg):
    global reboot_confirming
    content_type, chat_type, chat_id = telepot.glance(msg)

    command = msg['text'].lower()

    if command == '/reboot':
        bot.sendMessage(chat_id, 'Reboot?', reply_markup=...)
        reboot_confirming = True

    elif reboot_confirming:
        if command == 'Confirm':
            # REBOOT!!!!!
            reboot_confirming = False
        elif command == 'Cancel':
            reboot_confirming = False
        else:
            bot.sendMessage(chat_id, '??????')
```

**Comment by alavela** [comment]
Hi Nick! Thanks for your response, you and @Enfors were absolutely right! There was only a very stupid mistake on my implementation! 
Infact, the use of to lower on command definition:
```
...
command = msg['text'].lower()
...
```
needs to have confirm a 'confirm' and 'cancel' without the starting capital letter:
```
...
 elif reboot_confirming:
        if command == 'confirm':
            # REBOOT!!!!!
            reboot_confirming = False
        elif command == 'cancel':
            reboot_confirming = False
        else:
            bot.sendMessage(chat_id, '??????')
...
```
The case is closed. Thanks again!

**Comment by nickoala** [comment]
Oh, sorry for the uppercase. Good that you found it out.
