### ISSUE TITLE
editMessageText doesn't support chat_id/message_id combo

### ISSUE THREAD

**Issue by Arcaena** [nickoala/telepot#73]
On the [api docs](https://core.telegram.org/bots/api#editmessagetext) I noticed that we're supposed to be able to supply chat_id and message_id in editMessageText(), but it appears that Telepot doesn't allows us to do this.

**Comment by zumoshi** [comment]
Hello,
telepot does allow you to supply `chat_id` and `message_id`. from the [Reference](https://github.com/nickoala/telepot/blob/master/REFERENCE.md#telepot-Bot) :
```python
editMessageText(msgid_form, text, parse_mode=None, disable_web_page_preview=None, reply_markup=None)
```
msgid_form can be:

- a tuple of (chat_id, message_id)
- a tuple of (inline_message_id)
- a single value - inline_message_id

so, basically just call it this way:
```python
bot.editMessageText((chat_id, message_id), new_text)
```

**Comment by Arcaena** [comment]
ahh, I looked at the code and couldn't quite figure it out; it wasn't really clear when I looked at it. Sorry about that.
