### ISSUE TITLE
Bot not respond after few hours

### ISSUE THREAD

**Issue by evgsd** [nickoala/telepot#75]
My bot does not respond for requests but still running. Restart script fix it.

bot.message_loop(run_forever=True) in my script...

p.s. sorry for my english

**Comment by nickoala** [comment]
Hi @evgsd, I did an investigation into this problem, detailed in issue #23. This kind of problem is hard to fix because it cannot be reliably reproduced. All I can suggest is to keep a log of stdout and stderr, and see if you get some clues from there.

**Comment by nickoala** [comment]
I also want to add this. That your bot
> does not respond for requests but still running. Restart script fix it.

could mean a lot of possibilities. It could be a bug in your program and has nothing to do with telepot. Bottom line is, I cannot fix it unless I can reproduce it. And I cannot reproduce it (issue #23). So, I can't really fix it.

**Comment by evgsd** [comment]
ok. thanks. I add logger with debug level to script and wait)
