### ISSUE TITLE
DelegatorBot unable to stop delegates

### ISSUE THREAD

**Issue by wauterswim** [nickoala/telepot#77]
I have a delegator bot waiting for messages with bot.message_loop()

```
bot = telepot.DelegatorBot(TOKEN, [
    (per_chat_id(), create_open(test, timeout=900)),  
])
bot.message_loop()
```

Now when I want to stop the program I'm unable to stop the delegates and
they are trowing an exception as the delegate threats are not properly stopped yet.
Is there a method to stop the delegates of a delegatorbot?

```
Exception in thread Thread-2 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 505, in run
  File "/usr/local/lib/python2.7/dist-packages/telepot/delegate.py", line 72, in wait_loop
  File "/usr/local/lib/python2.7/dist-packages/telepot/helper.py", line 103, in wait
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'

```

**Comment by nickoala** [comment]
1. This exception puzzles me. It is thrown by this line:
    ```python
        except queue.Empty:
    ```
and seems to suggest `queue` is `None`. In that file, `queue` is an imported module. I have no idea why it becomes `None`.

2. If this problem happens only when you kill the program, I would have to give it a very low priority. There are more important problems to care about.

**Comment by wauterswim** [comment]
1. tested it with Queue directly, and got the same result

The problem arises when the main program loop is stopped 
The parent thread stops and all child threads are terminated 
[This](http://stackoverflow.com/questions/11620431/basic-python-multi-threading-issue) seems to be an example of the same exception.

2. Is there a way we can request DelegatorBot to stop (and also kill/close/stop all delegates (children))?
I think that would be a useful feature and also avoid this error

**Comment by nickoala** [comment]
Ok. Let me explain. The delegate is constantly trying to pull messages from a queue. When the queue is empty, it blocks. This happens inside a listener's `wait()` method. Each delegate has a `listener` object, so it basically loops over its `listener.wait()` calls, roughly equivalent to below:

```python
try:
    while 1:
        msg = j.listener.wait()
        j.on_message(msg)
except Exception as e:
    j.on_close(e)
```

The way I designed it, one natural way to exit the loop is to let it timeout, at which time `listener.wait()` would raise a `WaitTooLong` exception. Another way to exit the loop is to raise some exception inside the `on_message()` handler (e.g. calling `close()` would raise a `StopListening` exception, thus exiting the loop). 

So, my answer to your question is: **there is no simple way to stop all delegate threads in a top-down manner.** That being said, I am also wondering why this ability is important to you. Do you want to ensure the threads do some kind of cleanup as the program terminates?

Another thing I want to point out is, your `timeout` of 900 seconds seems too long. The purpose of that timeout is to stop the thread after a certain period of user inactivity. I know your case is just a test. In a real-life situation, you probably don't want to wait 900 seconds to conclude that a user has left. To me, 60 seconds is more than enough (in nowadays' short attention spans).

Unless you can convince me of this issue's importance, I don't feel motivated to fixing it.

**Comment by wauterswim** [comment]
Hi,

I understand, thank you for the explanation.
You are probably right this issue isn't very important 
It probably arose from a desire to control every possible exception.
For me you can close this issue.

Thank you for the good work and follow up on these issues
