### ISSUE TITLE
ImportError: cannot import name 'DependencyWarning'

### ISSUE THREAD

**Issue by NickGeek** [nickoala/telepot#80]
I'm getting this error when running 'import telepot' on Python 3.5.1 on Arch Linux. It was working not too long ago but now it throws the following:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/telepot/__init__.py", line 5, in <module>
    import requests
  File "/usr/lib/python3.5/site-packages/requests/__init__.py", line 61, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
ImportError: cannot import name 'DependencyWarning'
```

I'm running the latest version of Telepot (installed via pip)

**Comment by NickGeek** [comment]
Update: This was an issue in requests on Arch. Solved by reinstalling requests.

**Comment by alexandre-mbm** [comment]
@NickGeek, but how to do this with pip?

**Comment by paramono** [comment]
I managed to fix this issue just by upgrading urllib3:

`sudo pip install --upgrade urllib3`

**Comment by alexandre-mbm** [comment]
On Arch I always face problems to reconcile distro's packages with pip's packages.

**Comment by NickGeek** [comment]
@alexandre-mbm I did it with the AUR package.

**Comment by darkicekeel** [comment]
thanks for your replies, fixed an issue regarding layman thanks to you

**Comment by phoolchandra** [comment]
Solution for me:

$ sudo pip uninstall requests
$ sudo pip install requests
$ sudo pip uninstall docopt
$ sudo pip install docopt

**Comment by venerari** [comment]
me too.  thanks!
