### ISSUE TITLE
Connection behind a proxy

### ISSUE THREAD

**Issue by kalety** [nickoala/telepot#83]
Since 8.0, due urlliib3 change, telepot fails to connect when this connection is through a proxy. With telepot 7.1, no probems.

Regards

**Comment by nickoala** [comment]
I think you have to change the underlying class with which requests are made. By default, I use `PoolManager`. To go through a proxy, you need `ProxyManager`.

```python
import urllib3
import telepot.api

proxy_url = 'http://localhost:3128/'

telepot.api._pools = {
    'default': urllib3.ProxyManager(proxy_url=proxy_url, num_pools=3, maxsize=10, retries=False, timeout=30),
}

telepot.api._onetime_pool_spec = (urllib3.ProxyManager, dict(proxy_url=proxy_url, num_pools=1, maxsize=1, retries=False, timeout=30))
```

You may also need to put in a custom header. Read [urllib3 docs](http://urllib3.readthedocs.io/en/latest/managers.html#proxymanager) for details.

I have not tested the above code because I don't have a proxy, but it should not be far off.

**Comment by kalety** [comment]
Yesterday I tried "play" with urllib3 with no success... I will try your suggestion and I´ll tell you...

Thank you!!!

**Comment by kalety** [comment]
Perfect!!!! The connection was successful!.

I**f the proxy has autentication, then**:

`proxy_url='http://user:pass@proxyurl:port'`

Thousand of thanks for your quickly support and solution!!!!

**Comment by nickoala** [comment]
No problem :smile:

**Comment by paxapy** [comment]
just in case
for aio version of bot you can use

`proxy_url = "http://proxy.server:3128"

telepot.aio.api._pools = {
    'default': aiohttp.ProxyConnector(proxy=proxy_url, limit=10)
}

telepot.aio.api._onetime_pool_spec = (aiohttp.ProxyConnector, dict(proxy=proxy_url, force_close=True))
`
it works fine on pythonanywhere

**Comment by insanediv** [comment]
Hi guys,
I'm having troubles making proxy run with latest versions of aiohttp. That's because `aiohttp.ProxyConnector` has been deprecated. 
Any suggestions?
