### ISSUE TITLE
Sending a message to all users ?

### ISSUE THREAD

**Issue by diepes** [nickoala/telepot#84]
Is it possible to have a bot send a message to everyone connected to the Bot Channel ?

I am trying to do it without sending the same message over and over to each individual user.

**Comment by nickoala** [comment]
Shouldn't you be able to send a message to a *channel*?

**Comment by diepes** [comment]
I got it to work now in a Public and Private channel.
I created a Private Channel, and manually added the bot as a administrator.
I keep getting 

telepot.exception.TelegramError: (u'Bad Request: channel not found', 400, {u'error_code': 400, u'ok': False, u'description': u'Bad Request: channel not found'})

I tried with "ChannelName" and with "@ChannelName".

Then created Public channel telepot with url telegram.me/telepottest, using @telepottest worked.

So to make a Private channel, switch it to Public, pick the telegram.me/<url> , save and switch back to Private using the @<url>

**Comment by diepes** [comment]
It seems not to work for a Private channel, as a private channel only shows a "invite link" and not a "link"

**Comment by diepes** [comment]
Here i found a hack to do it.
http://stackoverflow.com/questions/33858927/how-to-obtain-the-chat-id-of-a-private-telegram-channel

**Comment by Ameerpappay** [comment]
Bro

I have recently deleted my account in telegram and I thus i lost my creatorship of channel.

But I can access it as a admin from my another number..

Can u help me on how to sent an individual message separately to all my members??
