### ISSUE TITLE
Bot API 2.1 is out

### ISSUE THREAD

**Issue by ttsda** [nickoala/telepot#86]
https://core.telegram.org/bots/api

> May 22, 2016
> 
>  - Bot API 2.1. Added more tools for group administrator bots. Your bot can now get a list of administrators and members count in a group, check a user's current status (administrator, creator, left the group, kicked from the group), and leave a group.
>  - Added new methods: getChat, leaveChat, getChatAdministrators, getChatMember, getChatMembersCount.
>  - Added support for edited messages and new mentions from Telegram v.3.9. New fields: edited_message in Update, edit_date in Message, user in MessageEntity. New value text_mention for the type field in MessageEntity.
>

**Comment by nickoala** [comment]
Thanks. Expect an update on or before **May 30<sup>th</sup>**.

**Comment by nickoala** [comment]
Updated, now at version 8.1. Please see **[changelog](https://github.com/nickoala/telepot/blob/master/CHANGELOG.md)**.
