### ISSUE TITLE
'Ignore' messages when bot offline?

### ISSUE THREAD

**Issue by Johen8** [nickoala/telepot#89]
Hi, I was testing the Bot Counter example and it works perfectly, but after I take it down, if I continue to send messages to him, when I start him again he will count all the messages that I sent him while he was offline. Is there any way to prevent or limit this? Thanks.

**Comment by zumoshi** [comment]
hello, please take a look at issue #35

**Comment by Johen8** [comment]
Yes, thank you very much!
