### ISSUE TITLE
Inline Photo bot returning corrupted images on iOS

### ISSUE THREAD

**Issue by pituseligmann** [nickoala/telepot#90]
Device: iPhone 6s
iOS version: 9.0.2

When using inline query on my bot, the results returned have the images corrupted. This is not happening on Telegram Web/Desktop/Android, only on iOS. This happens for photos as well as GIFs.

![Error image]
(https://i.imgur.com/mXANkMo.jpg)

Has anyone experienced something similar or has any idea what could be happening here? Thanks!

**Comment by nickoala** [comment]
Maybe you should report this to Telegram, instead of here?

**Comment by andreyoshev** [comment]
Same problem:

iPhone 6S,
iOS 10.

**Comment by giovannipiller** [comment]
I know that this ticket is very old, but just in case somebody else stumbles upon it:

make sure that you're including `photo_width` and `photo_height` in your answer for the inline query.
