### ISSUE TITLE
Callback_query called after DelegatorBot session has expired

### ISSUE THREAD

**Issue by yewsiang** [nickoala/telepot#91]
Hi,
Thanks a lot for the framework, it has made my development process really enjoyable!
Sorry if I'm asking a question that has been addressed but I couldn't find relevant questions.

I'm trying to ask the user a question and then allow the user to give me replies via a callback_query from an inline keyboard. After receiving the user's replies, I would also like to send the user a message. However, it is possible for the user to reply only after long periods of time (say 3hours) but the session would have expired.

Before the session expires, clicking on the "Some function" inline keyboard button would have allowed the DelegatorBot to send a message to the user saying "-- Your callback query has been called --". However, after expiry, clicking the button has no effect. Using "bot.sendMessage()" doesn't seem to work as well.

Is there a way to solve this?

Below is an example of what I'm trying to do.

`class MyBot(telepot.helper.ChatHandler):
    def __init__(self, seed_tuple, timeout):
        super(MyBot, self).__init__(seed_tuple, timeout)
        self.sender.sendMessage("-- Initialization --")

    def on_chat_message(self, msg):
        self.sender.sendMessage("-- On chat message --")
        markup = InlineKeyboardMarkup(inline_keyboard=[
                     [InlineKeyboardButton(text='Some function', callback_data='mycallbackfunction')],
                     [dict(text='Link to Forum', url='https://core.telegram.org/')]
                 ])
        self.sender.sendMessage("Some question for the user", reply_markup=markup)

    def on_callback_query(self, msg):
        query_id, from_id, data = telepot.glance(msg, flavor='callback_query')
        if data == 'mycallbackfunction':
            self.sender.sendMessage("-- Your callback query has been called --")
            bot.answerCallbackQuery(query_id, text='Callback query called!')

bot = telepot.DelegatorBot(TOKEN, [
    (per_chat_id(), create_open(MyBot, timeout=10)),
])
bot.message_loop(run_forever=True)`

Thanks so much for the help!

**Comment by nickoala** [comment]
1. You may lengthen the `timeout` (given to `ChatHandler`) to 3 hours or however long you want it to be. But this will keep alive a lot of "dormant" threads where the user has left but timeout has not been reached. I don't recommend this solution.

2. You may save the `ChatHandler`'s state just before it dies, by overriding its `on_close` method. Either save it in memory, in a file, or in a database. Retrieve those same information in the constructor, so whenever the same user makes contact again, he will have a `ChatHandler` with the same state as when he fell asleep 3 hours before.

3. Put some checking in `on_callback_query` to tell the user that his session has expired and "please send me a message to start over" or something like that. This way, you don't have to save state, but still make sure the user is doing what he is supposed to do.

As a general rule, you should always keep track of the stage a user is in, and check whether he is acting as expected. In your example, when you are expecting a callback query from him, he may send you 3 more chat messages in a row. You have to consider that, if you are making a serious application.

**Comment by yewsiang** [comment]
Hi Nick, 

1. There may be users that will click on the inline keyboard buttons only after a few days as well, so this solution will have a lot of alive "dormant" threads. Hence, I wouldn't be able to use this.

2. Saving the state of the ChatHandler is fine but after the session expires, I need to have a response when the user clicks on the inline keyboard buttons. Currently, clicking on the inline keyboard buttons will not have any effect since the session has already expired.

3. I'm hoping to use the on_callback_query function to restart the session so the user will be able to interact with the bot again. However, after the session expires, "on_callback_query" function will not be executed when the user clicks on the button.

The bot will be used in an application where users can ask and answer questions. Users will be receiving many messages and I hope to put a inline keyboard button for each question so that there can be ease of answering questions.
This is how I perceive the user to be using the inline keyboard buttons:
a. Messages with inline keyboard is sent to users
b. User opens Telegram and goes to the bot
c. User clicks on inline keyboard buttons (when a session has not been started) and this starts a session with a particular state, allowing the user to get down to replying the bot.

Sorry if there are obvious solutions to this problem! Thanks for taking the time to reply!

**Comment by yewsiang** [comment]
Actually, is there a way to have a bot (which listens for callback queries specifically)  that handles every user's callback queries which will run forever 
and 
another DelegatorBot (which handles each user in a different chat as in above) which will expire after each session?

**Comment by yewsiang** [comment]
So sorry, I realise that I can implement such functionality within DelegatorBot itself.

For example, instead of:
`bot = telepot.DelegatorBot(TOKEN, [
    (per_chat_id(), create_open(MyBot, timeout=10)),
])
bot.message_loop(run_forever=True)`

which will create threads that expire after 10s, we do:
`bot = telepot.DelegatorBot(TOKEN, [
    (per_application(), create_open(CallbackBot, timeout=None)),
    (per_chat_id(), create_open(MyBot, timeout=10)),
])
bot.message_loop(run_forever=True)`

which will create a bot that runs forever and which will be able to answer callback queries even if the session for the user has expired.

Thanks a lot!

**Comment by nickoala** [comment]
`per_application()` can do the trick. But it is not specific to one user; all users would share the same delegate. Are you ok with that?

**Comment by yewsiang** [comment]
May I know what are the implications of having all the users sharing the same delegate?
It seems like self.sender.sendMessage("Some msg") still works to send messages to the users.

**Comment by zumoshi** [comment]
hi,
when having a delegate per user you can store some user-specific variables in the delegate, for example wether bot is expecting a confirmation message from user or not, or what state is the bot in (what kind of response the bot is expecting from user)
in per-application mode all variables are shared between all bot users so this cannot be done, if you are no using this i am not aware of any other implications.
