### ISSUE TITLE
Delete messages in group

### ISSUE THREAD

**Issue by javierin** [nickoala/telepot#92]
Is there a way to have an administrator bot delete a message in a supergroup? I am looking for this feature as a way to auto moderate some content.

I have seen this https://core.telegram.org/method/messages.deleteMessages
However, I haven't seen reference for it anywhere. I've tried bot.deleteMessage and bot.deleteMessages but that seems not to work.

Thanks

**Comment by nickoala** [comment]
I don't know of a way to delete messages using the Bot API. The link you referred to is a part of the underlying Telegram communication protocol, a totally different thing from the Bot API.

**Comment by javierin** [comment]
Oh, thank you very much :)

**Comment by AdityaTelange** [comment]
For that

```
make the Group as SuperGroup
Promote the Bot to Group Admin
Give the bot All Admin Permissions
```

Noe the bot can delete any Message in the group Sent by anyone !
