### ISSUE TITLE
InlineKeyboardButton location

### ISSUE THREAD

**Issue by par-n-go** [nickoala/telepot#95]
I'm using async version on python 3.5.

How can I make an inline button that will ask user's location?

I tried this:
`[InlineKeyboardButton(text='Location', request_location=True)]`

But it gave me an error:

telepot.exception.TelegramError: ("Bad Request: Can't parse inline keyboard button: Text buttons are unallowed in the inline keyboard", 400, {'description': "Bad Request: Can't parse inline keyboard button: Text buttons are unallowed in the inline keyboard", 'error_code': 400, 'ok': False})

Sorry for troubling you

**Comment by nickoala** [comment]
Can you show me the entire call? Thank you.

**Comment by nickoala** [comment]
`request_location` is part of [KeyboardButton](https://core.telegram.org/bots/api#keyboardbutton) which is part of a *custom* keyboard, not *inline* keyboard. To make a custom keyboard with a location button, you do:

```python
ReplyKeyboardMarkup(keyboard=[[
    KeyboardButton(
        text='Location',
        request_location=True
    )
]])
```
