### ISSUE TITLE
Next up: telepot 8.2, on or before July 5

### ISSUE THREAD

**Issue by nickoala** [nickoala/telepot#99]
Hello Everyone,

I have been silent lately, because I am working on 8.2 which will have the following improvements:

- **Revamped documentations**: Complete reference, new tutorial, and a usage page. I am adding docstring to source code. Hopefully docs will be more easily maintained in the future.

- **Much better support for callback query**: Being usable in a private chat, in a group, and with inline mode, callback query introduces a new level of complexity. While you can always write your own `per_*` functions and `*Handler` class, built-in support is lacking. 8.2 will remedy this situation.

- **More updated examples** to illustrate new Bot API features.

- **Fix any outstanding issues** (wherever I can), such as issue #87, #93, #96, etc

**Expect 8.2 on or before July 5**. It likely won't take that long. I am just giving myself some leeway. 8.2 being my priority, everything else would take a backseat. Expect delay in issue response. Sorry for all inconvenience, confusion, frustration, and exasperation.

**Comment by Searinox** [comment]
Hello, once a bot is created and assigned a message_loop(), how can it be stopped without terminating the entire program?

**Comment by nickoala** [comment]
Ok, 8.2 is out. Handling of callback query is still unsatisfactory. But things are taking shape. Treat it as a preview. For experienced users, check out the [callback query examples](https://github.com/nickoala/telepot/tree/master/examples/callback).

Here are the major changes:

1. **Async version has been moved to `telepot.aio`** to avoid collision with `async` keyword. Using the old naming `telepot.async`, this would cause a syntax error:

    ```python
    import telepot.async.helper

    async def foo():
        e = telepot.async.helper.Editor(...)
    ```

    You may use `import ... as ...` to avoid having `async` in the code, but I found that very troublesome, and this problem can be extremely confusing to someone unaware.

2. Let me explain the state of callback query handling. Callback query is unlike other flavors of messages because of its *transient* nature. A callback query is possible only *after* you have sent an inline keyboard. Once you get a response from the user, you most likely would cancel the inline keyboard (by editing the original message) and remove the possibility of a callback query. If you don't cancel the inline keyboard, you probably don't care about further callback query anyway. So, listening for callback query is a on-and-off thing.

    Another complexity is callback query's *dual origin*. One originating from a chat and one originating from an inline message have different structures. The latter case is particularly "dynamic" because `inline_message_id` is assigned by Telegram servers and we can't know beforehand how to capture such a callback query.

    Message has 5 flavors, and telepot kind of divides them into 3 groups:
    - `chat`, `edited_chat` - chat-related
    - `inline_query`, `chosen_inline_result` - inline query-related
    - `callback_query` - transient

    Most [seeder functions](http://telepot.readthedocs.io/en/latest/reference.html#delegatorbot) and `*Handler` objects deal with the first 2 groups, or both. Callback query is handled in another fashion.

    It is possible to know when to listen for callback query. It is *after* we have sent an inline keyboard with some `callback_data`. We can intercept calls to `sendMessage()` and company to know whether to expect some callback query. Inline mode is more complicated. We have to intercept calls to `answerInlineQuery()`, remember which answers contain an inline keyboard, and wait for a chosen inline result. If the chosen inline result indicates an answer with an inline keyboard, we have to listen for callback query with that `inline_message_id`. We should also intercept calls to `editMessageText()` and company to recognize when an inline keyboard disappears (`reply_markup` being empty or devoid of `callback_data`). In that case, we no longer need to listen for callback query.

    All these logic is implemented in `CallbackQueryCoordinator`. Its job is to intercept calls to a bot's `send*()`, `edit*()`, and `answerInlineQuery()` methods, so the control of listening for callback query can be hidden from the user. Every `*Handler` has its own `CallbackQueryCoordinator`, so every delegate does its own interception. A bot's `send*()`, `edit*()`, and `answerInlineQuery()` methods are left unchanged and remain pure wrappers to Bot API methods.

    And then, there is the problem of timeout. Before callback query, we only have *inactivity* timeout. Whenever inactivity lasts for a period of time, we terminate the delegate. Now with callback query, we have another kind of timeout - the time after which we stop waiting for answers. Imagine this. A `ChatHandler` sends an inline keyboard to a *group*, expecting an answer from each of the group members. Normally, the `ChatHandler` terminates after 10 seconds of group silence (inactivity timeout), but should we expect all members to respond within 10 seconds? Should we lengthen the inactivity timeout to 1 minute, 5 minutes, ...? One result of lengthening inactivity timeout is to have more threads active at the same time. Do we want that? What if we keep inactivity timeout at 10 seconds, but allow group members longer time to respond? Here comes another problem. After the `ChatHandler` terminates (inactivity timeout), how does a callback query resurrect the correct `ChatHandler` (because `per_chat_id()` does not work on callback query)?

    **Inactivity timeout and callback query timeout should be two separate concerns, but telepot's current architecture does not allow them to be separate concerns.** This is the problem I am going to tackle. I will outline upcoming improvements in another article.

I apologize to anyone who expects more from this version. It turns out to be more involved than I thought, and documentations are still not as complete as I want them to be. I encourage you to check out **[all the examples](https://github.com/nickoala/telepot/tree/master/examples)**. An example is worth a thousand words.

**Comment by nickoala** [comment]
Version 9.0 is out. Callback query handling is satisfactory. I will update docs in coming days.
